### ISSUE TITLE
[Task]: Make anomalib PEP 561 compliant for mypy

### ISSUE THREAD

**Issue by ORippler** [openvinotoolkit/anomalib#1015]
### What is the motivation for this task?

When installing anomalib as a package, mypy starts to complain about missing type stubs. Seeing that anomalib is mostly (if not fully) typed, it would be nice to make the package PEP561 compliant (currently I ignore `anomalib` for mypy)

### Describe the solution you'd like

Make the package PEP 561 compliant. Could potentially be as easy as adding a `py.typed` at the root of the shipped package directory. Note that I am not an expert in building/shipping python packages, so I might also be wrong on this

### Additional context

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by WenjingKangIntel** [comment]
anomalib_Team3 working on this.

**Comment by ORippler** [comment]
I just did an install of anomalib==0.5.0 from pypi and py.typed was not present in the anomalib folder, so it's not yet fully compliant.
