### ISSUE TITLE
[Task]: Testing error

### ISSUE THREAD

**Issue by sagarsirbi05** [openvinotoolkit/anomalib#1020]
### What is the motivation for this task?

I am new to anomalib library and am currently training and testing the padim model on MVTec AD dataset and have encountered error in the following:

I have trained my model on MVTec AD bottle dataset and when I try to fit my model, I encoured the following error
command: `trainer.fit(model=model, datamodule=datamodule)`

error: `---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_3376819/1994785069.py in 
     10     val_check_interval=1.0,
     11 )
---> 12 trainer.fit(model=model, datamodule=datamodule)
     13 # trainer.fit(model=model, datamodule=datamodule,
     14 #             ckpt_path='/workspaces/research_anomaly_detection/anomalib/notebooks/mdl_ckp.ckpt')

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    606         model = self._maybe_unwrap_optimized(model)
    607         self.strategy._lightning_module = model
--> 608         call._call_and_handle_interrupt(
    609             self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    610         )

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     36             return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     37         else:
---> 38             return trainer_fn(*args, **kwargs)
     39 
     40     except _TunerExitException:

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    648             model_connected=self.lightning_module is not None,
...
-> 1704                     raise child_exception_type(errno_num, err_msg, err_filename)
   1705                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'mo'
`

### Describe the solution you'd like

It would be great if anyone can help me in this regard.

**Comment by ajaye2** [comment]
Hello, how were you able to solve this?

**Comment by samet-akcay** [comment]
@ajaye2, are you having the exact same problem?

**Comment by mrub1** [comment]
Hello @sagarsirbi05 , @ajaye2, @samet-akcay .
I am experiencing the same error  < FileNotFoundError: [Errno 2] No such file or directory: 'mo'>
Were you able to resolve it ?
Thank you so much.

**Comment by LucasJohannsenShadow** [comment]
Hi I got the same issue

**Comment by OPaivaHeitor** [comment]
Hello, I'm running into the same problem during training. Is there a solution for this?

**Comment by martin0258** [comment]
@ajaye2 @samet-akcay @mrub1 @LucasJohannsenShadow @OPaivaHeitor 

Sharing my findings and the solution (at least works for me) in case you still need help:

`mo` is actually a tool provided by OpenVINO, so you have to install it for it to be accessible. 

If using pip, it could be installed with the follwoing command ([ref](https://github.com/openvinotoolkit/openvino/issues/9167#issuecomment-993787517))

```shell
pip install --no-deps openvino-dev
```

If you encountered another runtime error such as `ModuleNotFoundError: No module named 'openvino.runtime'`, try
```shell
pip install openvino
```

Maybe the error message could be improved by first checking if `mo` is installed and accessible in PATH and showing instructions to guide people to install it (sounds like a pretty minor PR but a bit helpful)?
