### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by alexriedel1** [openvinotoolkit/anomalib#111]
**Describe the bug**
When training PatchCore, I'm getting the following error:
`IndexError: tensors used as indices must be long, byte or bool tensors`
caused by the line https://github.com/openvinotoolkit/anomalib/blob/c33d25a19f1b622a3dd354e81976257d9bac6d7f/anomalib/models/components/dimensionality_reduction/random_projection.py#L85

**To Reproduce**
Run the PatchCore algorithm on CPU (maybe on GPU too)

The problem can be solved by casting to `c_idx` to `c_idx.long()`

**Comment by innat** [comment]
@samet-akcay 
Could you please take a look into this issue? I've encountered this as well. I tried also PADIM, it worked but PatchCore failed with the above-mentioned error. Also please re-check other architecture.

**Comment by samet-akcay** [comment]
Hi @alexriedel1 and @innat . Thanks for spotting this. @alexriedel1 if you prefer, feel free to create a PR for this to become a contributor! If not, we'll try to immediately add a fix

**Comment by samet-akcay** [comment]
Have you guys seen this issue when you train patchcore on GPU

**Comment by alexriedel1** [comment]
> Hi @alexriedel1 and @innat . Thanks for spotting this. @alexriedel1 if you prefer, feel free to create a PR for this to become a contributor! If not, we'll try to immediately add a fix

I did a PR request. I haven't tried to reproduce the issue on GPU
