### ISSUE TITLE
How to specify the GPU id for training?

### ISSUE THREAD

**Issue by William9Baker** [openvinotoolkit/anomalib#1156]
Is it in the "trainer.devices" parameter in the config.yaml? I trird but it didn't work.

**Comment by William9Baker** [comment]
Every time it trains with a GPU card of number 0. I want to change the id, but I can't find where to modify it.

**Comment by blaz-r** [comment]
Hello.
As per official Lightning docstring, `trainer.devices: id` in combination with `trainer.accelerator: gpu` should work. Can you try this?

**Comment by blaz-r** [comment]
@William9Baker was this issue solved?

**Comment by William9Baker** [comment]
> @William9Baker was this issue solved?

Yep, I changed the 'devices: 1' to 'devices: [2]' in 'config.yaml', and it works.

**Comment by goldwater668** [comment]
@William9Baker @blaz-r 
engine = Engine(max_epochs=10,task="classification",accelerator='gpu',devices=[1,2])
I specify the GPU ID number according to the above code. Why do the following results still appear? Can’t I specify it?
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
