### ISSUE TITLE
[Bug]: When I use 'AUPRO' in config.yaml, I get an error 'ValueError: Input image shape must be (*,1,H,W). Got: torch.Size([8, 1])'.

### ISSUE THREAD

**Issue by William9Baker** [openvinotoolkit/anomalib#1162]
I changed metrics.image.AUROC to metrics.image.AUPRO, but it got this error.

**Comment by William9Baker** [comment]
This error is located at 'cca = connected_components_gpu(target)', when it runs to 'target = target.unsqueeze(1)' for the first time, the format of 'target' is 'torch.Size([8, 1, H, W])', but it changes to 'torch.Size([8, 1])' when running here for the second time. I'm so confused.

**Comment by blaz-r** [comment]
Hello, since you closed this as completed, did you figure out what was the problem?

**Comment by francescodalmonte** [comment]
Hi! I am getting the same error here... @William9Baker did you manage to solve it?

**Comment by blaz-r** [comment]
@francescodalmonte if this is for Efficient AD, did you set batch size of training to 1?

**Comment by 1094558673** [comment]
@blaz-r @francescodalmonte @William9Baker 
Hello, I had the same problem while training efficient_ad, "ValueError: Input image shape must be (*,1,H,W).Got: torch.Size([53, 1])"
And if I **import AUPRO in pixel scale in config, there will be no problem, but if I import AUPRO in image scale, there will be an error.** I am very confused about this and would like to ask if you have any solutions. Thank you very much.

**Comment by blaz-r** [comment]
I don't understand this. Are you using AUPRO in image metrics? If that's the case, it's not valid since AUPRO is a pixel metric.

**Comment by 1094558673** [comment]
> I don't understand this. Are you using AUPRO in image metrics? If that's the case, it's not valid since AUPRO is a pixel metric.

So that's it! I will go to study the specific meaning of AUPRO. Thank you very much for your timely reply.
