### ISSUE TITLE
Can I customize the checkpoints directory

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#1178]
Default save to C drive user directory

But I don't have enough space on my C drive

Need to modify the default checkpoint folder

**Comment by samet-akcay** [comment]
Hi, you could modify the below path:
https://github.com/openvinotoolkit/anomalib/blob/27876c851eb97a5b081b89a0059b7cbb2cad9688/src/anomalib/models/efficient_ad/config.yaml#L53

**Comment by alexriedel1** [comment]
You would have to modify the code a bit I guess: https://stackoverflow.com/questions/52628270/is-there-any-way-i-can-download-the-pre-trained-models-available-in-pytorch-to-a

**Comment by monkeycc** [comment]
Thank you for your help

Problem solving

**Comment by blueclowd** [comment]
Hello, is there an variable we can config in the Python API?
