### ISSUE TITLE
[Task]: Support list config for normal_dir and normal_test_dir of folder format

### ISSUE THREAD

**Issue by fanchuanster** [openvinotoolkit/anomalib#1195]
### What is the motivation for this task?

I am frustrated to merge multiple categories into a single normal dir (normal_test_dir as well), wondering it it makes sense to support list config for them?

dataset:
  name: model
  format: folder
  path: /app/data/trainData
  normal_dir: [folder1, folder2]
  normal_test_dir: [testfolder1, testfolder2]

this is the error it throws when it's a list config:

TypeError: expected str, bytes or os.PathLike object, not ListConfig

### Describe the solution you'd like

support list config for normal_dir and normal_test_dir of folder format

**Comment by samet-akcay** [comment]
@djdameln, any thoughts?

**Comment by harimkang** [comment]
I think it's a good feature for user convenience. I'll take a look and share my progress.
