### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Youskrpig** [openvinotoolkit/anomalib#121]
Hi，there are some codes which make me confused, hope to get your answer.
1.  In padim/config.yaml, what does nncf(belongs to optimization) mean? and what does function update_nncf_config mean?
2.  If i want to use multiple gpus to train, how should i set? and there are many parameters in trainer section which i wanna figure out each is used for and be clear which can be tuned or not.

**Comment by samet-akcay** [comment]
Hi @Youskrpig, [NNCF](https://github.com/openvinotoolkit/nncf) is a framework for inference optimization. If fast inference is not your concern, you could then ignore this setting.

Regarding multiple gpus to train there is `gpus` flags in trainer settings. For more details, you could refer to this PyTorch Lightning Trainer [documentation](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html).

We are currently working on a new CLI approach to document the parameters and configurable from the terminal.
