### ISSUE TITLE
[Bug]: Outdated Documentation

### ISSUE THREAD

**Issue by Spicermi** [openvinotoolkit/anomalib#1227]
### Describe the bug

Lack of working code examples in the anomalib README and github.io page.

The 'get started' section for Docker here: https://openvinotoolkit.github.io/anomalib/getting_started/installation/docker/index.html refers to files and code snippets that no longer exist/work.  For in
For example, tstance, it suggests building off a Dockerfile in the main anomalib directory that does not exist, with no explanation of what the .ci folder is and how to use it for containerized deployments.

Further, the anomalib README does not work as expected and seems to be outdated -- the 'get started' training quickstart saves padim in ..weights/lightning, and the inference quickstart attempts to load the model weights from ../weights/ . 

### Dataset

Other (please specify in the text field below)

### Model

PADiM

### Steps to reproduce the behavior

Follow guide on README and https://openvinotoolkit.github.io/anomalib/getting_started/installation/docker/index.html

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Expect to follow the directions of the README/ Get Started guides and for the code snippets to work.  Makes it much more challenging to get started with anomalib and encourage others to learn it as well.

### Screenshots

N/A

### Pip/GitHub

GitHub

### What version/branch did you use?

v.0.6.0

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@Spicermi, we are aware of this. The team have been working on the development of anomalib 1.0, which will drastically change the existing API and documentation. This is the main reason why we did not have time to invest in the documentation :/

**Comment by Spicermi** [comment]
That's very fair, thanks for the update.  Is there a rough timeline on when 1.0 will be out?

**Comment by samet-akcay** [comment]
We are working hard to release it in October 🤞

**Comment by Spicermi** [comment]
Very exciting, thanks for the quick responses!
