### ISSUE TITLE
ModuleNotFoundError: No module named 'anomalib.utils.callbacks'

### ISSUE THREAD

**Issue by hqxiao** [openvinotoolkit/anomalib#125]
**Describe the bug**
-anomalib package install error, seems the package released do not include all function of utils file

**To Reproduce**
1. Go to https://pypi.org/project/anomalib/0.2.4/#files download the file anomalib-0.2.4-py3-none-any.whl
2. pip install anomalib-0.2.4-py3-none-any.whl
3. cd anomalib 
4. python tools/train.py
5. See error ModuleNotFoundError: No module named 'anomalib.utils.callbacks'

**Expected behavior**
-seems the package released on pypi.org do not include all function of the git file anomalib,such as utils file.

**Comment by samet-akcay** [comment]
Hi @hqxiao, thanks for reporting this. We are aware of this. This is in fact, due to some on-going internal integration efforts. We'll be fixing this shortly. Meanwhile you could install the library via editable pip install as shown below:

```
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
```
