### ISSUE TITLE
[Task]: Dataset Robustness on `.ipynb_checkpoints` issue

### ISSUE THREAD

**Issue by Starlento** [openvinotoolkit/anomalib#1256]
### What is the motivation for this task?

I got `ValueError: NumPy boolean array indexing assignment cannot assign 18 input values to the 17 output values where the mask is true` and I found out it is because there is `.ipynb_checkpoints` in the mask dir. And if the dataset could deal with certain situation or even more complex folder structure, that would be great.

### Describe the solution you'd like

I think there were some issues related to this. I am just wondering whether there is an elegant solution to ignore every folder starts with `.`. Because I found the code for "listdir the folder" is not a single entrance, as you have multiple `make_xxx_dataset()`.
And actually for the dataset, I do not see the need to take folders into account, is there certain usage?
Could you share some insights on this?

**Comment by Starlento** [comment]
And as a solution from my site. I can delete certain folders before running the script.
`find . -type d -name .ipynb_checkpoints -exec rm -r {} \;`

**Comment by samet-akcay** [comment]
@Starlento, thanks for reporting this. In order for us to reproduce this, can you provide more specific details such as which dataset you used, what is your data configuration, model etc.

**Comment by samet-akcay** [comment]
If you could use the bug template, it would be easier for us to reproduce. Thanks!
https://github.com/openvinotoolkit/anomalib/issues/new?assignees=&labels=&projects=&template=bug_report.yaml&title=%5BBug%5D%3A+

**Comment by Starlento** [comment]
> If you could use the [bug template](https://github.com/openvinotoolkit/anomalib/issues/new?assignees=&labels=&projects=&template=bug_report.yaml&title=%5BBug%5D%3A+), it would be easier for us to reproduce. Thanks!
Sorry for the late reply. I think this is not a bug actually. And for reproducing the issue, I just follow https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html. And change it to segmentation, mask dir to `mask/colour`. Then create .ipynb_checkpoints (I browser some images before training) in `mask/colour`. Then I got the error above.
