### ISSUE TITLE
Support Kaggle and Colab Environments

### ISSUE THREAD

**Issue by innat** [openvinotoolkit/anomalib#130]
**Is your feature request related to a problem? Please describe.**
  - Kaggle and Colab are free and great resources to do quick experiments. Currently, I've found that it's not possible to run `anomalib` on these environments. I guess, when the [PIP](https://github.com/openvinotoolkit/anomalib#pypi-install) packages get ready, it would be possible.  Supporting these environments would be a great opportunity for the end-user for sure.

**Comment by alexriedel1** [comment]
Whats exactly your problem on Colab?
I've had no problem using anomalib

**Comment by innat** [comment]
I actually tried on kaggle, couldn't install it with pip. Maybe due to some torch / Cuda version issue. Have you checked on kaggle env?

**Comment by alexriedel1** [comment]
I can only guess if you're not posting the actual error. But my guess is, that Kaggle and Colab are running python 3.7 so you have to change this line in anomalib https://github.com/openvinotoolkit/anomalib/blob/aa49b7d81458832df23a3f58bfa3a38531e8bfef/setup.py#L97

**Comment by alexriedel1** [comment]
After moving to the anomalib dir, run the following, then install via pip
```
import fileinput
import sys

for line in fileinput.input("setup.py", inplace=1):
    line = line.replace(">=3.8", ">=3.7")
    sys.stdout.write(line)
```

**Comment by innat** [comment]
@alexriedel1 (cc. @samet-akcay )
I just tried your tips, but unfortunately couldn't make it run. Could you please take a look at this [FILE ](https://www.kaggle.com/ipythonx/anomaly-xyz-temporary/notebook)for reference? I surely have missed something.

**Comment by alexriedel1** [comment]
> 

you need the correct torchtext version for pytorch 1.8.1, which is 0.9.1 (`pip install torchtext==0.9.1`)
On Kaggle, you'll run into a openvino import error (as openvino is not installed). You can patch this by not importing openvino in the respective init files.

**Comment by alexriedel1** [comment]
Hello,
this notebook contains all the necessary steps to get anomalib running on Google Colab
https://colab.research.google.com/drive/1yFtIJP7OkE4-zF8S3kg9lQnqS53Nh95H?usp=sharing

**Comment by samet-akcay** [comment]
Hi all, we've recently merged #163. You could have a look and let us know if you encounter any issues.

**Comment by innat** [comment]
@samet-akcay Thanks. 
Could you please add `torchtext==0.9.1` in the set up / requirement file. It's the only issue to run anomalib in colab and kaggle.

**Comment by samet-akcay** [comment]
Done:)
