### ISSUE TITLE
FastFlow improvement

### ISSUE THREAD

**Issue by mjack3** [openvinotoolkit/anomalib#133]
**Describe the bug**
FastFlow does not need  Fm.PermuteRandom module

**Screenshots**
![image](https://user-images.githubusercontent.com/37028633/156984008-d4ee339d-ae65-45c3-bfe9-d1393c1a9116.png)

Paper applies random channel permutation. If we read what Freia.AllInOneBlock says:

![image](https://user-images.githubusercontent.com/37028633/156984552-49638ecf-490d-4c24-b834-880bb576cc56.png)

So it's suposted no needed to add the permute block. In this way I'm getting similar (or better) paper results in the classes i have tested (I'm still working in some specific data augmentation though)

**Comment by kilimi** [comment]
I also get performance boost when remove Fm.PermuteRandom. 
But still on another dataset then mvtec, performace of this fastflow implementation is much worse then padim.

**Comment by samet-akcay** [comment]
Thanks for reporting this @mjack3 and @kilimi. Please note that fastflow is still work in progress, and not ready yet. If you would like to contribute to the project, we welcome and appreciate any contributions.

**Comment by mjack3** [comment]
@samet-akcay sure, I'm working on a solution in my personal github. You can check it

**Comment by samet-akcay** [comment]
@mjack3 , great thanks! Always open to collaborate!

**Comment by Zigars** [comment]
@mjack3 Hello, I'm working on fastflow too. If you have any good reappearance, please tell me. I will great appreciate with you!

**Comment by mjack3** [comment]
Hello. I have already developed FastFlow with WResnet50 and ResNet18. We are in process to open the code. :)

**Comment by samet-akcay** [comment]
FastFlow implementation has been updated and merged [here](https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/models/fastflow).

**Comment by mjack3** [comment]
Good job. Just one advice. It would be better if you write "original code" instead of "inspired" in the readme. This two words mean different things ;)

**Comment by samet-akcay** [comment]
Sure, definitely. The original implementation has indeed been credit in multiple modules, though. Please refer to the following, for example:
https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/models/fastflow/torch_model.py#L5
https://github.com/openvinotoolkit/anomalib/blob/development/third-party-programs.txt#L26

I'll also update the description.

**Comment by samet-akcay** [comment]
`README.md` file has also been updated accordingly.
