### ISSUE TITLE
[Task]: logical anomaly detection

### ISSUE THREAD

**Issue by lemonbuilder** [openvinotoolkit/anomalib#1341]
### What is the motivation for this task?

I'm going to train 'Mvtec AD Loco' dataset using EfficientAd.
Could I have some info for that?
I wonder what part of tools/train.py I should modify for **logical anomaly detection**.
Or should I use another appropriate command?

### Describe the solution you'd like

I downloaded 'Mvtec AD Loco' dataset.

### Additional context

I read the following post.
- Add support for MVTEC LOCO AD #471
- Jpcbertoldo/mvtec ad loco #538
- Jpcbertoldo/mvtec ad loco 2 #553

**Comment by jpcbertoldo** [comment]
@lemonbuilder I lost track of tha script, but I believe there were refactors on the parent classes

https://github.com/openvinotoolkit/anomalib/blob/ed1d9fa5c7050a6edf79febd256d27b261a441ae/src/anomalib/data/base/dataset.py#L36

https://github.com/openvinotoolkit/anomalib/blob/ed1d9fa5c7050a6edf79febd256d27b261a441ae/src/anomalib/data/base/datamodule.py#L52

so it probably won't work right away

**Comment by samet-akcay** [comment]
thanks for the update @jpcbertoldo. 

@lemonbuilder, you could then follow #471 for any update since this will be a duplicate

**Comment by samet-akcay** [comment]
If you want to implement it yourself, you could use [AnomalibDataset](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/base/dataset.py) and [AnomalibDatamodules](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/base/datamodule.py) to implement
