### ISSUE TITLE
[Help][EfficientAD] How to change the input size of training processs?

### ISSUE THREAD

**Issue by TuanHAnhVN** [openvinotoolkit/anomalib#1352]
Hi all,
I want to change the input size of training process of EfficientAD. For example instead of using 256, we can edit to 256x512,320x320,.... How to do it?

Thanks!

**Comment by alexriedel1** [comment]
Just like with other models you change the image size in the config file (or via CLI) https://github.com/openvinotoolkit/anomalib/blob/9a33639d4daaf521e15ae6e38d25bc11428a5462/src/anomalib/models/efficient_ad/config.yaml#L10C1-L10C71

**Comment by samet-akcay** [comment]
@TuanHAnhVN, you could change the image size like 
https://github.com/openvinotoolkit/anomalib/blob/9a33639d4daaf521e15ae6e38d25bc11428a5462/src/anomalib/models/efficient_ad/config.yaml#L10C1-L10C71

For example, if you want `512x512` image you could do 

```yaml
dataset:
  ...
  image_size: [512, 512]
  ...
```

I have noticed that we have the following error when we try a rectangle image such as `[512, 256]`
```bash
File "./anomalib/src/anomalib/models/efficient_ad/torch_model.py", line 322, in forward
    distance_ae = torch.pow(teacher_output_aug - ae_output_aug, 2)
RuntimeError: The size of tensor a (56) must match the size of tensor b (120) at non-singleton dimension 3
Epoch 0:   0%|          | 0/215 [00:00<?, ?it/s]   
```

**Comment by TuanHAnhVN** [comment]
> For example, if you want `512x512` image you could do
> 
> ```yaml
> dataset:
>   ...
>   image_size: [512, 512]
>   ...
> ```
> 
> I have noticed that we have the following error when we try a rectangle image such as `[512, 256]`
> 
> ```shell
> File "./anomalib/src/anomalib/models/efficient_ad/torch_model.py", line 322, in forward
>     distance_ae = torch.pow(teacher_output_aug - ae_output_aug, 2)
> RuntimeError: The size of tensor a (56) must match the size of tensor b (120) at non-singleton dimension 3
> Epoch 0:   0%|          | 0/215 [00:00<?, ?it/s]   
> ```
> 
> I need to investigate the root cause though

Thank you. I want to try a rectangle image. It seems that from input size of teacher network.

**Comment by abc-125** [comment]
> I have noticed that we have the following error when we try a rectangle image such as `[512, 256]`

I think it is caused by using only the first dimension to create AutoEncoder in `torch_model.py`: 
`self.ae: AutoEncoder = AutoEncoder(out_channels=teacher_out_channels, padding=padding, img_size=input_size[0])`

This value is passed to Decoder and used to calculate the size for upsampling, so Decoder's output doesn't match other outputs.

**Comment by TuanHAnhVN** [comment]
> > I have noticed that we have the following error when we try a rectangle image such as `[512, 256]`
> 
> I think it is caused by using only the first dimension to create AutoEncoder in `torch_model.py`: `self.ae: AutoEncoder = AutoEncoder(out_channels=teacher_out_channels, padding=padding, img_size=input_size[0])`
> 
> This value is passed to Decoder and used to calculate the size for upsampling, so Decoder's output doesn't match other outputs.

Hi bro,
Did you evaluate your proposal on the mvtecAD datasets?
Could you show me the table or some information?

**Comment by abc-125** [comment]
> Did you evaluate your proposal on the mvtecAD datasets?

Hi, no, I didn't. It should not change existing results anyway.

Also, if you want to get better results on MVTec AD, I don't think that increasing resolution would achieve much because, according to the paper (see Appendix A.2), EfficientAD's teacher model was trained to extract the same features from images with resolution 256x256 as WideResNet101 from images with resolution 512x512. So, it already imitates using higher-resolution images.

**Comment by TuanHAnhVN** [comment]
> > Did you evaluate your proposal on the mvtecAD datasets?
> 
> Hi, no, I didn't. It should not change existing results anyway.
> 
> Also, if you want to get better results on MVTec AD, I don't think that increasing resolution would achieve much because, according to the paper (see Appendix A.2), EfficientAD's teacher model was trained to extract the same features from images with resolution 256x256 as WideResNet101 from images with resolution 512x512. So, it already imitates using higher-resolution images.

Thanks!
I want to train on my dataset. My input images is the rectangle images. I will try your proposal. Hope for good results
