### ISSUE TITLE
On the issue of scoring image-level and pixel-level evaluation metrics

### ISSUE THREAD

**Issue by 1094558673** [openvinotoolkit/anomalib#1377]
I really like your work! When I was evaluating the model, I found that the image-level AUROC score was lower than the pixel-level AUROC. This is different from my understanding, I thought that the pixel-level AUROC score should be lower because of the higher fine-grained, do you know why?

**Comment by samet-akcay** [comment]
@1094558673 thanks for your interest. 

Can you elaborate your use-case a bit more pleaes? Which model/dataset do you use? The difference in metrics could be use-case specific and might vary.

**Comment by 1094558673** [comment]
@samet-akcay Thank you for your reply.

I chose efficient_ad during training and its default parameter: "**python tools/train.py --model efficient_ad**".

The training results in the "**cable**" detection category are
**image_AUROC 0.9450899362564087
pixel_AUROC 0.9816182255744934**

The training results in the "**hazelnut**" detection category are
**image_AUROC 0.9385715126991272
pixel_AUROC 0.9708681106567383**

And so on, although the resulting numbers are not very different.

**Comment by blaz-r** [comment]
Hello. This can happen in some situations. While Efficient AD doesn't have per category scores, you can check [Patchcore paper](https://arxiv.org/pdf/2106.08265.pdf) where some categories have lower image AUROC than pixel AUROC (Appendix table S1 and S2).

There are some factor so this, one of which is that while pixel-AUROC is indeed more fine grained, it also doesn't take the scale of anomalies into account that well. AUPRO solves this to some degree. Additionally, scale related issue of small defects is that majority of pixels are 0 aka non-anomalous, which affects pixel metrics.

**Comment by 1094558673** [comment]
@blaz-r Thank you very much for your explanation. I will also read the related papers.
