### ISSUE TITLE
VisualizerCallback not showing properly predicted masks on fully defected images

### ISSUE THREAD

**Issue by lorenzomammana** [openvinotoolkit/anomalib#138]
**Describe the bug**
When using the visualizer callback I was constantly getting empty masks on completely defected images i.e images in which the anomaly score is greater than the given threshold for each pixel.

If this happens the imshow function called at line 64 of the visualizer.py
`self.axis[index].imshow(image, color_map)`

Will have vmin=255 and vmax=255 resulting in an empty image which is not the correct output!

The solution is straightforward, set the vmin value to 0 and vmax value to 255 (this actually requires to also multiply the gt_mask by 255 since it's in range [0-1], maybe it's better to just check if there's only one value in the array).

p.s I guess the issue arise in the same way if the gt mask is completely white.

**To Reproduce**
Use 0 as F1 threshold and the VisualizerCallback on a generic training and the issue should arise.

**Expected behavior**
The resulting predicted mask should be completely white.

**Comment by samet-akcay** [comment]
Similar to #139, we'll try to have a look at and address the issue at our earliest convenience.

**Comment by lorenzomammana** [comment]
Thank you for your work!
