### ISSUE TITLE
Threshold values are ignored when using non adaptive threshold

### ISSUE THREAD

**Issue by lorenzomammana** [openvinotoolkit/anomalib#139]
**Describe the bug**
If in the config file I disable the adaptive threshold to use my custom threshold that gives a better tradeoff compared to the adaptive one, the values that I specify are ignored and the default threshold of 0.5 if used (even if I'm not using minmax or cdf).

Looking at the code the values of my custom threshold are used only to initialize the AdaptiveThreshold object
```       
self.image_threshold = AdaptiveThreshold(self.hparams.model.threshold.image_default).cpu()
self.pixel_threshold = AdaptiveThreshold(self.hparams.model.threshold.pixel_default).cpu()
```

But then only the values from 
```       
self.image_metrics.F1.threshold
self.pixel_metrics.F1.threshold
```       

Are used, which are only updated when the adaptive_threshold flag is set to True, otherwise are just set as 0.5 as by F1 default.

**To Reproduce**
Perform a training with no anomaly score normalization, disabling adaptive threshold and setting values of your own, add debug logs to check which value of the threshold are being used, it should use 0.5 while ignoring own values.

**Expected behavior**
If no adaptive threshold is set and `model.threshold.image_default` or `model.threshold.pixel_default`, these values should be the one used to compute metrics and to reconstruct images.

**Additional context**
I'm using the updated development branch

**Comment by samet-akcay** [comment]
@djdameln, will you be able to look at this issue?
