### ISSUE TITLE
[Task]: Problen with multi GPU training

### ISSUE THREAD

**Issue by pankajmishra000** [openvinotoolkit/anomalib#1410]
### What is the motivation for this task?

    work = group.allgather([tensor_list], [tensor])
RuntimeError: No backend type associated with device type cpu

### Describe the solution you'd like

I would like to know the solution

### Additional context

Error while training patchcore on multiple GPU

**Comment by Seanny123** [comment]
See the related issue #1398 for instructions on where to remove `.cpu()` calls to enable multi-gpu training.

**Comment by samet-akcay** [comment]
Closing this as it seems to be duplicate.
