### ISSUE TITLE
Padim, inference on image with different size fails

### ISSUE THREAD

**Issue by kilimi** [openvinotoolkit/anomalib#143]
**Describe the bug**
superimposed_map = cv2.addWeighted(anomaly_map, alpha, image, (1 - alpha), gamma)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/core/src/arithm.cpp:669: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

**To Reproduce**
0. Take images where width/height is different
1. Train padim
2. tools/Inference.py with trained model

**Additional context**
- The fix is in anomalib/anomalib/deploy/inferencers/torch.py
- line: 159
- meta_data["image_shape"] - is height/width
- anomaly_map = cv2.resize(anomaly_map, meta_data["image_shape"]) --> this needs width/height
- So smth like this would do the trick: 
-  dim = (meta_data["image_shape"][1], meta_data["image_shape"][0])
        if "image_shape" in meta_data and anomaly_map.shape != dim:
            anomaly_map = cv2.resize(anomaly_map, dim)

**Comment by samet-akcay** [comment]
@kilimi, I assume you pulled the latest commit to avoid this issue, right? I'm asking for future reference.

**Comment by kilimi** [comment]
Yes, I was too slow to write the issue, it was already fixed :D Next time will double check before posting

**Comment by samet-akcay** [comment]
@ashwinvaidya17 would you be able to check this out?
