### ISSUE TITLE
[Task]: update the package to be compatible with pytorch lightning 2.1!

### ISSUE THREAD

**Issue by jamal-saeedi** [openvinotoolkit/anomalib#1459]
### What is the motivation for this task?

update the package

### Describe the solution you'd like

change anomaly module and anomaly score threshould classes

**Comment by samet-akcay** [comment]
We are currently finalising anomalib v1.0 here, which uses the latest lightning version. It is almost ready; we are working on the tests and the documentation. Once released, you will be able to use the latest lightning version

**Comment by jamal-saeedi** [comment]
I managed to make it work with the latest version of Lightning and TorchMetric. The main issues were related to the class wrapper for TorchMetric and omitting the EPOCHOUTPUT from Lightning. I fixed the latter issue by using a temporary state to keep track of the outputs.
    def on_validation_batch_end(self, val_step_outputs: STEP_OUTPUT, *args, **kwargs) -> STEP_OUTPUT:
        """Called at the end of each validation step."""
        del args, kwargs  # These variables are not used.
        self.state.append(val_step_outputs)

        self._outputs_to_cpu(val_step_outputs)
        self._post_process(val_step_outputs)
        

        return val_step_outputs

    def on_test_batch_end(self, test_step_outputs: STEP_OUTPUT, *args, **kwargs) -> STEP_OUTPUT:
        """Called at the end of each test step."""
        del args, kwargs  # These variables are not used.
        self.state.append(test_step_outputs)

        self._outputs_to_cpu(test_step_outputs)
        self._post_process(test_step_outputs)

        return test_step_outputs
