### ISSUE TITLE
The problem of running the inference code to output the image in full size

### ISSUE THREAD

**Issue by 1094558673** [openvinotoolkit/anomalib#1469]
Hello, when I ran lightning_inference.py, I saw that the output image was 256*256. If I want to output the image in full size, where do I need to change? Thank you very much.

**Comment by ArivCR7** [comment]
Hi @1094558673 , Did you make this work?

**Comment by samet-akcay** [comment]
Hi, Lightning inferencer script does not resize the output predictions to the original input size. You could add something like the following to ensure that your output matches your input size
https://github.com/openvinotoolkit/anomalib/blob/1f50c952fc65a165884b2b94e178821dcebfbbef/src/anomalib/deploy/inferencers/torch_inferencer.py#L224-L230

**Comment by ashwinvaidya17** [comment]
@1094558673 I am closing this as @samet-akcay 's answer should give you some pointers. Feel free to continue in the discussion page if you have any more questions.
