### ISSUE TITLE
Support training with custom MVTec like dataset but without masks (ground truths)

### ISSUE THREAD

**Issue by GuillaumeAnoufa** [openvinotoolkit/anomalib#147]
Hello,

I would like to be able to train on custom datasets without the need to have ground truth masks since most anomaly detection methods do not use ground truth for training. The format would be the same as any MVTec dataset just without the ground_truth directory.

Edit: I changed data/mvtec.py:253  `if label_index == 0 or not Path(mask_path).exists():
                    mask = np.zeros(shape=image.shape[:2])`
An empty mask is created if mask_path doesn't exist and it seemed to do the trick

**Comment by samet-akcay** [comment]
Thanks @GuillaumeAnoufa for the update! We're working on CustomDataset support and aim to merge it by the end of the week
