### ISSUE TITLE
Requirements incompatible with M1 Mac

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/anomalib#150]
**Describe the bug**

Currently when installing the requirements on an M1 Mac, there are certain packages (e.g. torch, numpy, scikit-learn) for which the current version cannot be found or does not work.

**To Reproduce**
1. `pip install requirements/base.txt`

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Hardware and Software Configuration**
- OS: MacOs
- NVIDIA Driver Version [470.57.02]: NA
- CUDA Version [e.g. 11.4] :NA
- CUDNN Version [e.g. v11.4.120]: NA
- OpenVINO Version [Optional e.g. v2021.4.2]

**Additional context**
- Add any other context about the problem here.

**Comment by samet-akcay** [comment]
Hi @dreaquil, can you paste the exact error you're facing so we could reproduce the problem? Thanks!

**Comment by dreaquil** [comment]
Hi @samet-akcay, there's a few different errors that one needs to work through before getting a functional install. I have started a branch which has the changes I needed to make [here](https://github.com/dreaquil/anomalib/tree/150-m1-mac).
https://github.com/openvinotoolkit/anomalib/pull/151
So far I have found issues in the versions specified of:
- torch (fixed with upgrade)
- torchvision (fixed with upgrade)
- numpy (fixed with upgrade)
- scikit-learn (fixed with upgrade)
- pandas (missing altogether?)
- openvino (not fixed)
- nncf (not fixed)

**Comment by dreaquil** [comment]
hi @samet-akcay, just a follow up on this morning's reply. I think the two main issues are nncf and openvino for the M1 mac. The problem is that their dependencies are pinned to exact versions. A lot of packages (like numpy) have only started working on the M1 mac over the past 6 months. This means that I need to upgrade numpy to make it work but this causes a dependency conflict with nncf. Any thoughts on this?

```
The conflict is caused by:
    anomalib 0.2.4 depends on numpy>=1.22.3
    albumentations 1.1.0 depends on numpy>=1.11.1
    matplotlib 3.4.3 depends on numpy>=1.16
    nncf 2.1.0 depends on numpy~=1.19.2
```

**Comment by dreaquil** [comment]
Hi @samet-akcay,

yes this is possible with the addition of commenting a particular import. I have added this temporary fix in this PR for anyone that needs it. Any idea on rough estimates for nncf and openvino? Our use case is to develop on Mac and to run on intel x86 linux so we would still like the capabilities afforded by openvino.

**Comment by samet-akcay** [comment]
Hard to tell an estimate for nncf and openvino. I guess it would be better to create in issue in [nncf](https://github.com/openvinotoolkit/nncf) and [openvino](https://github.com/openvinotoolkit/openvino) repos.
