### ISSUE TITLE
[Bug]: Windows 11 install  anomalib env error

### ISSUE THREAD

**Issue by fry404006308** [openvinotoolkit/anomalib#1502]
### Describe the bug

I followed the official instructions to set up the Anomalib environment, but I encountered the following error. Please refer to the screenshot below for more details.

[https://openvinotoolkit.github.io/anomalib/getting_started/installation/operating_systems/windows.html](https://openvinotoolkit.github.io/anomalib/getting_started/installation/operating_systems/windows.html)

### Dataset

N/A

### Model

PADiM

### Steps to reproduce the behavior

none

### OS information

OS information:
- OS: [e.g. windows 11]
- Python version: [e.g. 3.10]

### Expected behavior

none

### Screenshots

![QQ截图20231127170049](https://github.com/openvinotoolkit/anomalib/assets/33335064/3191882d-f6e1-4e3e-b59b-1ae2d79ad682)
![QQ截图20231127170105](https://github.com/openvinotoolkit/anomalib/assets/33335064/d0232d3b-77e5-4138-b784-c7210cdfb508)
![QQ截图20231127170808](https://github.com/openvinotoolkit/anomalib/assets/33335064/4e7498af-6009-441a-a074-a4f8ded9da3b)

### Pip/GitHub

pip

### What version/branch did you use?

latest

### Configuration YAML

```yaml
none
```

### Logs

```shell
(anomalib_env) D:\_230711_learnArchive\LA_ai_main_CV\_360_DAD_AnomalyDetection\_230301_EfficientAD\anomalib>pip install -r .[full]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.[full]'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fry404006308** [comment]
I have successfully solved this problem. This issue can be closed. Thank you very much.

**Comment by samet-akcay** [comment]
@fry404006308 can you post how you solved your problem so that others can refer in the future?
