### ISSUE TITLE
[Bug]: MVTec Datamodule not found

### ISSUE THREAD

**Issue by smithty48** [openvinotoolkit/anomalib#1505]
### Describe the bug

I am attempting to use the 102_mvtec.ipynb in Google Colab. When trying to run mvtec_datamodule.prepare_data() I get the following error:
![image](https://github.com/openvinotoolkit/anomalib/assets/125526686/900e52e2-310a-4fbe-bae8-d0426e01df29)

I attempted to debug via Google & Colab AI without success

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

1. Run 102_mvtec.ipynb through the 5th code chunk
2. The fifth chunk errors for me.

### OS information

N/A

### Expected behavior

I was able to run 101_btech.ipynb as expected:
![image](https://github.com/openvinotoolkit/anomalib/assets/125526686/f9ca6e1d-fb94-4059-a69b-d81d7fb2a87f)

### Pip/GitHub

pip

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smithty48** [comment]
Other note: I get a similar error in 001_getting_started.ipynb

![image](https://github.com/openvinotoolkit/anomalib/assets/125526686/033c1564-235a-4ef8-8f00-b800062fbbc2)

**Comment by blaz-r** [comment]
Hello. The link doesn't work for me as well. We'll see what we can do, thanks for reporting.

**Comment by smithty48** [comment]
> Hello. This is an issue with dataset download link. There was another report of link now working, but it is working now for me. Can you try this again and report back?

Good Morning! This works for me now. Thanks for responding!
