### ISSUE TITLE
Invalid Dataset Links about MVTec AD 3D datasets

### ISSUE THREAD

**Issue by skyqwe123** [openvinotoolkit/anomalib#1507]
Page not found
https://www.mvtec.com/company/research/datasets/mvtec-3d-ad

The official dataset cannot be downloaded. Seek a Google or Baidu cloud storage link。 Thanks

**Comment by blaz-r** [comment]
Hello, could you provide more details. The link you pasted works for me and same with the link in mvtec3d code.
