### ISSUE TITLE
Onnx padim output processing in C#

### ISSUE THREAD

**Issue by Tibe31** [openvinotoolkit/anomalib#1517]
### What is the motivation for this task?

I've trained a padim anomaly detector on my own dataset; now I want to deploy it in C#.
I've experience with Microsoft.ML.OnnxRuntime library. 
First of all, is it normal that my onnx model is around 600MB? Furthermore I would like to know how to process output from onnx model to obtain the anomaly score; is there a guide or a further documentation to process output feature map from onnx file?

### Describe the solution you'd like

I'd like to get a description of the output structure of onnx model after being executed in C# with Microsoft.ML.OnnxRuntime library. I need to know how can i process the output in order to get the final result as happen making an inference in python.

**Comment by blaz-r** [comment]
Hello. The reason that the model is so big are mean tensor and inverse of covariance matrix inside multivariate Gaussian which can become quite large in dimensions:
https://github.com/openvinotoolkit/anomalib/blob/1f50c952fc65a165884b2b94e178821dcebfbbef/src/anomalib/models/components/stats/multi_variate_gaussian.py#L20-L21
WIth input size of 256x256 they have shape of [100, 4096] and [4096, 100, 100] respectively . With 512x512 they are [100, 16384]  and [16384, 100, 100] respectively. 
Now for pre and post-processing you can refer to [OpenVInoInferencer code](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/deploy/inferencers/openvino_inferencer.py#L30). You will need to handle resizing, normalization and take care of channel order in preprocessing and then normalization and thresholding in post-processing. And for the structure of output, I it should be just a single anomaly map. Again refer to OpenVinoInferencer (and Inferencer base class) for specifics.
