### ISSUE TITLE
[Task]: CFA memory bank updating

### ISSUE THREAD

**Issue by Yzp1018** [openvinotoolkit/anomalib#1529]
### What is the motivation for this task?

hi,when I use CFA model for anomaly detection,it did achieve amazing performance.But I have some questions about code implementation.

### Describe the solution you'd like

There is a memory bank in the model.In the code,I could only find the process of initializing the memory bank before training,but I could not find the process of updating it.Could you tell me where is it?Thank you very much.

**Comment by blaz-r** [comment]
Hello. I am not that familiar with the model but I think that the memory bank is prepared at the beginning of training here:
https://github.com/openvinotoolkit/anomalib/blob/1f50c952fc65a165884b2b94e178821dcebfbbef/src/anomalib/models/cfa/torch_model.py#L142-L168
It is then just utilized in training and not modified.

**Comment by Yzp1018** [comment]
Thanks for the answer!
But in the above code to initialize the memory bank before training,there is a layer named self.descriptor,and its parameters are trainable.After traing a batchsize,the self.descriptor is changable.
So you mean,we use the original self.descriptor to make the memory bank?The memory bank is just the mean feature after the self.descriptor when the self.gamma_c is setted to 1(it is that in the config.yaml).The unchangable memory bank is used to calculate the loss and heatmap.I cannot understand that.

**Comment by blaz-r** [comment]
Looking at the diagram from the paper, I don't think the memory bank is updated:
![image](https://github.com/openvinotoolkit/anomalib/assets/61357777/dad27bbf-9cf9-48e5-b489-a96c2e1b4ef9)
but I am not that familiar with the model, @samet-akcay will probably know more.

**Comment by StarShang** [comment]
https://github.com/sungwool/CFA_for_anomaly_localization/issues/19     它只是在初始化的时候  将memorybank  初始化了一次，后面就不再更新这个memorybank了；如果你想更新它，可以在每个epoch后 再执行一次源码中的 initialize_centroid（要进行适当修改）。我试过了 这样可以让loss下降的比较顺滑，检测精度也会有所提升。
