### ISSUE TITLE
How to use data augmentation during training process (especially PatchCore)?

### ISSUE THREAD

**Issue by james77777778** [openvinotoolkit/anomalib#155]
**Is your feature request related to a problem? Please describe.**
I successfully trained PatchCore with custom dataset, but I find that the threshold is too sensitive and the model is hard to generalize. Maybe some extra data augmentation (like color jittering, rotation, etc.) will help the generalization?

https://github.com/openvinotoolkit/anomalib/discussions/119#discussioncomment-2242825

**Describe the solution you'd like**
I know anomalib uses albumentations for preprocessing, but I cannot found an easy way (without hard-coding) to configure it.

**Describe alternatives you've considered**

**Additional context**

Thanks for the great work. If there are some plans to make this possible, I can try to contribute.

**Comment by samet-akcay** [comment]
Hi @james77777778, you could use albumentations to[ serialize an augmentation pipeline](https://albumentations.ai/docs/examples/serialization/) into a yaml file. I've created a PR #156 that reads this augmentation yaml file and applies these custom augmentations to the input images. Following this, you don't need to hardcode anything.

**Comment by james77777778** [comment]
Thanks for the quick response!

But I have a question. Since PatchCore extracts features only once, how the augmentation pipeline works in this scenario?
It makes random augmentation for each image only once (if epoch=1)? It is recommended to set more epochs?

Thanks!

**Comment by samet-akcay** [comment]
There is already an ongoing discussion here in #119 you could refer to. Maybe we could continue from there?
