### ISSUE TITLE
📚 v1 - Docs Add the feature to resume training from a previous training

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#1558]
### What is the motivation for this task?

It will be great if we can resume training (for EfficientNet) since it takes time to train. Loading the pre trained weight will help get to desired accuracy quicker .

### Describe the solution you'd like

An option in the config file that can load the pre trained weight and then resume training from there.

**Comment by blaz-r** [comment]
Hello. You can achieve this by adding `resume_from_checkpoint` somewhere in your config and providing a path to weights that you want to resume from.

This is not that well documented I thing. So I'll note it down as something that should be improved in v1 docs.

**Comment by samet-akcay** [comment]
Yes, let's keep this issue open as a doc improvement.

**Comment by Shakib-IO** [comment]
Hi @samet-akcay @blaz-r 
I want to work on this.

**Comment by samet-akcay** [comment]
@Shakib-IO, sure go ahead. Thanks for your interest!

**Comment by Shakib-IO** [comment]
Hi @blaz-r 
I'm unsure where I should insert `resume_from_checkpoint` in the documentation. Any insight you could provide would be greatly appreciated. I found a relevant [source](https://github.com/ultralytics/ultralytics/blob/b53a3989ab216f04e2cd8eb5503703897eb05457/docs/en/modes/train.md?plain=1#L139) here.

Thanks!

**Comment by blaz-r** [comment]
Hi @Shakib-IO resume_from_checkpoint was part of config before the v1. With v1, this is a bit different. You can pass the checkpoint to fit directly:
https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/engine/engine.py#L462-L497
so passing `--ckpt_path CKPT_PATH`. 
As for setting this via config, I am not sure how this exactly it's handled there.

**Comment by ashwinvaidya17** [comment]
@Shakib-IO are you still working on this?

**Comment by Shakib-IO** [comment]
No. @ashwinvaidya17
