### ISSUE TITLE
[Task]: How to use a torch to run a padim model？

### ISSUE THREAD

**Issue by anzitong** [openvinotoolkit/anomalib#1559]
### What is the motivation for this task?

I've got the output of the model from torch_model import PadimModel, where should I go next to find the code to calculate the Gaussian distribution and the Mahalanobis distance and everything that evaluates the metrics, because I want to use pytorch instead of pytorch_lightning, thank you very much for your answer

### Describe the solution you'd like

    I don't want to use trainer.fit, I prefer to use the following way to do anomaly detection, what should I do, where can I find the corresponding evaluation metrics, codes to calculate Gaussian distribution and Mahalanobis distance?

model = PadimModel(input_size=[256, 256], layers=['layer1', 'layer2', 'layer3'], backbone="resnet18")
    model.to(device)
    # print(model)
    # extract train set features
    # x:32 3 256 256
    for (x, _, _) in tqdm(train_dataloader, '| feature extraction | train | %s |' % class_name):
        # model prediction
        with torch.no_grad():
            # 32 100 64 64
            outputs = model(x.to(device))
        print(outputs)

**Comment by abc-125** [comment]
Hello, usually you should be able to find the boilerplate code for training in `lightning_model.py` , for Padim it can be found [here](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/padim/lightning_model.py). You can look at `training_step` for feature extraction and at `on_validation_start` for calculating Gaussian distribution. For calculation of the anomaly map using Mahalanobis distance, check `anomaly_map.py` in the same folder. Hope this helps.
