### ISSUE TITLE
[Task]: How to use GPU to call models in C++

### ISSUE THREAD

**Issue by longge-vision** [openvinotoolkit/anomalib#1560]
### What is the motivation for this task?

How to use GPU to call models in C++

### Describe the solution you'd like

How to use GPU to call models in C++

### Additional context

How to use GPU to call models in C++

**Comment by longge-vision** [comment]
The onnx model can run on the CPU, but the GPU cannot run it

**Comment by ashwinvaidya17** [comment]
As of now we don't support any C++ inference officially so this is a bit out of scope for this repository. Hence, I am closing this issue. You can have a look at https://github.com/openvinotoolkit/model_api in case you are interested in OpenVINO inference using C++.
