### ISSUE TITLE
[Task]: efficientAD only train one category at a time

### ISSUE THREAD

**Issue by B1SH0PP** [openvinotoolkit/anomalib#1563]
### What is the motivation for this task?

I am new to unsupervised learning, and I am not familiar with this type of network usage.
I am attempting to train my own dataset using efficientAD. Currently, I am using the MVTec_AD dataset to familiarize myself with the training process.

### Describe the solution you'd like

I noticed that the training YAML file specifies a single category: `category: hazelnut`.
like this:
"
dataset:
  name: mvtec
  format: mvtec
  path: ../../datasets/MVTec_AD
  category: hazelnut
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 16
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: none # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  .....
  "

**Comment by blaz-r** [comment]
Hello. Most of the popular architectures in anomaly detection work by only training on a single object or category. 

There are many reasons behind this, but the most prominent in my opinion is that we want the models to be highly reliable. So a single model only "focuses" on a single object but does that really really well. This is especially important in cases of industrial inspection, where we'd like a really high performance.

**Comment by B1SH0PP** [comment]
I'm delighted to receive your reply. 
Your work has greatly fueled my enthusiasm for learning in this field! 
Sincere thanks.
