### ISSUE TITLE
Suggestion: WinCLIP: Zero-/Few-Shot Anomaly Classification and Segmentation

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#1564]
WinCLIP: Zero-/Few-Shot Anomaly Classification and Segmentation
https://paperswithcode.com/paper/winclip-zero-few-shot-anomaly-classification

https://github.com/caoyunkang/WinClip
https://github.com/bychelsea/vand-april-gan

https://sites.google.com/view/vand-cvpr23/challenge?authuser=0

**Comment by samet-akcay** [comment]
Hi @monkeycc, @djdameln is currently working on an implementation, which is almost complete. We might see a PR quite soon. For more details, you could keep an eye on #1569.
