### ISSUE TITLE
📚 v1 - Add custom training tutorials

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#1566]
V1 version does not have custom training tutorials

`anomalib\src\configs\data`

Data configuration file
No custom directory configuration file

**Comment by samet-akcay** [comment]
For a config file for custom data 
https://github.com/openvinotoolkit/anomalib/blob/main/src/configs/data/folder.yaml

For more detailed how-to guide
https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/data/custom_data.html
