### ISSUE TITLE
Separate train and test augmentation

### ISSUE THREAD

**Issue by alexriedel1** [openvinotoolkit/anomalib#160]
Hello,
in some settings it might be useful to use other image augmentation methods for training than for testing. E.g. in order to make a model rotational invariant, rotating during training might be useful, whereas at test time it might not be necessary.

If you find this a useful contribution for the main branch, i'll create a PR dealing with this issue.

**Comment by samet-akcay** [comment]
Hi @alexriedel1, yes, that would be really useful in certain usecases!

**Comment by samet-akcay** [comment]
should I assign this issue to you then?

**Comment by alexriedel1** [comment]
> should I assign this issue to you then?

yes, thats fine
