### ISSUE TITLE
[Task]: Revisit data typing in engine entrypoints

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#1638]
### What is the motivation for this task?

Typing of the data-related arguments in the entrypoint methods of the engine is currently confusing. e.g.:
```python
    def predict(
        self,
        model: AnomalyModule | None = None,
        dataloaders: EVAL_DATALOADERS | AnomalibDataModule | None = None,
        datamodule: AnomalibDataModule | Dataset | PredictDataset | None = None,
        return_predictions: bool | None = None,
        ckpt_path: str | None = None,
    ) -> _PREDICT_OUTPUT | None:
```
`dataloader` can be a `DataModule` instance, which conflicts with the `datamodule` argument.
`datamodule` can be a `Dataset` instance which conflicts with the `dataloader` argument.

### Describe the solution you'd like

`dataloader` can only be a (sequence of?) torch `DataLoader` object(s).
`datamodule` can only be a `AnomalibDataModule` instance.

`Dataset` instances should be wrapped in a `DataLoader` first before passing to the engine.

**Comment by ashwinvaidya17** [comment]
Addressed by: https://github.com/openvinotoolkit/anomalib/pull/1772
