### ISSUE TITLE
[Task]: Setup callbacks before instantiating trainer

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#1642]
### What is the motivation for this task?

In the engine, we first [create the trainer](https://github.com/openvinotoolkit/anomalib/blob/v1/src/anomalib/engine/engine.py#L168) before we [setup the callbacks](https://github.com/openvinotoolkit/anomalib/blob/v1/src/anomalib/engine/engine.py#L170). This has some unwanted side effects, such as skipping the checks in [`on_trainer_init`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/trainer/connectors/callback_connector.py#L47) for the updated list of callbacks. This also prevents us from adding our custom ModelCheckpoint callback to the trainer. Instead, the trainer will default to Lightning's ModelCheckpoint callback, which causes some issues downstream for zero/few-shot models.

### Describe the solution you'd like

Swap the order of instantiating the trainer and collecting the callbacks. We could first define the list of anomalib-specific callbacks, and then pass these to the `Trainer` constructor using the `callbacks` arg. Some of the callbacks depend on `trainer.default_root_dir`, but we can easily replicate the logic needed to assign that variable from the engine, and then pass it to the trainer constructor using the `default_root_dir` arg.

**Comment by ashwinvaidya17** [comment]
I am closing this as the linked PR was merged.
