### ISSUE TITLE
🔨 Rename `DynamicBufferModule` to `DynamicBufferMixin`

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#1649]
### What is the motivation for this task?

The `DynamicBufferModule` class, which is used to allow dynamically changing the shape of tensors registered as buffers, essentially behaves as a mixin and should be named as such.

### Describe the solution you'd like

Rename `DynamicBufferModule` to `DynamicBufferMixin`.

### Additional context

We could consider moving the mixins to their own submodule under `models.components`

**Comment by djdameln** [comment]
also add some unit tests

**Comment by kamlesh-ops** [comment]
Hii @djdameln 
I would like to take up this issue. 
Also, I would love to know get any advice and insights from your side before starting.
Thanks:)

**Comment by samet-akcay** [comment]
Hi @kamlesh-ops, @danylo-boiko just created PR https://github.com/openvinotoolkit/anomalib/pull/1776 to address this issue

**Comment by kamlesh-ops** [comment]
Ohh no problem. @samet-akcay 
Btw let me know if I can still contribute in any way. I'll be looking for other issues till then
cheers:)

**Comment by samet-akcay** [comment]
sure, thanks for your interest. There are bunch of `Good First Issues` there. I'll continue to label more.
