### ISSUE TITLE
Inference on remote host

### ISSUE THREAD

**Issue by patzaa** [openvinotoolkit/anomalib#166]
## Could not connect to display 

Hey guys I am trying to run the inference example remote on a ubuntu 18.04 server. 

and I am getting the following error 

```
qt.qpa.xcb: could not connect to display                                                                                  
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/dan/miniconda3/envs/anomalib-3.8/lib/python3.8/site-pa
ckages/cv2/qt/plugins" even though it was found.  

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix 
this problem.     

Available platform plugins are: xcb.                                                                                  
Aborted (core dumped)
```

Is there a way how I can save the results or port forward the display?

**Comment by LukasBommes** [comment]
I ran into the same issue when trying to run `tools/train.py` on Ubuntu 20.04 Desktop with anomalib installed in a conda virtual environment as stated in the readme.

**Comment by samet-akcay** [comment]
Hi @patzaa and @LukasBommes, sounds like this is more related to opencv and qt installation. Perhaps you could refer to the [issue](https://github.com/opencv/opencv-python/issues/447) created in opencv. [This comment](https://github.com/opencv/opencv-python/issues/447#issuecomment-779847130) seems to address it.

**Comment by LukasBommes** [comment]
Thanks for your reply! I have PyQt installed, so that could indeed be the issue. I will run anomlib in a Docker container to circumvent this issue.

**Comment by samet-akcay** [comment]
hi @patzaa and @LukasBommes, as you pointed out this is more like an issue with opencv not anomalib. I'm closing this issue for now. Feel free to reopen it if you still have issues regarding anomalib.
