### ISSUE TITLE
[Bug]: Where is the tools/train.py?

### ISSUE THREAD

**Issue by Breezewrf** [openvinotoolkit/anomalib#1675]
### Describe the bug

I search the whole project and can not find the file of tools/train.py, but some README mentioned to exec the command to train

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

exec the file and train the dataset

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Find the file

### Screenshots

![image](https://github.com/openvinotoolkit/anomalib/assets/53564343/4998ce54-2198-40c6-b0f0-31809eb3ff4f)

### Pip/GitHub

pip

### Configuration YAML

```yaml
None
```

### Logs

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blaz-r** [comment]
Hello. With introduction of v1 train script is no longer used. Check the README on how to train: https://github.com/openvinotoolkit/anomalib#-training
