### ISSUE TITLE
Unable to use Hyperparameter Optimization

### ISSUE THREAD

**Issue by MMYY-yy** [openvinotoolkit/anomalib#1683]
### Describe the bug

Optimizer failed to retrieve data from the optimizer service, for more information look at: https://comet.com/docs/v2/api-and-sdk/python-sdk/warnings-errors/

### Dataset

Other (please specify in the text field below)

### Model

PADiM

### Steps to reproduce the behavior

 python tools/hpo/sweep.py     --model padim --model_config ./src/anomalib/models/padim/config.yaml     --sweep_config tools/hpo/configs/comet.yaml

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

none

### Pip/GitHub

pip

### What version/branch did you use?

0.7.0

### Configuration YAML

```yaml
none
```

### Logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashwinvaidya17** [comment]
I am closing this as the HPO functionality is going to be overhauled for v1.1 hence this might not be relevant anymore.
