### ISSUE TITLE
🐞 Can't run the 'getting_started' notebook

### ISSUE THREAD

**Issue by Abecadarian** [openvinotoolkit/anomalib#1688]
### Describe the bug

I've just started learning how to use anomalib and tried to run the '001_getting_started' notebook. It's completely impossible.

When I try to run it in Colab, I get a bunch of errors:

```
datamodule = MVTec('sample_data')
datamodule.prepare_data()  # Downloads the dataset if it's not in the specified `root` directory
datamodule.setup()  # Create train/val/test/prediction sets.

i, data = next(enumerate(datamodule.val_dataloader()))
print(data.keys())
```

> mvtec: 5.26GB [04:23, 20.0MB/s]                            
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> [<ipython-input-6-065daa4b6dbc>](https://localhost:8080/#) in <cell line: 3>()
>       1 datamodule = MVTec('sample_data')
>       2 datamodule.prepare_data()  # Downloads the dataset if it's not in the specified `root` directory
> ----> 3 datamodule.setup()  # Create train/val/test/prediction sets.
>       4 
>       5 i, data = next(enumerate(datamodule.val_dataloader()))
> 
> 5 frames
> [/usr/local/lib/python3.10/dist-packages/anomalib/data/utils/path.py](https://localhost:8080/#) in validate_path(path, base_dir, should_exist)
>     215     if not str(path).startswith(str(base_dir)):
>     216         msg = "Access denied: Path is outside the allowed directory"
> --> 217         raise ValueError(msg)
>     218 
>     219     # In case path ``should_exist``, the path is valid, and should be
> 
> ValueError: Access denied: Path is outside the allowed directory

I tried to run it locally on my computer instead, and that ran into more errors - when I tried to install anomalib using pypi, several of the modules couldn't be found:
> ImportError: cannot import name 'ExportType' from 'anomalib.deploy'

And it couldn't load the MVTec dataset:
> TypeError: MVTec.__init__() missing 2 required positional arguments: 'root' and 'category'

When I tried to install anomalib from source, I got this error:
> ModuleNotFoundError: No module named 'openvino.tools.mo'

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

N/A

### OS information

N/A

### Expected behavior

N/A

### Pip/GitHub

pip

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@NilsB98, you are right! Due to the security scans, we had to add `validate_path` function to input paths. But the current version fails, when the input path is outside the home directory. 
https://github.com/openvinotoolkit/anomalib/blob/b5ceacfb27f40ea9025b10487017d76ead67219d/src/anomalib/data/image/mvtec.py#L131

This may not be the best approach though since the data can be on a mount. I'll see how we can ease this security check.

**Comment by Issa-Bqain** [comment]
@samet-akcay I am running the notebook on my C drive and getting the same issue - Has there been a resolution to this?
