### ISSUE TITLE
Switch to `torchvision` transforms

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1725]
### What is the motivation for this task?

Anomalib currently uses albumentations for data transforms. As torchvision v2 introduces the features we mainly use from albumentations, it might be an idea to switch to torchvisions now.

### Describe the solution you'd like

- use torchvision transforms.
- [optional] use model-specific transforms that will be applied within the model forward-pass.
- wrap the transforms within the torch model so that they could be automatically applied during inference.

**Comment by ashwinvaidya17** [comment]
Addressed by: https://github.com/openvinotoolkit/anomalib/pull/1706
