### ISSUE TITLE
Add PIMO metric to anomalib

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1728]
# Description: 

- ArXiv: https://arxiv.org/abs/2401.01984
- Medium: https://medium.com/p/c653ac30e802
- GSoC: https://gist.github.com/jpcbertoldo/12553b7eaa97cfbf3e55bfd7d1cafe88

Assignee: @jpcbertoldo

**Comment by jpcbertoldo** [comment]
oh, i forgot to create this, tnx!

**Comment by ashwinvaidya17** [comment]
Closing as PIMO is on main branch
