### ISSUE TITLE
🔨 Move export functionality to base anomaly module

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#1752]
### What is the motivation for this task?

When exporting, the anomalib engine uses several functions defined in `anomalib.deploy.export`. A cleaner solution would be to add the export functionality to the base anomaly module, similar to `LightningModule.to_onnx`.

### Describe the solution you'd like

Add the following methods to `AnomalyModule`: `AnomalyModule.to_torch`, `AnomalyModule.to_onnx` and `AnomalyModule.to_openvino`. This would simplify the export syntax from:

```python
from anomalib.models import Padim
from anomalib.deploy.export import ExportType, export_to_onnx, export_to_openvino, export_to_torch

model = Padim()
export_to_openvino(
    model=model,
    export_root="path/to/export/folder",
)
```
to:
```python
from anomalib.models import Padim

model = Padim()
model.to_openvino("path/to/export/folder")
```

**Comment by thinhngo-x** [comment]
Hi,

Do you think it would be better to retain the `anomalib.deploy.export` functions after refactoring or else to move entirely the export functions to `AnomalyModule`?

**Comment by thinhngo-x** [comment]
@samet-akcay can you assign this task for me pls? I'm working on it right now. Thanks.

**Comment by samet-akcay** [comment]
All yours :)
