### ISSUE TITLE
[Task]: Training anomalin on Android

### ISSUE THREAD

**Issue by lebichhanh** [openvinotoolkit/anomalib#1754]
### What is the motivation for this task?

I want to perform the task of training a model on Android. Is that feasible?

### Describe the solution you'd like

I don't have a solution yet and just want to confirm if this is feasible.

**Comment by alexriedel1** [comment]
I can imagine that it's not tooo much work for some of the feature aggregation methods in anomalib to be trained on android but I guess thats not possible out of the box. For models that involve backward passes I guess you would have to write some pytorch backend to do this.

**Comment by ashwinvaidya17** [comment]
You can look into inference using torch script but I agree with @alexriedel1 training on the cloud is the best option. I am not aware if PyTorch supports training on Android devices. I am closing this issue as this might not be exactly relevant to Anomalib.
