### ISSUE TITLE
✨ MLFlow support

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1759]
### Discussed in https://github.com/openvinotoolkit/anomalib/discussions/1206

<div type='discussions-op-text'>

<sup>Originally posted by **Ravio1i** July 12, 2023</sup>
### What is the motivation for this task?

We are using MlFlow. Is it planned to support sending logs to mlflow?

### Describe the solution you'd like

```yaml
  logger: mlflow
```

### Additional context

_No response_</div>

**Comment by rghvsh** [comment]
Hey @samet-akcay @blaz-r! I would like to work on this issue.

**Comment by samet-akcay** [comment]
Sure, thanks for your interest!

**Comment by CarlosNacher** [comment]
> Hi @samet-akcay! Just to make sure I've gotten this right I need to :
> 
> 1. Create a file named mlflow at src/anomalib/loggers.
> 2. That file should contain `AnomalibMLFlow` class which innherits from anomlibs'  and mlflow's logger class.
> 3. It would contain the method `add_image(self, image: np.ndarray | Figure, name: str | None = None, **kwargs: Any)`
> 4. the method will look something like
>    ```
>      if "global_step" not in kwargs:
>         msg = "global_step is required for logger"
>         raise ValueError(msg)
>    
>     # Need to call different functions of SummaryWriter for  Figure vs np.ndarray
>     if isinstance(image, Figure):
>         self.experiment.add_figure(figure=image, tag=name, close=False, **kwargs)
>     else:
>         self.experiment.add_image(img_tensor=image, tag=name, dataformats="HWC", **kwargs
>    ```

Hi @rghvsh and @samet-akcay ! If may I make a comment:

1. Yes, one `AnomalibMLFlowLogger(ImageLoggerBase, MLFlowLogger)` (`from pytorch_lightning.loggers.mlflow import MLFlowLogger`) with all you @rghvsh comment!
2. In `src/anomalib/utils/loggers/__init__.py` you should add the logic for mlflow logger following the code for wandb or tensorbord ones.
3. In `tests\pre_merge\utils\loggers\test_get_logger.py` I guess also.
4. Also, in `requirements/loggers.txt` you could add mlflow package and, if the case, the version.
5. You could update in each model `config.yaml` the comment `# options: [comet, tensorboard, wandb, csv] or combinations.` to add mlflow.

@samet-akcay @rghvsh **doubt, should anything be added/updated in:** 

1. `src/anomalib/utils/callbacks/graph.py` and `src/anomalib/utils/callbacks/visualizer/visualizer_base.py`
2. `pyproject.toml` in `[[tool.mypy.overrides]] module = ["torch.*", "wandb.*"]`
3. **benchmark related:** `tools\benchmarking\benchmark_params.yaml`, `tools\benchmarking\benchmark.py` , `tools\benchmarking\utils\__init__.py`, 
4. **hpo related:** method `upload_to_mlflow` in `tools\benchmarking\utils\metrics.py`, `src\anomalib\utils\hpo\__init__.py`, `tools\hpo\sweep.py`, `src\anomalib\utils\hpo\runners.py`

Thank you so much for your valuable work!

**Comment by rghvsh** [comment]
Hi! I'm sorry won't be able to work on the issue right now.
Sorry for the inconvenience

**Comment by samet-akcay** [comment]
No worries. Thanks for your interest anyway

**Comment by blaz-r** [comment]
@Bepitic sure, thanks for the interest.

**Comment by Bepitic** [comment]
.take

**Comment by sachinkennyr** [comment]
Is this task already assigned? If not I wish to work on it. Thanks.

**Comment by blaz-r** [comment]
Hi, thanks for the interest. Bepitic is working on it, but it's not marked as assigned. Please check out other issues.

**Comment by lathashree01** [comment]
Hi Team,
Can I pls know if there is any update on this?
Thanks

**Comment by samet-akcay** [comment]
There is PR here
https://github.com/openvinotoolkit/anomalib/pull/1847

once the tests pass, we could merge it

**Comment by ashwinvaidya17** [comment]
Closing this as MLFlow logger PR is merged
