### ISSUE TITLE
[Bug]: No module named 'lightning'

### ISSUE THREAD

**Issue by wwj723452017** [openvinotoolkit/anomalib#1782]
### Describe the bug

I‘m running the " 001_getting_started.ipynb ",and in the "import" module ,I got error like this:

File ~/PycharmProjects/anomalib1/anomalib/src/anomalib/data/base/datamodule.py:11
      8 from abc import ABC
      9 from typing import TYPE_CHECKING, Any
---> 11 from lightning.pytorch import LightningDataModule
     12 from lightning.pytorch.utilities.types import EVAL_DATALOADERS, TRAIN_DATALOADERS
     13 from torch.utils.data.dataloader import DataLoader, default_collate

ModuleNotFoundError: No module named 'lightning'

### Dataset

MVTec

### Model

N/A

### Steps to reproduce the behavior

non

### OS information

OS information:
- OS: mac m2 pro
- Python version: 3.10.13
- Anomalib version:1.0
- PyTorch version: 2.2
- run on pycharm

### Expected behavior

please tell me how can I successfully run this notebook ,thanks.

### Screenshots

non

### Pip/GitHub

pip

### What version/branch did you use?

main

### Configuration YAML

```yaml
non
```

### Logs

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 9
      6 from torchvision.transforms import ToPILImage
      8 from anomalib import TaskType
----> 9 from anomalib.data import MVTec
     10 from anomalib.data.utils import read_image
     11 from anomalib.deploy import ExportType, OpenVINOInferencer

File ~/PycharmProjects/anomalib1/anomalib/src/anomalib/data/__init__.py:16
     12 from omegaconf import DictConfig, ListConfig
     14 from anomalib.utils.config import to_tuple
---> 16 from .base import AnomalibDataModule, AnomalibDataset
     17 from .depth import DepthDataFormat, Folder3D, MVTec3D
     18 from .image import BTech, Folder, ImageDataFormat, Kolektor, MVTec, Visa

File ~/PycharmProjects/anomalib1/anomalib/src/anomalib/data/base/__init__.py:7
      1 """Base classes for custom dataset and datamodules."""
      3 # Copyright (C) 2022 Intel Corporation
      4 # SPDX-License-Identifier: Apache-2.0
----> 7 from .datamodule import AnomalibDataModule
      8 from .dataset import AnomalibDataset
      9 from .depth import AnomalibDepthDataset

File ~/PycharmProjects/anomalib1/anomalib/src/anomalib/data/base/datamodule.py:11
      8 from abc import ABC
      9 from typing import TYPE_CHECKING, Any
---> 11 from lightning.pytorch import LightningDataModule
     12 from lightning.pytorch.utilities.types import EVAL_DATALOADERS, TRAIN_DATALOADERS
     13 from torch.utils.data.dataloader import DataLoader, default_collate

ModuleNotFoundError: No module named 'lightning'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashwinvaidya17** [comment]
Just to confirm, was this your workflow?
```bash
pip install -e .
anomalib install
```

**Comment by wwj723452017** [comment]
> Just to confirm, was this your workflow?
> 
> ```shell
> pip install -e .
> anomalib install
> ```

I installed according to the document.

git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .

**Comment by BaruBenoni** [comment]
I have the same problem. I had pytorch lightning version that was not compatible, so I installed version 2 as recommended: 

lightning>2,<2.2.0 # We need to sort out the compatibility with the latest version of Lightning.

Then I had another error: no module open_clip. So I installed the latest version of open clip. Now I have an error that I can't solve: No module named 'openvino.tools.ovc' . I tried to install the openvino but no improvement. I installed it via git as well.

**Comment by Issa-Bqain** [comment]
> I have the same problem. I had pytorch lightning version that was not compatible, so I installed version 2 as recommended:
> 
> lightning>2,<2.2.0 # We need to sort out the compatibility with the latest version of Lightning.
> 
> Then I had another error: no module open_clip. So I installed the latest version of open clip. Now I have an error that I can't solve: No module named 'openvino.tools.ovc' . I tried to install the openvino but no improvement. I installed it via git as well.

This has generally been my experience so far with anomalib

**Comment by samet-akcay** [comment]
sorry to hear that you folks had some issues. On a fresh environment, if you do the following, it should work:

```bash
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
anomalib install -v
```

**Comment by samet-akcay** [comment]
By Friday, we hope to release v1 and push it to pypi so you can install it via `pip install anomalib`.

The reason why Lightning 2.2 is not supported is because Lightning introduced some breaking changes in 2.2, which we will need address.

**Comment by Issa-Bqain** [comment]
> sorry to hear that you folks had some issues. On a fresh environment, if you do the following, it should work:
> 
> ```shell
> git clone https://github.com/openvinotoolkit/anomalib.git
> cd anomalib
> pip install -e .
> anomalib install -v
> ```

I just tried this and I am still getting the same exact issue

**Comment by samet-akcay** [comment]
can you share your error log here?

**Comment by Issa-Bqain** [comment]
> can you share your error log here?

```
 File "c:\code\gr-playground\anomalib\test.py", line 9, in <module>
    from anomalib.data import MVTec
  File "C:\code\anomalib_test\anomalib\src\anomalib\data\__init__.py", line 16, in <module>
    from .base import AnomalibDataModule, AnomalibDataset
  File "C:\code\anomalib_test\anomalib\src\anomalib\data\base\__init__.py", line 7, in <module>
    from .datamodule import AnomalibDataModule
  File "C:\code\anomalib_test\anomalib\src\anomalib\data\base\datamodule.py", line 11, in <module>
    from lightning.pytorch import LightningDataModule
ModuleNotFoundError: No module named 'lightning'
```

**Comment by samet-akcay** [comment]
are you sure you ran `anomalib install -v`?

**Comment by samet-akcay** [comment]
alternatively you could run `pip install -r requirements/core.txt` to manually install the dependencies.

**Comment by Issa-Bqain** [comment]
> are you sure you ran `anomalib install -v`?

I just remade a new env and re-ran the instructions. I tried it through both instructions you mentioned above, it still was missing wand & openvino among among some other dependencies however once I manually installed these two libraries the module imports in the notebook returned no more errors:

```
from anomalib import TaskType
from anomalib.data import MVTec
from anomalib.data.utils import read_image
from anomalib.deploy import ExportType, OpenVINOInferencer
from anomalib.engine import Engine
from anomalib.models import Padim
```

Thank you for your help & diligence.

**Comment by samet-akcay** [comment]
Sure, glad that it worked. 

Yeah, `pip install -r requirements/core.txt` would only install the dependencies like torch, lightning etc.

If you want wand and openvino it would not install them you would need

```bash
pip install -r requirements/loggers.txt
pip install -r requirements/openvino.txt
```

However, if you run `anomalib install`, it should install all of these dependencies.

**Comment by Issa-Bqain** [comment]
> Sure, glad that it worked.
> 
> Yeah, `pip install -r requirements/core.txt` would only install the dependencies like torch, lightning etc.
> 
> If you want wand and openvino it would not install them you would need
> 
> ```shell
> pip install -r requirements/loggers.txt
> pip install -r requirements/openvino.txt
> ```
> 
> However, if you run `anomalib install`, it should install all of these dependencies.

I am still curious as to why the imports only worked for me with 1.0.0.dev0 and not 0.7.0 in #1790 but otherwise I will stock to 1.0.0.dev0 for now

**Comment by samet-akcay** [comment]
There are breaking changes in v1.0.0. If you have v0.7.0 installed, v1.0.0 stuff will not work. If you install anomalib via `pip install anomalib`, the notebook will not work for now. We will update the PyPI tomorrow so, this won't be an issue anymore.

**Comment by wwj723452017** [comment]
thanks for all your replies,
I’ve tried creating a new env, and commands like followed:

git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
pip install -r requirements/core.txt
pip install -r requirements/loggers.txt
pip install -r requirements/openvino.txt

and it still didn't work, the error is "No module named 'torchvision'" (although I tried "pip install torchvision")

**Comment by samet-akcay** [comment]
@wwj723452017, have you run the following first?

```bash
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
anomalib install
```

This should work

**Comment by Issa-Bqain** [comment]
> thanks for all your replies, I’ve tried creating a new env, and commands like followed:
> 
> git clone https://github.com/openvinotoolkit/anomalib.git cd anomalib pip install -e . pip install -r requirements/core.txt pip install -r requirements/loggers.txt pip install -r requirements/openvino.txt
> 
> and it still didn't work, the error is "No module named 'torchvision'" (although I tried "pip install torchvision")

This worked for me (all done in a new venv), give it a go:

```
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
pip install -r requirements/core.txt

pip install openvino
pip install wandb

```


This installed anomalib v1.0.0.dev0 where the following initial package module imports in the notebook worked:

```
from anomalib import TaskType
from anomalib.data import MVTec
from anomalib.data.utils import read_image
from anomalib.deploy import ExportType, OpenVINOInferencer
from anomalib.engine import Engine
from anomalib.models import Padim
```

**Comment by samet-akcay** [comment]
Great! However, `anomalib install -v` should install logger and openvino requirements as well. Ideally you don't need to do the final bit.

```bash
pip install -r requirements/loggers.txt
pip install -r requirements/openvino.txt
```

We'll double check this

**Comment by samet-akcay** [comment]
Is this on windows?

**Comment by samet-akcay** [comment]
It works on Linux and MacOS as well...

**Comment by wwj723452017** [comment]
> @wwj723452017, have you run the following first?
> 
> ```shell
> git clone https://github.com/openvinotoolkit/anomalib.git
> cd anomalib
> pip install -e .
> anomalib install
> ```
> 
> This should work

thanks, this work for me.
