### ISSUE TITLE
Are masks needed if we use classification models like dfm ?

### ISSUE THREAD

**Issue by MhdKAT** [openvinotoolkit/anomalib#180]
I tried to run dfm to classify my images as anomalous/non anomalous. I made my dataset in MVTec hierarchy but I get an error when i run the train script with the error being that the trainer can't access segmentation masks. Are they mandatory when the task is to classify? Below is a the error I get.   
File "C:\Users\hp\anomalib\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\hp\anomalib\anomalib\data\mvtec.py", line 256, in __getitem__
    mask = cv2.imread(mask_path, flags=0) / 255.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by samet-akcay** [comment]
@MhdKAT, it's the same issue that was found in `folder` dataset. Need to propose the same fixes to address the issue.
@LukasBommes, yes that's on our todo list, but didn't have a chance to work on it this week unfortunately.

**Comment by MhdKAT** [comment]
I see ! Thanks for the clarification @LukasBommes,  @samet-akcay.
