### ISSUE TITLE
 An error occurred when using multiple gpus 

### ISSUE THREAD

**Issue by luoyq6** [openvinotoolkit/anomalib#1809]
### Describe the bug

![image](https://github.com/openvinotoolkit/anomalib/assets/110521846/8e674b05-d713-428c-98f2-5b735afa77e9)
CUDA_VISIBLE_DEVICES=0,1 python tools/train.py --config src/anomalib/models/efficient_ad/config.yaml

### Dataset

Folder

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

efficient_ad

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

efficient_ad

### Screenshots

efficient_ad

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
efficient_ad
```

### Logs

```shell
efficient_ad
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@luoyq6, we are aware of this and would plan to address it in v1.1. For further updates please follow https://github.com/openvinotoolkit/anomalib/issues/1449. 

I'm closing this one since it is a duplicate. Thanks!
