### ISSUE TITLE
[Bug]: Inconsistency in 103_folder Notebook and Folder documentation

### ISSUE THREAD

**Issue by JoannaCCJH** [openvinotoolkit/anomalib#1811]
### Describe the bug

In the examples under the Folder documentation, the `image_size` parameter of `Folder()` is 256. However, in the examples given in the 103_folder notebook, the `image_size` parameter of `Folder()` is (256,256). 

### Dataset

Folder

### Model

PADiM

### Steps to reproduce the behavior

1. run the 103_notebook
2. reproduce the code in the documentation

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

In the examples under the Folder documentation, the `image_size` parameter of `Folder()` is (256,256).

### Screenshots

<img width="1147" alt="documentation" src="https://github.com/openvinotoolkit/anomalib/assets/96377883/4525c227-5c55-4478-a48a-37a318ede038">
<img width="1070" alt="notebook" src="https://github.com/openvinotoolkit/anomalib/assets/96377883/ccd7d684-d7cf-4ded-98cc-fdf2bc941389">

### Pip/GitHub

pip

### Configuration YAML

```yaml
no
```

### Logs

```shell
no
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@JoannaCCJH, thanks for reporting but this is to show that both is possible. Closing since this is not an issue
