### ISSUE TITLE
[Task]:How to adjust the input of one model? or how to apply this library on gray image datasets.

### ISSUE THREAD

**Issue by wwj723452017** [openvinotoolkit/anomalib#1812]
### What is the motivation for this task?

I'm trying to use my own dataset with gray image(1 channel).
when training the model Padim, I got error bellow.
Given groups=1, weight of size [64, 3, 7, 7], expected input[32, 1, 256, 256] to have 3 channels, but got 1 channels instead

### Describe the solution you'd like

I would like to know how to change the input of one model ,so that I can use gray image(1 channel).

or how to apply this library  on gray image datasets.

thanks.

**Comment by samet-akcay** [comment]
@djdameln, can you help ?

**Comment by mjack3** [comment]
You cannot use RGB because the base these anomaly detector models use pre-trained models on ImageNet (RGB)

**Comment by samet-akcay** [comment]
With the most recent anomalib commit on main, you should be able to load gray scale images to RGB

https://github.com/openvinotoolkit/anomalib/blob/a07d47e989242d358f7e8daa01c06f57c56e0e9d/src/anomalib/data/utils/image.py#L354
