### ISSUE TITLE
[Bug]: Wrong normalization used for some models.

### ISSUE THREAD

**Issue by blaz-r** [openvinotoolkit/anomalib#1813]
### Describe the bug

Some of the models have wrong normalization setup in current version of code.
This list includes: [DSR](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/image/dsr/lightning_model.py), [DRAEM](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/image/draem/lightning_model.py), [EfficientAD](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/image/efficient_ad/lightning_model.py), and [rkde](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/image/rkde/lightning_model.py).

All of the above methods shouldn't use imagenet normalization, but they have the default method setup (which uses imagenet normaliztion):
https://github.com/openvinotoolkit/anomalib/blob/9482d34049dad874fcf68edbc79454638700813a/src/anomalib/models/components/base/anomaly_module.py#L224-L241 
or in case of the EfficientAD it is manually set to imagenet:
https://github.com/openvinotoolkit/anomalib/blob/9482d34049dad874fcf68edbc79454638700813a/src/anomalib/models/image/efficient_ad/lightning_model.py#L311-L319

### Dataset

Other (please specify in the text field below)

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

/

### OS information

/

### Expected behavior

All of the above (and potentially some other models, but I think those are the only four) should have normalization set to just get all the images to [0, 1] range.

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
/
```

### Logs

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngquan** [comment]
Does using imagenet normalization affect the results much? Did you do any experiments? When I used draem, the anomaly maps rendered poorly. The anomalous regions are not rendered red. I'm still trying to figure out why.

**Comment by blaz-r** [comment]
Draem must not use imagenet normalization because the synthetic anomalies are in range 0-1, therefore images need to be normalized to 0-1 as well.
