### ISSUE TITLE
Inference on a directory of images

### ISSUE THREAD

**Issue by LukasBommes** [openvinotoolkit/anomalib#182]
It would be handy if the inference script could handle not only a single image, but an entire folder of images. Since looking at only a single example does not provide a complete picture of the algorithm's performance. 

I know, this could be achieved with a bash script. But it is easier for newcomers to have this functionality built into the inference script.

I would automatically disable graphical output (imshow) when performing inference on an entire folder (requring specifiction of the `save_path` in that case). The directory and its subdirectories could be recursively traversed and the outputs could be stored in the same directory structure at the location indicated by the `save_path`.

I could make a PR with this. What do you think?

**Comment by samet-akcay** [comment]
[](url)@LukasBommes, yeah this could be possible.

It's also possible to look at the results of the test set without running the inference script. So when you set `log_images_to: ["local"]` in `project` section of the config file, `tools/train.py` saves the results of the entire test set to `./results/<model>/<dataset>/<category>/images/...

Here is an example
![000](https://user-images.githubusercontent.com/17574420/161246525-115f9a72-98e0-49af-8148-7b500ae930bd.png)
