### ISSUE TITLE
🔨 Refactor - `make_folder3d_dataset` is too complex (16 > 15)RuffC901

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1826]
## Description

`ruff` throws the following error for the `make_folder3d_dataset` function:

```bash
`make_folder3d_dataset` is too complex (16 > 15)RuffC901
```

It would be good to simplify this function to be within the complexity limit.

**Comment by sahusiddharth** [comment]
@samet-akcay, I have made a seperate PR for this issue but it was also dealt in another PR #1825.
