### ISSUE TITLE
🔨 Remove `input_size` argument from models

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1827]
# Description
After merging PR https://github.com/openvinotoolkit/anomalib/pull/1706, models no longer require `input_size` argument. However, there are some places where `input_size` is still used, such as docs and some other utility functions. This is to ensure they are all removed properly.

For example, here is an example to the Patchcore model.

https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/patchcore/lightning_model.py#L25-L33

**Comment by Shakib-IO** [comment]
Hi @samet-akcay 
I want to work on this issue.

**Comment by samet-akcay** [comment]
Sure, thanks for your interest

**Comment by Shakib-IO** [comment]
Hi @samet-akcay,
I've begun addressing the issue at hand and have a few inquiries.

Certain utility functions contain the parameter `input_size`, as seen [here (cfa)](https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/cfa/torch_model.py#L135). Should I also eliminate these instances?

Additionally, some functions compute values dependent on `input_size`, like here [here (ganomaly)](https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/ganomaly/torch_model.py#L66C28-L66C38) Should these calculations be adjusted as well?

**Comment by dyogaharshitha** [comment]
.take

**Comment by Shakib-IO** [comment]
Hi @samet-akcay 
In ganomaly, the encoder and decoder have the `input_size`, based on the `input_size` it calculates some [values](https://github.com/openvinotoolkit/anomalib/blob/07bf60bf316e71e3e675eed4b8ca11ce69ab0c8c/src/anomalib/models/image/ganomaly/torch_model.py#L146C9-L146C20). Should these calculations be adjusted as well? Please let me know.

Thanks.

**Comment by Shakib-IO** [comment]
Hi @samet-akcay 
In ganomaly, the encoder and decoder have the `input_size`, based on the `input_size` it calculates some values. Do I need to remove them as well?

**Comment by Shakib-IO** [comment]
Hi @blaz-r 
Any comment on this?

**Comment by blaz-r** [comment]
Hi,
about the [cfa question you had[(https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/cfa/torch_model.py#L135) I think that this input_size stays as it's internal.

About ganomaly, the input_size you linked is part of torch model and that needs to stay. You should remove the input_size in lighting_model docstring:
https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/ganomaly/lightning_model.py#L26-L31
the input_size is set inside lighting_model with setup function:
https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/ganomaly/lightning_model.py#L95-L103
so the code you linked will work. But looking at this setup function, it seems like the assert string is wrong as it says csflow, so you can fix that.

**Comment by Shakib-IO** [comment]
Hi @blaz-r 
Thanks. 

Please review the PR and let me know. 
Thank you.
