### ISSUE TITLE
Make imagenette path configurable in config

### ISSUE THREAD

**Issue by holzweber** [openvinotoolkit/anomalib#1832]
https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/efficient_ad/lightning_model.py#L112

**Comment by sahusiddharth** [comment]
How would you prefer to configure the imagenette path? Would you like to use a structured format like YAML or JSON? or would you prefer a simpler approach where the path is provided directly as an argument?

**Comment by samet-akcay** [comment]
Would it be an idea to have it as an argument here, like `imagenette_path: Path | str `?

https://github.com/openvinotoolkit/anomalib/blob/34b3a90f9794dc037ec963381866d18f5f270328/src/anomalib/models/image/efficient_ad/lightning_model.py#L70-L72

**Comment by sahusiddharth** [comment]
Got it. I will also set the default path to `./datasets/imagenette`, which won't break any existing test cases.

**Comment by holzweber** [comment]
hey sorry for the late response
@samet-akcay  showed exactly the idea i had how to solve this. thanks for the quick fix! :)
