### ISSUE TITLE
[Bug]: I configured it according to the custom data set provided by the official website and kept getting errors.

### ISSUE THREAD

**Issue by zhaozzt** [openvinotoolkit/anomalib#1841]
### Describe the bug

![1](https://github.com/openvinotoolkit/anomalib/assets/127210381/003c60d2-9386-4473-a253-fb98bdda93ce)

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

123

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

![2](https://github.com/openvinotoolkit/anomalib/assets/127210381/fa055fc5-9ebd-4472-98d6-8dbc0d81ab5a)

### Pip/GitHub

pip

### Configuration YAML

```yaml
1
```

### Logs

```shell
1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blaz-r** [comment]
Hi,
I believe I had to use the variables in upper case, so CLASSIFICATION instead of the classification. I'm not sure why exactly this is the case, maybe @ashwinvaidya17 could help here.
