### ISSUE TITLE
[Bug]: ImportError: cannot import name 'auc' from 'torchmetrics.functional'

### ISSUE THREAD

**Issue by sahusiddharth** [openvinotoolkit/anomalib#1845]
### Describe the bug

- last discussed in 
- #750 
- still not addressed

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

# Import the required modules
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine

# Initialize the datamodule, model and engine
datamodule = MVTec()
model = Patchcore()
engine = Engine()

# Train the model
engine.fit(datamodule=datamodule, model=model)

### OS information

OS information:
- OS: M1 air 2020
- Python version: 3.10
- Anomalib version: 1.0.0

### Expected behavior

Should train the model

### Pip/GitHub

pip

### Configuration YAML

```yaml
na
```

### Logs

```shell
na
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashwinvaidya17** [comment]
What version of TorchMetrics are you using? There is a PR https://github.com/openvinotoolkit/anomalib/pull/1829 aimed to address this. Meanwhile try downgrading the TorchMetrics version in your python environment.
I am closing this issue and let's continue in the original issue

**Comment by Sandeep418** [comment]
It worked after downgrading by running pip install torchmetrics==0.10.3 and pip install protobuf==3.20.1.
