### ISSUE TITLE
[Task]: 使用anamolib中的patchcore模型训练自己的数据集

### ISSUE THREAD

**Issue by praycxy** [openvinotoolkit/anomalib#1846]
### What is the motivation for this task?

使用anamolib中的patchcore模型训练自己的数据集

### Describe the solution you'd like

顺利训练数据集，但总提示出现错误
![3214](https://github.com/openvinotoolkit/anomalib/assets/117440075/23697950-6cf6-4988-8078-9c2b2854580f)

**Comment by ashwinvaidya17** [comment]
@praycxy can you use the Bug template? There isn't much to go on from the three lines in the screenshot.

**Comment by tom99763** [comment]
你貼一下整個錯誤面板 看一下路徑

**Comment by praycxy** [comment]
您好，附件是整个错误部分面板，麻烦您帮忙看一下问题所在，非常感谢！


崔星雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/anomalib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月14日(星期四) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/anomalib] [Task]: 使用anamolib中的patchcore模型训练自己的数据集 (Issue #1846)





 
你貼一下整個錯誤面板 看一下路徑

**Comment by samet-akcay** [comment]
Duplicate of #1860

**Comment by yiquersanliyeye** [comment]
Hello, I have the same problem, have you solved it？
