### ISSUE TITLE
Question about inference input normalization

### ISSUE THREAD

**Issue by blueclowd** [openvinotoolkit/anomalib#1870]
Hello, i notice the latest document of [inference](https://anomalib.readthedocs.io/en/latest/markdown/guides/reference/deploy/index.html) may need a minor modification
I found that in `.predict()` there is a normalization step if the input is image path. So should we manually normalize it if the input is a numpy array?

The inference script (in current document)
```
import cv2
image = cv2.imread("path/to/image.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
result = inferencer.predict(image)
```

should it be 
```
import cv2
image = cv2.imread("path/to/image.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)/255.0
result = inferencer.predict(image)
```

the output of above script is same as using the image path directly
```
result = inferencer.predict("path/to/image.jpg")
```

**Comment by samet-akcay** [comment]
@blueclowd, you don't need to normalize the image. It is done here in the `predict` method:
https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/deploy/inferencers/openvino_inferencer.py#L185-L186

**Comment by samet-akcay** [comment]
if this documentation causes a confusion, maybe we could remove image reading part.

**Comment by blueclowd** [comment]
To sum up, there are two types of supported input format:

1. If the input is numpy array, we need to normalize it to make it between 0 and 1
2. If the input is image path, we don't need to normalize it cause it is done in the `predict` method

Its always good to support multiple types of input format, maybe just need to mention the manual normalization step if the input is numpy array?

**Comment by samet-akcay** [comment]
@blueclowd, I have now modified the logic in the PR. If you are using OpenVINO for inference, the only thing that you need to do is to pass image path, PIL or np images. No normalization is needed. It is done under the hood
