### ISSUE TITLE
[Bug]: Unable to initialize model

### ISSUE THREAD

**Issue by OneBugMaker** [openvinotoolkit/anomalib#1877]
### Describe the bug

# problem
When I tried to initialize the model in anomalib, an error occurred. This happened during the initialization phase without any further operations. Both "Padim" and "Patchcore" encountered the same issue. The detailed error message is as follows: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21240\545706316.py in <cell line: 1>()
----> 1 model = Padim()

D:\ML\0-PHD2\27_IDD\MyIDD\new_19_14_42\anomalib\src\anomalib\models\image\padim\lightning_model.py in __init__(self, backbone, layers, pre_trained, n_features)
     48         super().__init__()
     49 
---> 50         self.model: PadimModel = PadimModel(
     51             backbone=backbone,
     52             pre_trained=pre_trained,

D:\ML\0-PHD2\27_IDD\MyIDD\new_19_14_42\anomalib\src\anomalib\models\image\padim\torch_model.py in __init__(self, layers, backbone, pre_trained, n_features)
     99         self.idx: torch.Tensor
    100         self.loss = None
--> 101         self.anomaly_map_generator = AnomalyMapGenerator()
    102 
    103         self.gaussian = MultiVariateGaussian()

D:\ML\0-PHD2\27_IDD\MyIDD\new_19_14_42\anomalib\src\anomalib\models\image\padim\anomaly_map.py in __init__(self, sigma)
     24         super().__init__()
     25         kernel_size = 2 * int(4.0 * sigma + 0.5) + 1
---> 26         self.blur = GaussianBlur2d(kernel_size=(kernel_size, kernel_size), sigma=(sigma, sigma), channels=1)
     27 
     28     @staticmethod

D:\ML\0-PHD2\27_IDD\MyIDD\new_19_14_42\anomalib\src\anomalib\models\components\filters\blur.py in __init__(self, sigma, channels, kernel_size, normalize, border_type, padding)
     66             self.kernel = normalize_kernel2d(self.kernel)
     67         self.kernel.unsqueeze_(0).unsqueeze_(0)
---> 68         print(self.kernel.shape, self.channels)
     69         self.kernel = self.kernel.expand(self.channels, -1, -1, -1)
     70         self.kernel = self.kernel.expand(self.channels, -1, -1, -1)

RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

# environment
python==3.10.0
torch==2.1.0+cu121
anomalib==1.1.0dev

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

When I tried to initialize the model in anomalib, an error occurred. 

This happened during the initialization phase without any further operations.

Both "Padim" and "Patchcore" encountered the same issue.

### OS information

OS information:
- OS: [Windows 11]
- Python version: [ 3.10.0]
- Anomalib version: [1.1.0dev]
- PyTorch version: [2.1.0]
- CUDA/cuDNN version: [12.1]
- GPU models and configuration: [GeForce RTX 2060]

### Expected behavior

Resolve this bug and successfully use Padim and Patchcore models

### Screenshots

![image](https://github.com/openvinotoolkit/anomalib/assets/47165478/3ef4a5c3-64b5-402d-9d23-f37d49d12e7a)

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
i do not know
```

### Logs

```shell
i do not know
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
Can you show the full code you ran? It is a bit hard to find out the problem from `model = Padim()`

**Comment by OneBugMaker** [comment]
Thank you for your comment. 
I imported the required modules in Jupyter Notebook and attempted to initialize the model, but encountered an error, as shown in the screenshot.

![image](https://github.com/openvinotoolkit/anomalib/assets/47165478/95a0afa7-0b1b-4e20-b8c5-69cdb06ef860)

**Comment by samet-akcay** [comment]
I have tried it on both MacOS and Linux, which worked fine. Can you check if your installation is correct?

On MacOS
<img width="1201" alt="image" src="https://github.com/openvinotoolkit/anomalib/assets/17574420/8c3fa03d-19fa-42e8-bcef-73ccbb279e8b">

On Linux
<img width="1201" alt="image" src="https://github.com/openvinotoolkit/anomalib/assets/17574420/824ac015-9394-4252-81bd-4cab9932fc1d">

**Comment by OneBugMaker** [comment]
Thank you for your efforts！
The good news is that this issue has been resolved. Here are the specific steps taken to address it:

Open the file: anomalib/src/anomalib/models/components/filters/blur.py
Locate line 67: self.kernel.unsqueeze_(0).unsqueeze_(0)
Replace it with: self.kernel.unsqueeze_(0)

**Comment by luizfelippesr** [comment]
#1944
