### ISSUE TITLE
[Bug]: Validation failed: No action for key "center_crop" to check its value.

### ISSUE THREAD

**Issue by Shabayek** [openvinotoolkit/anomalib#1898]
### Describe the bug

anomalib fit -c configs/model/csflow.yaml --data configs/data/mvtec.yaml
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]]
                {install,fit,validate,test,train,predict,export} ...
error: Parser key "data":
  Problem with given class_path 'anomalib.data.MVTec':
    Validation failed: No action for key "center_crop" to check its value.

anomalib fit -c configs/model/padim.yaml --data configs/data/mvtec.yaml
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]]
                {install,fit,validate,test,train,predict,export} ...
error: Parser key "model":
  Problem with given class_path 'anomalib.models.Padim':
    Validation failed: No action for key "input_size" to check its value.

anomalib fit -c configs/model/cfa.yaml --data configs/data/mvtec.yaml
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]]
                {install,fit,validate,test,train,predict,export} ...
error: Parser key "data":
  Problem with given class_path 'anomalib.data.MVTec':
    Validation failed: No action for key "center_crop" to check its value.

anomalib fit -c configs/model/patchcore.yaml --data configs/data/mvtec.yaml
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]]
                {install,fit,validate,test,train,predict,export} ...
error: Parser key "data":
  Problem with given class_path 'anomalib.data.MVTec':
    Validation failed: No action for key "center_crop" to check its value.

### Dataset

MVTec

### Model

CSFlow

### Steps to reproduce the behavior

anomalib fit -c configs/model/padim.yaml --data configs/data/mvtec.yaml

The same error happens with all algorithms.

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Continue without errors.

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
Default in configs
```

### Logs

```shell
error: Parser key "data":
  Problem with given class_path 'anomalib.data.MVTec':
    Validation failed: No action for key "center_crop" to check its value.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@Shabayek, can you clone the latest anomalib version? `center_crop` is not part of anomalib anymore. For more details, you could refer to this PR https://github.com/openvinotoolkit/anomalib/pull/1706
