### ISSUE TITLE
📉 Investigate the low performance of EfficientAD

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#1943]
# Description
Current EfficientAD implementation does not match the numbers reported in the original paper. This task is to investigate the potential root cause of this issue.

**Comment by papago2355** [comment]
Not as for the paper result, when I use EfficientAD model export to Openvino there has been significant inference speed drops.

**Comment by abc-125** [comment]
@samet-akcay, can I please take this issue?

**Comment by samet-akcay** [comment]
@abc-125, sure. Thanks for your interest!

**Comment by alexriedel1** [comment]
@abc-125 one starting point for your work: 
Try the teacher models provided by [rximg ](https://github.com/rximg/EfficientAD) and [nelson1425](https://github.com/nelson1425/EfficientAD)

Check their teacher model training pipeline and see if they use the same image pre-processing steps as in anomalib. 
It's also worth trying to set an training pipeline for an efficientad  teacher model that resembles the anomalib training/inference pipeline

**Comment by samet-akcay** [comment]
Great pointers, thanks @alexriedel1! This was what I was trying to remember from our last discussion :)
