### ISSUE TITLE
[Bug]: setting max_epochs when engine instantiation not works

### ISSUE THREAD

**Issue by shanmugamani1023** [openvinotoolkit/anomalib#1968]
### Describe the bug

i tried to create model using custom dataset ,so ,
i used following code
# Import the datamodule
from anomalib.data import Folder
from anomalib.data.utils import TestSplitMode

# Create the datamodule
datamodule = Folder(
    name="bottle",
    root="datasets/bottle",
    normal_dir="good",
    test_split_mode=TestSplitMode.SYNTHETIC,
    task="classification",
    image_size=(512,512)
  )

# Setup the datamodule
datamodule.setup(),

after that # Import the model and engine
from anomalib.models import Patchcore
from anomalib.engine import Engine

# Create the model and engine
model = Patchcore()
engine = Engine(task="classification",
    accelerator="auto",
    check_val_every_n_epoch=1,
    max_epochs=2,
    num_sanity_val_steps=0,
    val_check_interval=1.0)
,i configured train arguments like this,
i gave max_epochs=2,
but it only run 1 time ?? how to resolve this issue ?
![1_time](https://github.com/openvinotoolkit/anomalib/assets/119931738/0ece22ac-9a5c-4852-aaea-05562e979c82)

### Dataset

Other (please specify in the text field below)

### Model

PatchCore

### Steps to reproduce the behavior

i tried to create model using custom dataset ,so ,
i used following code
# Import the datamodule
from anomalib.data import Folder
from anomalib.data.utils import TestSplitMode

# Create the datamodule
datamodule = Folder(
    name="bottle",
    root="datasets/bottle",
    normal_dir="good",
    test_split_mode=TestSplitMode.SYNTHETIC,
    task="classification",
    image_size=(512,512)
  )

# Setup the datamodule
datamodule.setup(),

after that # Import the model and engine
from anomalib.models import Patchcore
from anomalib.engine import Engine

# Create the model and engine
model = Patchcore()
engine = Engine(task="classification",
    accelerator="auto",
    check_val_every_n_epoch=1,
    max_epochs=2,
    num_sanity_val_steps=0,
    val_check_interval=1.0)
,i configured train arguments like this,
i gave max_epochs=2,
but it only run 1 time ?? how to resolve this issue ?
![1_time](https://github.com/openvinotoolkit/anomalib/assets/119931738/0ece22ac-9a5c-4852-aaea-05562e979c82)

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

need to run 2 times

### Screenshots

![1_time](https://github.com/openvinotoolkit/anomalib/assets/119931738/034e1ef7-e878-47ea-8167-48ee771cd950)

### Pip/GitHub

pip

### Configuration YAML

```yaml
null
```

### Logs

```shell
null
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@shanmugamani1023, Patchcore only needs one epoch to extract the features. Setting more epochs does not help training, which is the reason it is 1 by default and cannot be changed. 

For more details, you could refer to the paper
https://arxiv.org/abs/2106.08265

I'm closing this since this is not an issue. Thanks

**Comment by shanmugamani1023** [comment]
Thanks, so does every model have its own predefined epochs? Therefore, 
Could you please provide me with the epoch values for each model?
Which model allows me to change the epoch number?
