### ISSUE TITLE
[Bug]: change pytorch to gpu version and can't run 

### ISSUE THREAD

**Issue by wwj723452017** [openvinotoolkit/anomalib#1986]
### Describe the bug

I changed the torch version because I want to run on cuda.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

File ~/python_project/anomalib/src/anomalib/data/base/datamodule.py:15
     13 from lightning.pytorch.utilities.types import EVAL_DATALOADERS, TRAIN_DATALOADERS
     14 from torch.utils.data.dataloader import DataLoader, default_collate
---> 15 from torchvision.transforms.v2 import Resize, Transform
     17 from anomalib.data.utils import TestSplitMode, ValSplitMode, random_split, split_by_label
     18 from anomalib.data.utils.synthetic import SyntheticAnomalyDataset

ModuleNotFoundError: No module named 'torchvision.transforms.v2'

then I deleted ".v2" in the datamodule.py.
got error like this:

File ~/python_project/anomalib/src/anomalib/data/base/datamodule.py:15
     13 from lightning.pytorch.utilities.types import EVAL_DATALOADERS, TRAIN_DATALOADERS
     14 from torch.utils.data.dataloader import DataLoader, default_collate
---> 15 from torchvision.transforms import Resize, Transform
     17 from anomalib.data.utils import TestSplitMode, ValSplitMode, random_split, split_by_label
     18 from anomalib.data.utils.synthetic import SyntheticAnomalyDataset

ImportError: cannot import name 'Transform' from 'torchvision.transforms' (/home/wwj/miniconda3/envs/anomalib_env/lib/python3.10/site-packages/torchvision/transforms/__init__.py)

### OS information

OS information:
- OS: [Ubuntu 18.04]
- Python version: [e3.10.0]
- Anomalib version: [1.1.0.dev0]
- CUDA/cuDNN version: [11.3]
- GPU models and configuration: [NVIDIA GeForce RTX 3080]
-  pytorch==1.12.1 
- torchvision==0.13.1 
- torchaudio==0.12.1 
- cudatoolkit=11.3 

### Expected behavior

I just want to know how to use anomalib under GPU situation.
and by changing the torch version,I can not solve the import problem.

### Pip/GitHub

pip

### Configuration YAML

```yaml
nan
```

### Logs

```shell
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 2
      1 # Import the datamodule
----> 2 from anomalib.data import Folder
      4 # Create the datamodule
      5 datamodule = Folder(
      6     name="PVED",
      7     root=os.path.join(root_dir, "train"),
   (...)
     13     task=task,
     14 )

File ~/python_project/anomalib/src/anomalib/data/__init__.py:16
     12 from omegaconf import DictConfig, ListConfig
     14 from anomalib.utils.config import to_tuple
---> 16 from .base import AnomalibDataModule, AnomalibDataset
     17 from .depth import DepthDataFormat, Folder3D, MVTec3D
     18 from .image import BTech, Folder, ImageDataFormat, Kolektor, MVTec, Visa

File ~/python_project/anomalib/src/anomalib/data/base/__init__.py:7
      1 """Base classes for custom dataset and datamodules."""
      3 # Copyright (C) 2022 Intel Corporation
      4 # SPDX-License-Identifier: Apache-2.0
----> 7 from .datamodule import AnomalibDataModule
      8 from .dataset import AnomalibDataset
      9 from .depth import AnomalibDepthDataset

File ~/python_project/anomalib/src/anomalib/data/base/datamodule.py:15
     13 from lightning.pytorch.utilities.types import EVAL_DATALOADERS, TRAIN_DATALOADERS
     14 from torch.utils.data.dataloader import DataLoader, default_collate
---> 15 from torchvision.transforms import Resize, Transform
     17 from anomalib.data.utils import TestSplitMode, ValSplitMode, random_split, split_by_label
     18 from anomalib.data.utils.synthetic import SyntheticAnomalyDataset

ImportError: cannot import name 'Transform' from 'torchvision.transforms' (/home/wwj/miniconda3/envs/anomalib_env/lib/python3.10/site-packages/torchvision/transforms/__init__.py)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
You need to install torch and torchvision together. There is something wrong with your torchvision now

**Comment by samet-akcay** [comment]
If you want to install anomalib, you could do the following 

```bash
# Option I: From PyPI
pip install anomalib

# Option II: From source.
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
```

If you would like to install the correct torch and torchvision versions into your environment, you could do the following:
```python
anomalib install

# To get help about the installation options
anomalib install -h
```

I'm closing this issue since it does not seem to be an issue. Feel free to re-open it if you still have issues.
