### ISSUE TITLE
[Bug]: "A required privilege is not held by the client" when running installation guide sample on Windows 10; requires admin privileges

### ISSUE THREAD

**Issue by Llewi** [openvinotoolkit/anomalib#2017]
### Describe the bug

Trying to follow the tutorial on https://anomalib.readthedocs.io/en/v1.0.1/markdown/get_started/anomalib.html,

I encounter a the privilege issue as in the title when running the line `engine.fit(datamodule=datamodule, model=model)`. I can run the code fine as an admin, but I'm surprised that this is necessary. I tried running the code either via jupyter notebook, or directly via command line in the python prompt. Both lead to the same result.

I installed according to instructions, in a new pip environment with python 3.10.11 and pip 24.0. I installed anomalib using a local installation with pip install -e .; installing it from the public repository lead to the same result.

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

Install anomalib in a new virtual environment, using
`pip install -e .`
followed by
`anomalib install -v`

Run the sample code from the documentation
```
# Import the required modules
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine

# Initialize the datamodule, model and engine
datamodule = MVTec()
model = Patchcore()
engine = Engine()

# Train the model
engine.fit(datamodule=datamodule, model=model)
```

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

I'd expect to train the model without running the code as admin.

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
      - layer2
      - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
```

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\Projects\anomalib\src\anomalib\engine\engine.py", line 504, in fit
    self._setup_workspace(
  File "C:\Users\username\Projects\anomalib\src\anomalib\engine\engine.py", line 293, in _setup_wo
rkspace
    self._cache.args["default_root_dir"] = create_versioned_dir(root_dir) if versioned_dir else root
_dir / "latest"
  File "C:\Users\username\Projects\anomalib\src\anomalib\utils\path.py", line 63, in create_versio
ned_dir
    latest_link_path.symlink_to(new_version_dir, target_is_directory=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1255, in s
ymlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\username\\Pro
jects\\anomalib\\results\\Patchcore\\MVTec\\bottle\\v2' -> 'C:\\Users\\username\\Projects\\anomali
b\\results\\Patchcore\\MVTec\\bottle\\latest'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blaz-r** [comment]
I think I've encountered a similar thing. Symlinks are a bit weird on Windows, one way to solve this is to enable developer mode in your Windows settings.

**Comment by silvanobianchi** [comment]
Hi, 
I got the same problem with a recent installation of Anomalib on Windows Server 2019. 

The solution i've found is to run the conda environment as Administrator. 
While Developer mode didn't work for me.

Hope it works

**Comment by him192021** [comment]
You could comment the line 60-65 of  utils/path.py 
![螢幕擷取畫面 2024-04-25 123903](https://github.com/openvinotoolkit/anomalib/assets/99976450/e6e850ea-3441-409e-a073-31ff2de7cead)

**Comment by skaderbe** [comment]
Hi,
I got the same problem with a recent installation of Anomalib on Windows 10 Pro.

The solution i've found is to run the Spyder IDE in anomalib_env environment as Administrator.

Hope it works

**Comment by samet-akcay** [comment]
Looks like this is not an issue related to anomalib. Closing it but feel free to re-open if you have any follow-up issues.

**Comment by blueclowd** [comment]
> You could comment the line 60-65 of utils/path.py ![螢幕擷取畫面 2024-04-25 123903](https://private-user-images.githubusercontent.com/99976450/325473643-e6e850ea-3441-409e-a073-31ff2de7cead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzkxMzYsIm5iZiI6MTcxNjU3ODgzNiwicGF0aCI6Ii85OTk3NjQ1MC8zMjU0NzM2NDMtZTZlODUwZWEtMzQ0MS00MDllLWEwNzMtMzFmZjJkZTdjZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE5MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDMzNWIxMDU4MGZjODRjMjY5MmJkYTYxMGYyNzNlZjM5M2IyMGQzMGQ4M2NlZTRhZWY0NTZjNTE1YzAyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zg96uYjUXr_fHiRF33Ka49wJ93McMMfMe6dNqtox6GQ)

Works for me. The full path of the file is `${Your Python Environment}\site-packages\anomalib\utils\path.py`

**Comment by samet-akcay** [comment]
@monkeycc, yeah that's fair. I don't have a windows machine unfortunately to check this :/ I'll see what we can do

**Comment by terrarier2111** [comment]
@samet-akcay would it be possible to circumvent this on windows by copy the latest training files into the latest directory instead of latest simply beaing an symlink? On linux the symlink strategy could be retained tho (as that seems like the preferable strategy)
