### ISSUE TITLE
[Bug]: liccheck not picking license name

### ISSUE THREAD

**Issue by lathashree01** [openvinotoolkit/anomalib#2021]
### Describe the bug

when I run liccheck, the output is empty.

I see the license is Apache 2.0, but it would be great it that metadata could be picked by liccheck.

```
1 package.
    anomalib (1.0.1): ['']
      dependency:
          anomalib
```

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

run liccheck with Anomalib in requirements.txt

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Fetch - `Apache-2.0 license` as license

### Pip/GitHub

pip

### What version/branch did you use?

1.1.0

### Configuration YAML

```yaml
NA
```

### Logs

```shell
1 package.
    anomalib (1.0.1): ['']
      dependency:
          anomalib
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@lathashree01, PR #2074  should hopefully fix it

**Comment by lathashree01** [comment]
Thanks for adding this.
