### ISSUE TITLE
Question about ensemble tiler tool

### ISSUE THREAD

**Issue by junhhaha** [openvinotoolkit/anomalib#2036]
### What is the motivation for this task?

Hello, thank you for the amazing work.

The question is how can I use the ensemble tiler tool from the anomalib latest version?  

### Describe the solution you'd like

I am very interested in the ensemble tiler tool, but how can I implement the tool?

Thank you!

**Comment by samet-akcay** [comment]
Hi @junhhaha, we are currently refactoring it, and it depends on this PR https://github.com/openvinotoolkit/anomalib/pull/2005. Once we merge it, we'll integrate the ensemble tiler to the latest anomalib.

**Comment by samet-akcay** [comment]
I'm closing this issue, you could follow #1727 for further updates. Thanks!
