### ISSUE TITLE
[Task]: patchcore whether fp16 is supported

### ISSUE THREAD

**Issue by luoyq6** [openvinotoolkit/anomalib#2066]
### What is the motivation for this task?

RuntimeError: expected scalar type Half but found Float

### Describe the solution you'd like

RuntimeError: expected scalar type Half but found Float

### Additional context

patchcore

**Comment by samet-akcay** [comment]
@luoyq6 can you add a bit more context please?

**Comment by ashwinvaidya17** [comment]
Closing this as it is stale. @luoyq6 feel free to re-open with additional context to help address this issue.
