### ISSUE TITLE
[Task]: GPU is False

### ISSUE THREAD

**Issue by microchila** [openvinotoolkit/anomalib#2068]
### What is the motivation for this task?

Why is my Pytorch's CUDA false after installing, how can I install it to use the GPU version

### Describe the solution you'd like

I'm trying to get him to train on the GPU, but after installing it says GPU unavailable!

**Comment by samet-akcay** [comment]
How do you install anomalib?

**Comment by microchila** [comment]
1.git
2.cd
3.pip install -e .
4.anomalib install 
@samet-akcay

**Comment by samet-akcay** [comment]
Are you on windows or linux? Also what is the output of `nvcc --version`?

**Comment by abc-125** [comment]
> 'https://download.pytorch.org/whl/cpu', 'torch>=2+cpu'

I think you need to install PyTorch with GPU. You can look [here](https://pytorch.org/get-started/previous-versions/) to find one that matches your CUDA version. To find which CUDA version you have, use `nvcc --version`.

**Comment by samet-akcay** [comment]
`anomalib install` looks whether cuda and cudnn are installed, and decides which torch version to install. My suspicion is that cuda or cudnn may not properly be installed on the system so anomalib cannot find the gpu information

**Comment by microchila** [comment]
My cuda was installed on the pytorch official site using the command line, not a separate installation, and I think that's why it doesn't recognise my cuda. I've uninstalled the cpu version of torch and replaced it with the GPU version and it works now.
