### ISSUE TITLE
[Bug]: Issue occurs in setuptools version 70 +

### ISSUE THREAD

**Issue by harimkang** [openvinotoolkit/anomalib#2126]
### Describe the bug

https://github.com/openvinotoolkit/anomalib/blob/41d8cf90cfb8de954fd3ed0ec9c2c7bff75b81d3/src/anomalib/models/video/ai_vad/clip/clip.py#L21
An error occurs in environment where `setuptools` is version 70 or higher. This is related to this issue. https://github.com/pypa/setuptools/issues/4376

This can cause issues with newer builds.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

Install anomalib==1.1.0 with setuptools==70.0.0
```
pip install setuptools==70.0.0
pip install 'anomalib[core]==1.1.0'
anomalib train ***
```

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Install without error

### Screenshots

```shell
Problem with given class_path 'otx.algo.anomaly.padim.Padim':        
cannot import name 'packaging' from 'pkg_resources' (/mnt/hdd1/miniforge3/envs/py310-otx/lib/python3.10/site-packages/pkg_resources/__init__.py)
```

### Pip/GitHub

pip

### What version/branch did you use?

1.1.0

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
Problem with given class_path 'otx.algo.anomaly.padim.Padim':        
cannot import name 'packaging' from 'pkg_resources' (/mnt/hdd1/miniforge3/envs/py310-otx/lib/python3.10/site-packages/pkg_resources/__init__.py)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashwinvaidya17** [comment]
https://github.com/openvinotoolkit/anomalib/pull/2082 should solve this issue when it is merged.
