### ISSUE TITLE
No module named 'anomalib.config'

### ISSUE THREAD

**Issue by A0401A** [openvinotoolkit/anomalib#2132]
### Describe the bug

(pytorch) F:\anomalib-0.7.0>python tools/train.py --model padim
Traceback (most recent call last):
  File "F:\anomalib-0.7.0\tools\train.py", line 17, in <module>
    from anomalib.config import get_configurable_parameters
ModuleNotFoundError: No module named 'anomalib.config'

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

。

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

。

### Screenshots

。

### Pip/GitHub

pip

### Configuration YAML

```yaml
。
```

### Logs

```shell
。
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexriedel1** [comment]
`F:\anomalib-0.7.0` looks like you are using version 0.7.0 which is outdated. Please install the latest version via https://github.com/openvinotoolkit/anomalib?tab=readme-ov-file#-installation

**Comment by monkeycc** [comment]
```
from anomalib.config import Config
config = Config(path="config.yaml")
engine = Engine(config=config)  
```

```
    from anomalib.config import Config
ModuleNotFoundError: No module named 'anomalib.config'
```

anomalib-2.0.0
@alexriedel1
