### ISSUE TITLE
[Task]: The documentation for the config file is missing.

### ISSUE THREAD

**Issue by JinYuannn** [openvinotoolkit/anomalib#2208]
### What is the motivation for this task?

documentation is missing

### Describe the solution you'd like

Where can I find the complete config file? The` anomalib/configs` directory only contains the data and model configs. I haven't found config information that includes other parameters such as training hyperparameters, evaluation metrics, data augmentation configurations, etc., in the documentation or the project.

**Comment by abc-125** [comment]
Hello, training hyperparameters can be found in model configs (ones you can change). Data augmentation is not usually used in anomaly detection, but you can find how to use it in configs [here](https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/data/transforms.html). Documentation on how to use evaluation metrics in config is seemingly missing.

**Comment by ashwinvaidya17** [comment]
@JinYuannn on top of what @abc-125 mentioned, anomalib's CLI is based on `JSONArgparse`. It follows a similar pattern to the [Lightning CLI](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced.html). The config files in `anomalib/configs/model` serve as an example and contain only the parameters that are needed to run that model. The trainer takes the default parameters unless specified in the config. If you want to print the entire config you can use the `--print_config`` option. For example, `anomalib train --model Padim --data MVTec --print_config`.
I am closing this issue. Feel free to re-open if you are still uncertain.

**Comment by JinYuannn** [comment]
Thanks for your reply.
