### ISSUE TITLE
[Task]: Training using anomalib train

### ISSUE THREAD

**Issue by mohandeeprdori** [openvinotoolkit/anomalib#2223]
### What is the motivation for this task?

![image](https://github.com/user-attachments/assets/753e17fc-5478-4ed5-8fc1-e32eaefcc47a)
Install anomalib using 'anomalib install'
tried to start a training using **anomalib train --model EffiecientAd --data anomalib.data.MVTec --data.category bottle**
Still getting the same error saying **error: argument subcommand: invalid choice: 'train'**

### Describe the solution you'd like

How to run the training for the above configuration

**Comment by hrudaykolla** [comment]
I have tried API based, 
after pip install anomalib
# Install with verbose output, do this
anomalib install -v

And try to train again

**Comment by harimkang** [comment]
We've broken install into two steps to support use cases like installing edge devices, but we also provide a way to install the whole thing in one step.

`pip install anomalib[full]`
This command will install all the prerequisites for full training and exporting, and is the same as the result of `anomalib install -v`.

**Comment by mohandeeprdori** [comment]
@harimkang I have a doubt.
I did training over few custom datasets and now I want to run inference for a single image outside anomalib. Where in I wrote a custom script to load the model and the checkpoint. But the results seem to vary as of what anomalib gives and the other method gives. Any idea how do I replicate the same results outside anomalib? or if there is any way i can use anomalib to test on a single image instead of using images through data loaders. 
perhaps you could also answer. @ashwinvaidya17 ' :)
