### ISSUE TITLE
Is the imagenet data set necessary for efficientAd training?

### ISSUE THREAD

**Issue by gaooolianggg** [openvinotoolkit/anomalib#2245]
When I train efficient ad, I got an error that I don't have the imagenet dataset. ,I does not have one in fact, because it is very large, if I can use pretrained weights instead of retraining?
thanks very much!

**Comment by samet-akcay** [comment]
Are you sure if it is imagenet or imagenette? Can you share your error log ?

**Comment by abc-125** [comment]
Hello, it should be imagenette dataset, which is about 1.5GB. It is an important part of training EfficientAD which helps model not to overfit on training data.

**Comment by gaooolianggg** [comment]
thanks a lot, 

> Hello, it should be imagenette dataset, which is about 1.5GB. It is an important part of training EfficientAD which helps model not to overfit on training data.

thanks a lot! I got a mistake
