### ISSUE TITLE
Does patchcore's model size proportional to the number of training images?

### ISSUE THREAD

**Issue by luweishuang** [openvinotoolkit/anomalib#228]
I notice in patchcore model,  memory_bank size == [coreset_size, 1536], and  coreset_size is proportional to the number of training images, So its model size is proportional to the number of training images too? Is this normal?

**Comment by watertianyi** [comment]
@luweishuang 

What is stored in the patchcore model is the feature vector of each training sample, so the size of the model is related to the number of image training samples, and the inference speed should also be related to this?
