### ISSUE TITLE
CUDA support unavailable

### ISSUE THREAD

**Issue by Muhammad-Kazim** [openvinotoolkit/anomalib#231]
There seems to be no CUDA support.

Running Patchcore on a custom dataset. Works fine with cpu but takes forever to train. gpus set to 1 and auto_select_gpus set to True in config file.

My machine has NVIDIA GeForce RTX 3060. However, with the env activated, torch.cuda.is_available() is False.

Made the installations as follows:

conda create -n anomalib_env python=3.8
conda activate anomalib_env
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .

![image](https://user-images.githubusercontent.com/42314227/163379966-c75f252d-1a0f-4c81-a502-f40c48f2d49e.png)

**Comment by samet-akcay** [comment]
@Muhammad-Kazim, I think this could be related to RTX30*0 series. See [this](https://discuss.pytorch.org/t/nvidia-geforce-rtx-3090-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/141940), for instance. If you manually install torch with right cuda, it should be able to work

**Comment by samet-akcay** [comment]
We will double check this though. Looks like this issue is similar to #232

**Comment by samet-akcay** [comment]
Closing this as the discussion continues in #232
