### ISSUE TITLE
[Bug]: Update setuptools requirement for PEP 660 support

### ISSUE THREAD

**Issue by sunstudio** [openvinotoolkit/anomalib#2314]
### Describe the bug

I install anomalib from source. Get the following error:

ERROR: Project file:///home/sun/programs/anomalib has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

git clone
cd anomalib
pip install -e .

### OS information

- OS: [e.g. Ubuntu 22.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 1.1.1]

### Expected behavior

install anomalib

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
none
```

### Logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
Thanks for reporting this, @sunstudio. I've created #2320 to address this
