### ISSUE TITLE
[Bug]: MinMax fails when box predictions are empty

### ISSUE THREAD

**Issue by blaz-r** [openvinotoolkit/anomalib#2350]
### Describe the bug

MinMax class throws an exception in case where no boxes are predicted and update is called.

In case of no boxes present, the predictions for boxes look like this:
```python
[torch.Tensor([]), torch.Tensor([]), torch.Tensor([])]
```
i.e. a list of empty tensors. 

When update is called inside the callback, these are stacked before the update on MinMax is called:
https://github.com/openvinotoolkit/anomalib/blob/2ba5ede95daa2abfdb2026ec08f29f4e8a818f67/src/anomalib/callbacks/normalization/min_max_normalization.py#L83-L84

which then throws the following esception:

```error
    self.max = torch.max(self.max, torch.max(predictions))
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

### Dataset

Other (please specify in the text field below)

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

```python
    from anomalib.metrics import MinMax
    import torch

    box_preds = [torch.Tensor([]), torch.Tensor([]), torch.Tensor([])]

    minmax = MinMax().cpu()

    # cat and call update (same as the MinMax callback does).
    minmax.update(torch.cat(box_preds))
```

### OS information

OS information:
- OS: Win11
- Python version: 3.10
- Anomalib version: 1.2 dev
- PyTorch version: 2.3.0
- CUDA/cuDNN version: x
- GPU models and configuration: x
- Any other relevant information: x

### Expected behavior

No exception.

Probably fixable by simply adding an if statment here:

https://github.com/openvinotoolkit/anomalib/blob/2ba5ede95daa2abfdb2026ec08f29f4e8a818f67/src/anomalib/metrics/min_max.py#L46-L51

i.e.
```python
if predictions.numel():
....
```

### Pip/GitHub

GitHub

### What version/branch did you use?

latest

### Configuration YAML

```yaml
/
```

### Logs

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@blaz-r, we would like to remove the box support in future releases. How would this be impacted?

**Comment by blaz-r** [comment]
Then this won't be a problem anymore :)

**Comment by samet-akcay** [comment]
box prediction causes so much trouble and maintenance overhead. We don't even know if there is anyone using it
If we remove it we are going to have a better life :D

**Comment by blaz-r** [comment]
Okay, sounds good 👍
