### ISSUE TITLE
Issue in Patch-Core

### ISSUE THREAD

**Issue by innat** [openvinotoolkit/anomalib#236]
## Background

I have tried to run `anomalib` on the kaggle environment (also preparing a tutorial to contribute here for newcomers to get started with `anomalib` 😉).  However, with the `patch-core` model, I'm facing an issue.

## Describe the Behaviour 

When I run the script with patch-core, it kinda stuck in the following stage. And I've noticed that the coreset is processing on CPU (usages were high). So, it might be stuck or take lots of time to process on the CPU, which should not be. 

```yaml
Epoch 0:   8%|█▉           | 7/90 [01:20<15:58, 11.54s/it, loss=nan]
Validation: 0it [00:00, ?it/s]A
Creating CoreSet Sampler via k-Center Greedy
Getting the coreset from the main embedding.
```

## Reproducible Code 

- [Kaggle Notebook](https://www.kaggle.com/code/ipythonx/anomaly-in-anomalib/notebook). (make sure to enable GPU quote)

## Other info.

Not sure if it's the current know issue with patchcore. I've run the code successfully with the `padim` model (didn't test the rest of the models). 

I'm considering myself a **beginner** in `pytorch/pytorch-lighting`, maybe I'm missing something obvious. Also, there are lots of `pytorch-lighting`  related `UserWarning` messages. IMHO, it's annoying, can it be removed, like `verbose = 0`?

**Comment by innat** [comment]
Okay, here is a possible solution, will try.  https://github.com/openvinotoolkit/anomalib/issues/232#issuecomment-1099580054

**Comment by samet-akcay** [comment]
> I have tried to run anomalib on the kaggle environment (also preparing a tutorial to contribute here for newcomers to get started with anomalib 😉)

Thanks @innat, that'd be lovely!

> When I run the script with patch-core, it kinda stuck in the following stage. And I've noticed that the coreset is processing on CPU (usages were high). So, it might be stuck or take lots of time to process on the CPU, which should not be.

Do you want to explicitly use CPU? If yes, then it is indeed an issue that sampling takes lots of time. We want to optimize the code for CPU computation. If you want to use GPU, then, yes #232 is the solution.

> I'm considering myself a beginner in pytorch/pytorch-lighting, maybe I'm missing something obvious. Also, there are lots of pytorch-lighting related UserWarning messages. IMHO, it's annoying, can it be removed, like verbose = 0?

We'll be working on the issue #54, which would potentially address this. For the time being you could manually configure the [console logging](https://pytorch-lightning.readthedocs.io/en/latest/extensions/logging.html?highlight=console%20logging#configure-console-logging).

**Comment by innat** [comment]
> Do you want to explicitly use CPU?

@samet-akcay No, I don't want that for now. It takes a lot of time.

> If you want to use GPU, then, yes https://github.com/openvinotoolkit/anomalib/issues/232 is the solution.

That PR is not still merged. I will try to run code from `fix/sa/configs` branch.

**Comment by innat** [comment]
@samet-akcay running from `fix/sa/configs` branch fix the issue. Thanks. 😄

```yaml
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │            1.0            │
│         image_F1          │            1.0            │
│        pixel_AUROC        │     0.984413743019104     │
│         pixel_F1          │    0.7208729982376099     │
└───────────────────────────┴───────────────────────────┘
```

**Comment by daMichaelB** [comment]
Meanwhile the code from `fix/sa/configs` is merged. I have a slightly different setup and still does not work.

First I trained PatchCore on a single-GPU machine. There i always ran into Cuda-OutOfMemory as my dataset was to big for the patch-core training step. So i switched to a 8-GPU instance. I changed:

```yaml
trainer:
  accelerator: dp # parallel training
  gpus: 8 # Set automatically
```

if i use the settings from `fix/sa/configs` it only uses one gpu and goes into OOO in training step.

### Training Step 🆗 
Now the `training_step` works very well with all the data. I also found that the GPU-Mem is not used anymore at all (maybe because of `dp` setting. 

### Validation Step
The validation Step however does not use any of the GPUs and it takes forever.

I get the log `Applying core-set subsampling to get the embedding.` and then it computes forever on CPU.

Is there any idea how to get this working @samet-akcay ? Thank you very much in advance!
