### ISSUE TITLE
[Bug]: importing `anomalib.models` package is issueing a polluting warning about missing openvino

### ISSUE THREAD

**Issue by Yann-CV** [openvinotoolkit/anomalib#2384]
### Describe the bug

Simply `import anomalib.models` will display the following warning: `OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer.`

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

`import anomalib.models` 

### OS information

OS information:
- OS: Ubuntu 22.04
- Python version: 3.10.14
- Anomalib version: 1.1.1

### Expected behavior

the warning is issued only when the OpenVINOInferencer is of use

### Pip/GitHub

pip

### Configuration YAML

```yaml
not related
```

### Logs

```shell
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@Yann-CV, thanks for reporting, #2385 should fix it.

**Comment by Yann-CV** [comment]
thanks @samet-akcay
