### ISSUE TITLE
[Bug]: Notebook Examples Fail

### ISSUE THREAD

**Issue by vmiller987** [openvinotoolkit/anomalib#2394]
### Describe the bug

I am unable to get any of the notebook examples to work.
https://github.com/openvinotoolkit/anomalib/tree/v1.1.1/notebooks

I've tried starting with 001_getting_started.ipynb.
If I run it in colab, there's a lot more missing dependencies that I must work with installing. Missing module Lightning, FrEIA, dotenv, etc.

If I run this in my own env, I'm able to get the fit() to run, but it only does one epoch even if I set max_epochs=100. Depending on the notebook I'm running, but I end up with warnings about optimizer returns None. 

Do these notebooks still work? In a fresh venv?
I am new to unsupervised learning and I am trying to get into it. Your library looks excellent but I am struggling to get it to work.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

python -m venv .anomalib_env
source .anomalib/bin/activate

pip install anomalib
anomalib install

https://github.com/openvinotoolkit/anomalib/blob/main/notebooks/000_getting_started/001_getting_started.ipynb

### OS information

OS information:
- OS: RHEL 8.10
- Python version: 3.11.9
- Anomalib version: 1.1.1
- PyTorch version: 2.5.0
- CUDA/cuDNN version: 12.1
- GPU models and configuration: 8x RTX 4090
- Any other relevant information: 

### Expected behavior

I expect the notebook tutorials to run with minimal adjustments. 

### Screenshots
This is the closest I get to running it, but I cannot seem to get the epochs to update. I am currently trying to figure out how to deal with the optimizers return None.

![image](https://github.com/user-attachments/assets/06e5f79b-bb7d-4e74-b851-198acb5c46a1)

### Pip/GitHub

pip

### Configuration YAML

```yaml
I don't have a config yaml because I'm just trying the tutorial notebooks.
```

### Logs

```shell
I don't have any logs as I'm just trying to run the notebooks.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@vmiller987, looks like it is working. The reason why you are seeing `None` is `Padim` model does not have an optimiser. And the reason why you are not seeing any output is, you are just fitting the model with `engine.fit` If you call `engine.test(..)` it would give you some output

**Comment by vmiller987** [comment]
I appreciate the fast reply and the info. If it's working for you, then it's a skill issue on my part. I didn't realize `Padim` did not have an optimizer as I haven't had enough time to dig through all these libraries that are new to me. 

Does Anomalib only need to run for 1 epoch? I tried to set `max_epochs=100`, but it still ends at 1 epoch. The Engine stated it uses Trainer parameters so I thought I could adjust it with that.

**Comment by samet-akcay** [comment]
Padim only needs 1 epoch. You could try other models if you would like to train for longer. `EfficientAd` for example

**Comment by vmiller987** [comment]
Oh, well that would explain my issue then. I made an incorrect assumption. 
I shall continue to work through the notebooks, and I'll make sure I dig into the different models available to understand them better. My work is wanting me to pursue some unsupervised learning for defect detection in x-ray images of objects, and I have a few thousand unlabeled images. 

I am a novice and doing my best to learn. I greatly appreciate your fast replies and pointing out my issues.
Thanks!
