### ISSUE TITLE
`log_graph = True` for tensorboard logger doesn't show model graph.

### ISSUE THREAD

**Issue by innat** [openvinotoolkit/anomalib#240]
**Describe the bug**
I wanted to show the computational graph of the `patchcore` model and for that I enable `project.logger: tensorboard` and set `log_graph = True` 

```python
logger = AnomalibTensorBoardLogger(
            name="Tensorboard Logs",
            save_dir=os.path.join(config.project.path, "logs"),
            log_graph=True
        )
```

Now, when I finished training, I run the tensorboard and under the `GRAPHS` tag, it showed nothing. 

![image](https://user-images.githubusercontent.com/17668390/164081646-1f8d32d4-13d4-4636-a2e0-57ab9fd91eb2.png)

**To Reproduce**
1. Go to the `patchcore` config file and set `logger: tensorboard'
2. Next, `working/anomaly_detection_engine/anomalib/anomalib/utils/loggers/__init__.py` and set `log_graph=True` 
3. Run the anomalib with patchcore config
4. After training, run the event log in tensorboard.

**Expected behavior**
- It should give a computational graph, like https://github.com/PyTorchLightning/pytorch-lightning/issues/2915

**Screenshots**
- (Mention above)

**Hardware and Software Configuration**
- OS: [Ubuntu, OD] Ubuntu
- PyTorch-Lighting: '1.5.9'
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.4] 10.2
- CUDNN Version [e.g. v11.4.120] 7605
- OpenVINO Version [Optional e.g. v2021.4.2]

**Additional context**
- I also found that the [`add_image`](https://github.com/openvinotoolkit/anomalib/blob/4910e186925637ae3724c7c23f200494521552cc/anomalib/utils/loggers/tensorboard.py#L84) function of the tensorboard callback, doesn't write any image on the tensorboard either.
- Is there any way, I can write the **Histogram** in tensorboard in pytorch-lighting. Histograms are made for weights and bias matrices in the network. They tell us about the distribution of weights and biases among themselves. Is there any convenient way to add it to anomalib' models?

**Comment by innat** [comment]
@samet-akcay could you please take a look at this issue? 
I tried this [fix](https://github.com/openvinotoolkit/anomalib/pull/233) but ended up with this [issue](https://github.com/openvinotoolkit/anomalib/issues/237).

**Comment by innat** [comment]
FYI, also added `self.example_input_array` to `PatchcoreModel` inside the `patchcore/torch_model.py`. 

Any pointer?

**Comment by ashwinvaidya17** [comment]
@innat The part about logging images is not documented well. To log images to tensorboard, you need to set `log_images_to: ["tensorboard"]` and `logger: tensorboard`, in the config file of the model. 
For the second point, unless I am missing something you should ideally be able add anything to the tensorboard logger using the `logger` object.

**Comment by innat** [comment]
@ashwinvaidya17 thanks for the info. I've missed the `log_images_to` param in the config file, thought setting to `logger:tensorboard` is enough. I will try and report. 

Regarding the model graph, can you please point out what's wrong with the above approach?

**Comment by innat** [comment]
@ashwinvaidya17 I tested with `log_images_to`, and it worked. It showed the model prediction. I think it's better to at least comment on the possible option. Like

```
log_image_to = ['local'] # ['local'], ['tensorboard']. ['wandb'] 
```

And I think it would be nice if we can show models layers activation maps. For example: in patch core, the backbone is wide-resnet with layers 2 and 3. How about showcasing their activation maps.

**Comment by samet-akcay** [comment]
> @ashwinvaidya17 I tested with log_images_to, and it worked. It showed the model prediction. I think it's better to at least comment on the possible option. 

@innat, it will be addressed with #227 .

> And I think it would be nice if we can show models layers activation maps. For example: in patch core, the backbone is wide-resnet with layers 2 and 3. How about showcasing their activation maps.

We could discuss this. Perhaps this could be optional, so the user would be able to access when needed.

**Comment by innat** [comment]
@ashwinvaidya17 
> For the second point, unless I am missing something you should ideally be able to add anything to the tensorboard logger using the logger object.

Sorry, I've limited experience in pytorch. In keras, we can use [keras.callbacks.TensorBoard](https://keras.io/api/callbacks/tensorboard/) this convenient callback handles most of the cases, like plot graphs, histograms, images, etc. Could u please share any references where I can find examples regarding tensorboard logging in pytorch-lighting? I found [this](https://learnopencv.com/tensorboard-with-pytorch-lightning/), but a bit confusing to me.

**Comment by innat** [comment]
@ashwinvaidya17 Thanks a lot, it's really helpful. I'm currently out of my workplace, will check soon.
