### ISSUE TITLE
[Bug]: AttributeError: 'numpy.ndarray' object has no attribute 'to'

### ISSUE THREAD

**Issue by Septembit** [openvinotoolkit/anomalib#2452]
### Describe the bug

Seems this bug  still exists when I use torch inferencer in anomalib 1.2.0
Do anyone have a way to solve it?
thanks

### Dataset

Folder

### Model

FastFlow

### Steps to reproduce the behavior

N/A

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

N/A

### Pip/GitHub

pip

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
def pre_process(self, image: np.ndarray) -> torch.Tensor:
        """Pre process the input image.

        Args:
            image (np.ndarray): Input image

        Returns:
            Tensor: pre-processed image.
        """
        if len(image) == 3:
            image = image.unsqueeze(0)

        return image.to(self.device)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-NK** [comment]
can I take this issue and work on fixing it?

**Comment by Septembit** [comment]
Yes, thank you very much
