### ISSUE TITLE
Refactor to use new F1Score over F1

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/anomalib#267]
**Describe the bug**
Torchmetrics has deprecated the use of F1. They now specify to import F1Score. This is a breaking change with the current requirements has broken Anomalib.

**To Reproduce**
- Install fresh anomalib
- Run any anomalymodule

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Hardware and Software Configuration**
- OS: [Ubuntu, OD]
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.4]
- CUDNN Version [e.g. v11.4.120]
- OpenVINO Version [Optional e.g. v2021.4.2]

**Additional context**
- Add any other context about the problem here.

**Comment by dreaquil** [comment]
This seems to have already been fixed in development.

**Comment by dreaquil** [comment]
@samet-akcay In relation to the above, would it make sense to separate and fix requirements in setup.py? At the moment 0.2.6 is not usable.

**Comment by samet-akcay** [comment]
@dreaquil, there will be a new release, v0.3.0, before 24th of April.
