### ISSUE TITLE
enforce fail at CPUAllocator.cpp:71

### ISSUE THREAD

**Issue by haobo827** [openvinotoolkit/anomalib#270]
And it's easy for me that:
Epoch 10:  74%|███████████████2022-04-25 01:08:22,439 - anomalib.models.padim.lightning_model - INFO - Aggregating the embedding extracted from the training set.ation: 0it [00:00, ?it/s]
2022-04-25 01:09:31,280 - anomalib.models.padim.lightning_model - INFO - Fitting a Gaussian to the embedding collected from the training set.
Epoch 11:  74%|███████████████

Then:
RuntimeError: [enforce fail at CPUAllocator.cpp:71] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 132897177600 bytes. Error code 12 (Cannot allocate memory)

Troubled for a long time

**Comment by haobo827** [comment]
/home/devadmin/haobo/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/home/devadmin/haobo/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2022-04-25 00:51:08,051 - anomalib.models.padim.lightning_model - INFO - Initializing Padim Lightning model.
2022-04-25 00:51:18,415 - anomalib - INFO - Loading the experiment logger(s)
2022-04-25 00:51:18,415 - anomalib - INFO - Loading the callbacks
2022-04-25 00:51:50,361 - pytorch_lightning.utilities.distributed - INFO - GPU available: True, used: True
2022-04-25 00:51:50,380 - pytorch_lightning.utilities.distributed - INFO - TPU available: False, using: 0 TPU cores
2022-04-25 00:51:50,381 - pytorch_lightning.utilities.distributed - INFO - IPU available: False, using: 0 IPUs
2022-04-25 00:51:50,382 - anomalib - INFO - Training the model.
2022-04-25 00:51:50,411 - anomalib.data.folder - INFO - Setting up train, validation, test and prediction datasets.
/home/devadmin/haobo/C02_DisColor/anomalib-development/anomalib/data/folder.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  samples["mask_path"][index] = str(mask_dir / row.image_path.name)
/home/devadmin/haobo/C02_DisColor/anomalib-development/anomalib/data/folder.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  samples["mask_path"][index] = str(mask_dir / row.image_path.name)
2022-04-25 00:51:58,500 - pytorch_lightning.accelerators.gpu - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/devadmin/haobo/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py:37: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer

**Comment by haobo827** [comment]
Thank you for your help and patience

**Comment by mesolmaz** [comment]
I was going to create a new issue, but what I am experiencing is similar to this. During training, the memory is exhausted and crashes. Changing the batch size from 32 to 16 to 8 didn't make a difference and it always happens midway through the training. Here is the Config file and Error message.

**CONFIG:**

    dataset:
      name: folder #options: [mvtec, btech, folder]
      format: folder
      path: ./images
      normal_dir: good_train
      abnormal_dir: other_train
      normal_test_dir: null
      mask: null
      task: classification
      extensions: null
      split_ratio: 0.2  # ratio of the normal images that will be used to create a test split
      image_size: 512
      train_batch_size: 8
      test_batch_size: 8
      num_workers: 2
      transform_config:
        train: null
        val: null
      create_validation_set: true
      seed: 0
    
    model:
      name: dfm
      backbone: resnet50
      layer: layer3
    ... 

**ERROR:**
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 34359738368 bytes.

**Comment by samet-akcay** [comment]
@mesolmaz, I think the issue stems from the size of the feature map extracted from your dataset. Your dataset is likely to be large to fit into the memory. One possibility would be to reduce the feature-map extracted from the dataset, but I think it's currently not possible with DFM. I'll double check this with the team.

**Comment by mesolmaz** [comment]
@samet-akcay Thank you! Yes I figured this is the issue. Based on the image size, number of images and PCA component ratio, not every custom dataset is trainable without adjusting the config. Please consider this issue closed.
