### ISSUE TITLE
Add Gradio Support

### ISSUE THREAD

**Issue by julien-blanchon** [openvinotoolkit/anomalib#275]
Gradio App is an open source machine learning interface running on top of Python : https://gradio.app/

It's quite easy to implement and very hackable.
It's also compatible with Hugging Face Space (https://huggingface.co, https://huggingface.co/spaces).

I may help user and researcher to:

- Quickly debug their model (infer without any line of code, provide web drawing tool ...)
- Showcase their work
- Share model with the community (ie Hugging Face Space ...)
- Flagging unexpected behavior

![gradio](https://user-images.githubusercontent.com/11278197/165093206-ccb80241-690a-4ada-a218-ed86edb18856.png)
![gradio_draw1](https://user-images.githubusercontent.com/11278197/165093211-8c595ecb-3431-4b55-854e-52c4744d95d7.png)
![gradio_draw2](https://user-images.githubusercontent.com/11278197/165093212-8558d2e2-2855-4f9c-b63f-d0bea6fe9f19.png)

**Comment by julien-blanchon** [comment]
I've implemented a quick example with my EuroSat Dataset here: https://github.com/julien-blanchon/anomalib/tree/gradio
It may for now only work with `segmentation`

**Comment by ashwinvaidya17** [comment]
Great stuff! It was on our todo list.

**Comment by julien-blanchon** [comment]
I don't have the right to create a new branch here, I don't feel comfortable enough to request a merge with current project branch https://github.com/julien-blanchon/anomalib/tree/gradio

**Comment by ashwinvaidya17** [comment]
@julien-blanchon feel free to create a PR from your fork. We squash commits before merging in case that's what you are concerned about. We can always polish the rest in the PR review.
