### ISSUE TITLE
Get segmentation result from inference.py

### ISSUE THREAD

**Issue by Nayan-sse-tggs** [openvinotoolkit/anomalib#281]
If I run `inference.py`, I get a predicted heat map of original image as output. How do I get "**Segmentation Result**" as output (original image anomalies with boundaries) from `inference.py` script? Just like training output result where we get 6 figures which are "Image", "Ground Truth", "Predicted Heat Map", "Predicted Mask", "**Segmentation Result**" and "Classified Image". 
Thanks in advance

**Comment by ZeynepRuveyda** [comment]
Also you need to change 'category' name inside of the config.yaml file. You can find this in the patchcore folder.

**Comment by samet-akcay** [comment]
@Nayan-sse-tggs, just to understand the question, 

`inference.py` currently outputs the images based on the following format:
![image](https://user-images.githubusercontent.com/17574420/165704413-ae099ec6-3c87-49e8-b2b5-957cac295d84.png)

You would prefer to have the following format
![image](https://user-images.githubusercontent.com/17574420/165704630-2cd3a5af-7765-4fe9-b890-db6d0f9abfd9.png)

Is that correct?

**Comment by FaDavid98** [comment]
When I want to test my trained model on an unseen image, how can i get the segmentation result for that image?

**Comment by nguyenanhtuan1008** [comment]
Any update on this issue?

**Comment by samet-akcay** [comment]
There is a duplicate discussion in #294. Let's continue the discussion there. Closing this one.
