### ISSUE TITLE
Is the PatchCore image-level anomaly score correctly calculated?

### ISSUE THREAD

**Issue by StefanoSamele-PoliMi** [openvinotoolkit/anomalib#286]
We have found a significant difference between the implementation proposed and the one described in the paper, for the PatchCore image-level anomaly score calculation.

For a test image <img src="https://render.githubusercontent.com/render/math?math=x_{test}">, they first calculate the maximum distance score <img src="https://render.githubusercontent.com/render/math?math=s^{*}"> as:

![Screenshot 2022-04-26 at 16 36 19](https://user-images.githubusercontent.com/73292501/165325276-6d33a8ca-e034-4587-a12a-825f24ebf495.png)

where  <img src="https://render.githubusercontent.com/render/math?math=P(x_{test})"> is the set of patches of image <img src="https://render.githubusercontent.com/render/math?math=x_{test}"> and <img src="https://render.githubusercontent.com/render/math?math=M"> the memory bank. 

They then apply a re-weighting factor to take into account if the patch <img src="https://render.githubusercontent.com/render/math?math=m^*"> is far from neighboring samples and thereby
an already rare nominal occurrence.

![Screenshot 2022-04-26 at 16 17 38](https://user-images.githubusercontent.com/73292501/165324752-980bb358-fe97-48fd-87ac-a37b31d8a327.png)

We underline that <img src="https://render.githubusercontent.com/render/math?math=N_{b}(m^*)"> are the nearest neighbors of <img src="https://render.githubusercontent.com/render/math?math=m^*"> in the memory bank. In your implementation instead, you weigh according to the nearest neighbors of <img src="https://render.githubusercontent.com/render/math?math=m_{test}^*">, choosing the distance from the furthest element as numerator, and the distances from the others as denominator.

We have tested the two scoring methods (the original one and the one proposed in this repository) on a custom dataset and no differences were registered in terms of AUCROC score. We are currently testing on some MVTEC classes.

**Comment by samet-akcay** [comment]
Thanks @StefanoSamele-PoliMi! We'll check it out

**Comment by lorenzomammana** [comment]
Adding to the discussion, if you aren't aware patchcore authors updated their paper on arxiv and upload the official implementation of the algorithm, apparently it performs even better than the result reported by you (99.2 compared to 98.0 avg) with the wide resnet 50. If you have time might be worth checking it out!
[https://github.com/amazon-research/patchcore-inspection](https://github.com/amazon-research/patchcore-inspection)

**Comment by cyj95** [comment]
In official patchcore work, the performance is   Patchcore(99.1,98.1).
But your work get (98.0,98.0),which is lower than official.
Why is that ?  Is there any problem about the score calculation?
