### ISSUE TITLE
add_label in inference.py cannot put text on small image

### ISSUE THREAD

**Issue by ABoLei** [openvinotoolkit/anomalib#289]
**Describe the bug**

Function `add_label` in `inference.py` cannot put text on small image(height=18, width=43, jpeg image)

**To Reproduce**
1. Prepare small height and width of image(s), e.g. height=18, width=43, jpeg image
2. Specify `--image_path` to the image from step1
3. Run `inference.py`

**Expected behavior**
Put inferenced result on a image

**Screenshots**

![image](https://user-images.githubusercontent.com/9088253/165656000-40bd1dd3-2b88-4b82-b242-bf7c5ad2d310.png)

**Hardware and Software Configuration**
- OS: Windows
- NVIDIA Driver Version [v471.11]
- CUDA Version [v11.4]
- CUDNN Version [v11.4.120]

**Comment by djdameln** [comment]
This has been solved with the visualizer refactor.
