### ISSUE TITLE
Possible bug in Inference part.

### ISSUE THREAD

**Issue by innat** [openvinotoolkit/anomalib#290]
**Describe the bug**
- Training and Validation work fine. But running inference.py gives a noisy heatmap. Tried only with patchcore, not tested rest. 

**To Reproduce**
1. Go to https://www.kaggle.com/code/ipythonx/mvtec-ad-anomaly-detection-with-anomalib-library?scriptVersionId=94212905
2. Open it to run.
3. In the last cell (inference part), uncomment the code.
4. Now, run the notebook and see the output of the last cell (inference part).

**Expected behavior**
- It should be ok so far.

**Screenshots**
![download](https://user-images.githubusercontent.com/17668390/165699829-2a3dad30-2d9a-4326-b4ae-4374bb899667.png)

**Hardware and Software Configuration**
- Env.: Kaggle

**Additional context*
- Is OpenVino installation a must? I tried to run on the GCP instance (ubuntu) but faced opinion related issue through my checkpoint's format (`ckpt`).

**Comment by samet-akcay** [comment]
@innat, we have seen a similar behaviour before, where the issue turned out to be related to torch (CUDNN enabled/disabled on the platform). We'll investigate this.

**Comment by innat** [comment]
@samet-akcay the inference is working fine now. I faced it on kaggle environment, but now it's solved. We can close the issue.

**Comment by samet-akcay** [comment]
That's great! Do you know what the issue was?

**Comment by innat** [comment]
There was a bug in code in my side, which I fixed in latest (notebook) version. 
( But I didn't test with open-vino inference neither on kaggle environment or GCP. )

**Comment by samet-akcay** [comment]
Thanks for the update
