### ISSUE TITLE
The evaluation index

### ISSUE THREAD

**Issue by mouxinyue1** [openvinotoolkit/anomalib#309]
I want to ask which codes are used to calculate the evaluation indicators

**Comment by djdameln** [comment]
Hi, evaluation is done using a mixture of standard classes from the TorchMetrics package, and custom metric classes which are also based on TorchMetrics. The metrics can be configured from the config, where a list of metric names can be passed for both image-level and pixel-level evaluation, like so:
```
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
```
The specified list of metrics is processed in [this function](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/utils/metrics/__init__.py#L19), which is called from the [base anomaly module](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/models/components/base/anomaly_module.py#L60) when the model is first constructed. The function will first search for anomalib's [own metric implementations](https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/utils/metrics) for matching metric names, and if no matching metric is found, it will try to match it with one of the standard TorchMetrics classes. Separate metric collections are created for both image-level and pixel-level evaluation metrics.

During evaluation (validation, testing), the GT labels and the predictions of the model are [collected](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/models/components/base/anomaly_module.py#L156) in the metric collections, after which the metric results are [computed and logged](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/models/components/base/anomaly_module.py#L177).

For more information on TorchMetrics package, please refer to the [documentation](https://torchmetrics.readthedocs.io/en/stable/) of that package.

**Comment by mouxinyue1** [comment]
Are the Detection AUROC and Segmentation AUROC in the original text image-level evaluations？

**Comment by djdameln** [comment]
The AUROC, like most other metrics, can be evaluated either at image-level or at pixel-level, depending on the inputs. If the inputs to the metric class consist of image-level ground truth labels and the predicted image-level anomaly score, the metric will be evaluated at the image level. If the inputs consist of ground truth segmentation masks and the predicted anomaly score maps, the metric will be evaluated at pixel-level.

The `metrics` section in the config lists the metrics that will be evaluated at image level and pixel level. For example, we can configure anomalib to compute the MeanSquaredError metric at the pixel level, but not at the image level, by only adding it to the list of pixel metrics in the config:

```
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
    - MeanSquaredError
```

**Comment by mouxinyue1** [comment]
Ok, I see. Thank you very much for your help！

**Comment by djdameln** [comment]
You're welcome :)
