### ISSUE TITLE
Add support for Inference with Torch Models on CPU-only Machines

### ISSUE THREAD

**Issue by shakib-root** [openvinotoolkit/anomalib#317]
Currently, If we try to do inference on a CPU-only machine it gives:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

The concerned method [load_model](https://github.com/openvinotoolkit/anomalib/blob/9b117b00fc20f5639dc43fb830992a7f45acefd2/anomalib/deploy/inferencers/torch.py#L76) can be found at anomalib/deploy/inferencers/torch.py where
`model.load_state_dict(torch.load(path)["state_dict"])` needs to be updated.

I am not quite sure of a good way to do this. Maybe we can add something like this in `config.yaml`
```yaml
inference:
    gpu: true
```
and update `load_model` as:

```python
def load_model(self, path: Union[str, Path]) -> AnomalyModule:
        """Load the PyTorch model.
        Args:
            path (Union[str, Path]): Path to model ckpt file.
        Returns:
            (AnomalyModule): PyTorch Lightning model.
        """
        model = get_model(self.config)
        if self.config.inference.gpu:
            model.load_state_dict(torch.load(path)["state_dict"])
        else:
            model.load_state_dict(torch.load(path, map_location=torch.device('cpu'))["state_dict"])
        model.eval()
        return model
```

**Comment by samet-akcay** [comment]
Hi @shakib-root, there is currently a PR #298 that replaces the existing `TorchInferencer` with Pytorch Lightning inference, which would automatically handle device related issues.

**Comment by samet-akcay** [comment]
@shakib-root, will you be able to check this out our new inferencer. Ideally this issue should be resolved

**Comment by samet-akcay** [comment]
I'm closing this, but feel free to re-open it if you face an issue. Cheers!
