### ISSUE TITLE
Cannot import name ' configure_logger'

### ISSUE THREAD

**Issue by ING3TP2** [openvinotoolkit/anomalib#320]
Hello, I am having the error: Cannot import name 'configure_logger' from 'anomalib.utils.loggers' while trying to run the following command :
python tools/train.py --config anomalib/models/padim/config.yaml
error coming from the file below
![image](https://user-images.githubusercontent.com/92035159/168626357-6e143652-606e-4fb8-b052-5f01f5e63b87.png)

**Comment by ashwinvaidya17** [comment]
@ING3TP2 Are you on the development branch? How did you install anomalib in your environment?

**Comment by ashwinvaidya17** [comment]
I would suggest cloning the repo and installing using `pip install -e .` Let me know how that goes.

**Comment by ING3TP2** [comment]
![image](https://user-images.githubusercontent.com/92035159/170987372-5c3b9821-aca4-4adc-9003-b0d42c718305.png)
the same error occured after installing it from the windows Terminal command..

**Comment by ING3TP2** [comment]
![image](https://user-images.githubusercontent.com/92035159/171000900-de681015-e9de-4fc5-bc16-686cf904cc21.png)
Thank you so much, it has actually worked, but when it finished downloading the dataset and started to train, the PC crashed (I guess because of the large data) especially that I don't use GPU, so I had to shut it down. Actually now I'm willing to train on a custom dataset, and as I read in the instructions to be able to train on a Custom Dataset we have first to configure the config.yaml file, so supposing I want to train the model PADIM on a custom dataset , am I supposed to modify the config.yaml in the Padim folder?

**Comment by ashwinvaidya17** [comment]
Glad to know that it worked! You can either modify the config file in Padim folder or you can pass the path to a new config file using `--config` flag in `train.py`

**Comment by ING3TP2** [comment]
Thank you ! I have changed the config file, and I guess I have some issues in the library omegaconf and in _init_.py file in data folder, based on these errors..
![image](https://user-images.githubusercontent.com/92035159/171058319-84ac23dc-fc3d-4793-89ea-27280be60bcd.png)
when I checked _init_.py file in data folder I found problems in these libraries :
![image](https://user-images.githubusercontent.com/92035159/171061543-6d2b6210-aa03-4307-8b71-01623ee5d0b8.png)
even after installing the omegaconf package, nothing has changed

**Comment by samet-akcay** [comment]
@ING3TP2, can you share your config file?

**Comment by ashwinvaidya17** [comment]
Ah! The readme needs to be updated. Try using keys `normal_dir`, `abnormal_dir` and `normal_test_dir: None`. Instead of `normal:`, 
`abnormal:` in the config.yaml

**Comment by ING3TP2** [comment]
Thank you it was indeed the problem, but I guess some other keys should be changed referring to this error :
![image](https://user-images.githubusercontent.com/92035159/171160829-336d1d56-0b91-4b82-9fef-431b01765a91.png)
![image](https://user-images.githubusercontent.com/92035159/171161264-ba7674ad-a88a-43a5-bd96-9a191a876d8f.png)

**Comment by ING3TP2** [comment]
@samet-akcay  I didn't really know how to share the file so here's the changements tht are made
![image](https://user-images.githubusercontent.com/92035159/171162059-85c578cf-b2ee-4aed-96a0-cf0054a10c0f.png)

**Comment by ashwinvaidya17** [comment]
@ING3TP2 This PR has been merged to development https://github.com/openvinotoolkit/anomalib/pull/338. Can you confirm if these changes address your problem?
