### ISSUE TITLE
Refactor NNCF config

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#322]
When configuring NNCF, we currently have to add the nncf parameters to the `config.yaml` under `optimization.nncf`.

It would be easier to just pass the file path to a NNCF config json file as a single NNCF parameter. This way, we don't deviate from the original NNCF config format that is described and explained in the NNCF documentation, and at the same time keep our `config.yaml` clean.

**Comment by samet-akcay** [comment]
Sub-task of https://github.com/openvinotoolkit/anomalib/issues/20
