### ISSUE TITLE
PatchCore aggregation function not clear

### ISSUE THREAD

**Issue by AlessandroPolidori** [openvinotoolkit/anomalib#323]
Hi everyone, i'm trying to understand how the PatchCore's feature aggregation / patch embedding has been implemented here in anomalib. In particular, i don't understand what is happening here and what the avgPooling is doing on the patches' featuremaps. I hope someone can clarify it to me.

https://github.com/openvinotoolkit/anomalib/blob/17b62f8d97fe407405c871992bd4f1949f2c5cbb/anomalib/models/patchcore/torch_model.py#L79-L95

**Comment by alexriedel1** [comment]
You can find the explanation in the paper

https://arxiv.org/pdf/2106.08265.pdf

> For PatchCore, we use adaptive average pooling. This is similar to local smoothing over each individual feature map, and 
 esults in one single representation at (h, w) of predefined dimensionality d, which is performed for all pairs (h, w) with h ∈ {1, ..., h∗} and w ∈ {1, ..., w∗} and thus retains feature map resolution.

**Comment by alexriedel1** [comment]
Imagine the features on a feature map. If you use a kernel to smooth this map, information from neighbouring features will be shared across the affected features. 

Here's a plot of the PatchCore feature map of wide_resnet_50_2 layer 2 and layer 3 before and after average pooling with a 3x3 kernel:
![image](https://user-images.githubusercontent.com/54716527/169097761-84d71d84-edfe-4c3c-92ff-a12dcacd52ef.png)

Using a 7x7 "blurs" the feature maps even more, I hope this helps to understand the idea behind it:
![image](https://user-images.githubusercontent.com/54716527/169098278-99145db8-17c3-472a-960a-cb9176a79755.png)


I guess adapative pooling is not used because the feature maps are resized anyways in the process

**Comment by AlessandroPolidori** [comment]
First of all i want to thank you for your clarity and kindness. Now, the thing that seems different to me is the aggregation function. I made two simple drawings depicting (what i think) anomalib's implementation is doing and what it's in the paper. In anomalib it seems to me that the averagePooling is applied on every patch, separately, after you apply tile() and "line up" the patches.

![anomalib](https://user-images.githubusercontent.com/61737239/169120165-cb177a30-46c8-474d-bd29-5cd2680c5aba.png)

This is the paper way (here i depict only the aggregation function action for one of the patches):
![patchcorepaper](https://user-images.githubusercontent.com/61737239/169122406-e77ef244-7413-4f83-b96a-ac106d1b61d4.png)

**Comment by AlessandroPolidori** [comment]
> First of all i want to thank you for your clarity and kindness. Now, the thing that seems different to me is the aggregation function. I made two simple drawings depicting (what i think) anomalib's implementation is doing and what it's in the paper. In anomalib it seems to me that the averagePooling is applied on every patch, separately, after you apply tile() and "line up" the patches.
> 
> ![anomalib](https://user-images.githubusercontent.com/61737239/169120165-cb177a30-46c8-474d-bd29-5cd2680c5aba.png)
> 
> This is the paper way (here i depict only the aggregation function action for one of the patches): ![patchcorepaper](https://user-images.githubusercontent.com/61737239/169122406-e77ef244-7413-4f83-b96a-ac106d1b61d4.png)

@alexriedel1

**Comment by alexriedel1** [comment]
I guess you are referring to this line when talking of tiling: https://github.com/openvinotoolkit/anomalib/blob/17b62f8d97fe407405c871992bd4f1949f2c5cbb/anomalib/models/patchcore/torch_model.py#L79-L80

However, this is only applied to easily process large images and is not related to patchcore or any model directly https://github.com/openvinotoolkit/anomalib/blob/17b62f8d97fe407405c871992bd4f1949f2c5cbb/anomalib/pre_processing/tiler.py#L131-L139

The "patches" actually refer to the feature stacks on the feature maps.
