### ISSUE TITLE
Label Prediction with Confidence score

### ISSUE THREAD

**Issue by ngadhvi** [openvinotoolkit/anomalib#326]
I have noticed some good improvements in version 0.3 of Anomalib. I wondered if there is any way to get a Label as prediction along with the confidence score in inference as we get in the testing after the training?  

P.S. Referring to fitting a PaDiM model and inference from it.

**Comment by samet-akcay** [comment]
Hi @ngadhvi, there is curently a PR for this. See #298

**Comment by ngadhvi** [comment]
Thank you for the update @samet-akcay. Looking forward to it.
