### ISSUE TITLE
Heatmap  visualization results for classification (task)! 

### ISSUE THREAD

**Issue by innat** [openvinotoolkit/anomalib#327]
**Is your feature request related to a problem? Please describe.**
If we train the model as a segmentation (with a mask), we can have nice heatmap visualization in the results. But as for classification, we can't. ( Though it's reasonable. )

![165101253-6fb6958c-f9f7-4eb7-aeba-6a448fe0238a](https://user-images.githubusercontent.com/17668390/169534773-5d679334-a7e9-41d6-8d98-0d4e349af7ff.png)

**Describe the solution you'd like**
I am thinking if we can make use of the **explainable-ai** technique to visualize some kind of heatmap for classification tasks (without any mask). Though it may not be beneficial for some model which only requires 1 epoch. 
  - SHAP
  - Grad-CAM

**Comment by alexriedel1** [comment]
Why would you need Grad-CAM if you have the heatmap? 

+ Grad-CAM or derivatives won't work with simply sticking them to one of the models. You don't predict classes like normal with a forward network pass. In most of the methods implemented in anomalib, features are extracted and processed in order to get a classification (and/or heatmap) of anomaly. 

How would you implement a gradient-based visualization method in this pipelin?

**Comment by innat** [comment]
> Why would you need Grad-CAM if you have the heatmap?

Heatmap is only generated if I have a ground truth mask, right? Otherwise, if I train a model with `task: classification`, do I still able to get the same heatmap? I'm using an older commit, so not sure if there's anything new that is added. Please let me know. 

> How would you implement a gradient-based visualization method in this pipeline?

It's not a proposal to implement grad-cam. The point here is if we can add any mechanism that can produce some kind of visual indicative results on the defected area even if the model is trained as classification. If I'm not mistaken, if we train a model as classification, we can't have a heatmap that indicates the defected area.

**Comment by samet-akcay** [comment]
Generating a heatmap doesn't depend on the task type but algorithm. For example, cflow, padim, patchcore and stfpm does produce heatmap both for classification and segmentation tasks. We dont show it for classification, but it's possible to visualise if needed.

Dfkde and dfm don't generate a heatmap, mainly because it doesn't have anomaly-map-generator module. It's, however, possible to implement it by upsampling the featuremap to the input image size.

**Comment by alexriedel1** [comment]
Models that are capable of segmentation will always output a heatmap. 

Currently, the visualizer callback doesn't add it to the output images, but still it's there (you would have to rewrite parts of the visualizer a bit)
https://github.com/openvinotoolkit/anomalib/blob/17b62f8d97fe407405c871992bd4f1949f2c5cbb/anomalib/utils/callbacks/visualizer_callback.py#L127-L159

If you use the example inference script with your trained model, the heatmap will be saved.

https://github.com/openvinotoolkit/anomalib/blob/development/tools/inference.py

**Comment by innat** [comment]
@alexriedel1 Thanks for the pointer. Though the old commit I'm using is different than the above but it's solved overall. :)

**Comment by innat** [comment]
@samet-akcay 
> We don't show it for classification, but it's possible to visualize if needed.

Thanks for the information. I think it should be added.

**Comment by udasinnayan** [comment]
For classification task (with custom dataset where no ground truth mask is provided), patchcore model can generate heatmap (usually get percentage of anomalous image as output) which is easier to identify anomalies where normal patches has different color then anomalies. Is it possible to create bounding box for all the detected anomalies in Classification task?

For visualization in `anomalib/post_processing/visualizer.py` script, I have tried to call `mark_boundaries` from `skimage.segmentation` and edit  `_visualize_simple()`  function. The sample code it following (it has been used in segmentation task for mark boundaries):

```
    def _visualize_simple(self, image_result):
        """Generate a simple visualization for an image.

        The simple visualization mode only shows the model's predictions in a single image.

        Args:
            image_result (ImageResult): GT and Prediction data for a single image.

        Returns:
            An image showing the simple visualization for the input image.
        """
        if self.task == "segmentation":
            visualization = mark_boundaries(
                image_result.heat_map, image_result.pred_mask, color=(1, 0, 0), mode="thick"
            )
            return (visualization * 255).astype(np.uint8)
        if self.task == "classification":
            # this section is edited 

            # if image_result.pred_label:
            #     image_classified = add_anomalous_label(image_result.image, image_result.pred_score)
            # else:
            #     image_classified = add_normal_label(image_result.image, 1 - image_result.pred_score)
            # return image_classified

            visualization = mark_boundaries(
                image_result.image, image_result.pred_mask, color=(1, 0, 0), mode="thick"
            )
            return (visualization * 255).astype(np.uint8)

        raise ValueError(f"Unknown task type: {self.task}")
```

Inference script
`python tools/inference/lightning_inference.py --config */patchcore/config.yaml --weights */model.ckpt --input */sample.png --output */* --visualization_mode simple
`

As an output, patchcore model can give us some boundaries (only for major defects) of detected anomalies but not all of them. How do I create bounding box for all detected anomalies for classification task from patchcore model with using custom dataset?

**Comment by watertianyi** [comment]
@alexriedel1 @samet-akcay @innat 
![Image_20241127153444](https://github.com/user-attachments/assets/9d69f900-691b-47b1-9bcf-d6361e1fa475)

Use EfficientAd for classification reasoning. The leftmost one is converted into the result of onnx reasoning, which clearly distinguishes the defective area. The three pictures on the right use TorchInferencer for reasoning, but the defective area is not reflected in the heat map. What's going on?
