### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ZeynepRuveyda** [openvinotoolkit/anomalib#329]
UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
  rank_zero_warn(
Traceback (most recent call last):
  File "/home/zeynep/zynp/anomalib/tools/train.py", line 99, in <module>
    train()
  File "/home/zeynep/zynp/anomalib/tools/train.py", line 88, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 208, in on_run_start
    self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1995, in reset_train_val_dataloaders
    self.reset_val_dataloader(model=model)
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1948, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._data_connector._reset_eval_dataloader(
  File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 424, in _reset_eval_dataloader
    min_pct = 1.0 / len(dataloader)
ZeroDivisionError: float division by zero

Is anyone help me to solve this bug?

Thanks in advance,
Zeynep

**Comment by ZeynepRuveyda** [comment]
Do I need to use put the image in pairs? (Groundtruth and test images)

**Comment by ZeynepRuveyda** [comment]
> UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention. rank_zero_warn( Traceback (most recent call last): File "/home/zeynep/zynp/anomalib/tools/train.py", line 99, in train() File "/home/zeynep/zynp/anomalib/tools/train.py", line 88, in train trainer.fit(model=model, datamodule=datamodule) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit self._call_and_handle_interrupt( File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl results = self._run(model, ckpt_path=self.ckpt_path) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run results = self._run_stage() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage return self._run_train() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train self.fit_loop.run() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run self.on_run_start(*args, **kwargs) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 208, in on_run_start self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1995, in reset_train_val_dataloaders self.reset_val_dataloader(model=model) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1948, in reset_val_dataloader self.num_val_batches, self.val_dataloaders = self._data_connector._reset_eval_dataloader( File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 424, in _reset_eval_dataloader min_pct = 1.0 / len(dataloader) ZeroDivisionError: float division by zero
> 
> Is anyone help me to solve this bug?
> 
> Thanks in advance, Zeynep

Do I need to use put the image in pairs? (Groundtruth and test images)

**Comment by ZeynepRuveyda** [comment]
> > UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention. rank_zero_warn( Traceback (most recent call last): File "/home/zeynep/zynp/anomalib/tools/train.py", line 99, in train() File "/home/zeynep/zynp/anomalib/tools/train.py", line 88, in train trainer.fit(model=model, datamodule=datamodule) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit self._call_and_handle_interrupt( File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl results = self._run(model, ckpt_path=self.ckpt_path) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run results = self._run_stage() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage return self._run_train() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train self.fit_loop.run() File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run self.on_run_start(*args, **kwargs) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 208, in on_run_start self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1995, in reset_train_val_dataloaders self.reset_val_dataloader(model=model) File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1948, in reset_val_dataloader self.num_val_batches, self.val_dataloaders = self._data_connector._reset_eval_dataloader( File "/home/zeynep/zynp/env/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 424, in _reset_eval_dataloader min_pct = 1.0 / len(dataloader) ZeroDivisionError: float division by zero
> > Is anyone help me to solve this bug?
> > Thanks in advance, Zeynep
> 
> Do I need to put the image in pairs? (Groundtruth and test images)

Here is my config file!
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  category: FL
  task: segmentation
  image_size: 850
  train_batch_size: 32
  test_batch_size: 1
  num_workers: 16
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]
  threshold:
    image_default: 7
    pixel_default: 15
    adaptive: False

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC

project:
  seed: 42
  path: ./results
  log_images_to: ["local"]
  logger: false # options: [tensorboard, wandb, csv] or combinations.

optimization:
  openvino:
    apply: true

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 3
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 50
  replace_sampler_ddp: true
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.

**Comment by alexriedel1** [comment]
Looks like there are no images in `./datasets/MVTec/FL`

**Comment by ZeynepRuveyda** [comment]
> Looks like there are no images in `./datasets/MVTec/FL`

Hi @alexriedel1, I have images inside of the FL folder. I check the path that is true.

**Comment by alexriedel1** [comment]
> > Looks like there are no images in `./datasets/MVTec/FL`
> 
> Hi @alexriedel1, I have images inside of the FL folder. I check the path that is true.

Can you please show your complete folder structure?

**Comment by ZeynepRuveyda** [comment]
> > > Looks like there are no images in `./datasets/MVTec/FL`
> > 
> > 
> > Hi @alexriedel1, I have images inside of the FL folder. I check the path that is true.
> 
> Can you please show your complete folder structure?

![image](https://user-images.githubusercontent.com/72027409/169848783-32114544-be5b-4064-b89a-91f65593c808.png)

**Comment by samet-akcay** [comment]
@ZeynepRuveyda, I see that you are using MVTec format. The mask images in MVTec has `_mask.png` suffix. In this case your mask images should be like

```shell
ground_truth
---- bad
--------fng-d090_mask.png
```

Alternatively you could try using the `folder` format instead of using `mvtec`, which offers more flexibility.

**Comment by alexriedel1** [comment]
Also be aware that the MVTec Dataloader searches for `.png` and not for `.jpg`

https://github.com/openvinotoolkit/anomalib/blob/17b62f8d97fe407405c871992bd4f1949f2c5cbb/anomalib/data/mvtec.py#L122

**Comment by samet-akcay** [comment]
sounds like this is similar to #143. Thought this issue had been fixed, but looks like we need to double check.

**Comment by ZeynepRuveyda** [comment]
Ok. Thanks for your help.
