### ISSUE TITLE
Get rid of task_type parameter

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#34]
The `task_type` parameter currently dictates which types of ground truth data is passed to the model. When the `task_type` parameter is set to `segmentation`, the ground truth pixel masks are passed in addition to the image-level labels. This might no longer be needed. Instead we can just pass whatever ground truth information is available, and let the PL module handle the evaluation based on what type of ground truth data it receives with the batches.

**Comment by samet-akcay** [comment]
Closing this issue due to DX
