### ISSUE TITLE
The unknown issue about the predicted mask while using PatchCore

### ISSUE THREAD

**Issue by Cassie07** [openvinotoolkit/anomalib#367]
Dear contributors,

Hello! First of all, thanks for developing and maintaining such an awesome anomaly detection library.

***Problem Description***
I am training PatchCore and Padim on my dataset, which is similar to MVTec AD. However, I found that the Padim works well while PatchCore shows an unreasonable segmentation performance. (I will continue checking with my customized data loading function. So far, it works well on Padim.) Besides the unreasonably low segmentation performance, I found that the predicted mask is always totally white for both the training and testing set while no error was reported. I really appreciate if there is any suggestion for this issue or the related functions.

Thanks for the help!

***Screenshots***
**Padim**
<img width="1095" alt="Padim" src="https://user-images.githubusercontent.com/31313145/173472119-f6718b50-7ac4-4273-90f3-403849b60e80.png">

**PatchCore**
<img width="1138" alt="Patchcore" src="https://user-images.githubusercontent.com/31313145/173472135-8db57134-64ba-4a36-b337-804f4f623aa8.png">

**Comment by papago2355** [comment]
Hello I also encountered same issues. How did you solve this? I am completely opposite to your situation. All my results are returned True and mask everything in test dataset.
