### ISSUE TITLE
_src.empty() in function 'cvtColor

### ISSUE THREAD

**Issue by EudicL** [openvinotoolkit/anomalib#393]
Hi, when i  input the command below :
anomalib fit --config ./configs/model/padim_1.yaml  

the erro is :
 image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor

**Comment by samet-akcay** [comment]
@EudicL, looks like opencv cannot load the image. You need to ensure that the path to your dataset is correct. If you could share your config, we could help

**Comment by EudicL** [comment]
> @EudicL, looks like opencv cannot load the image. You need to ensure that the path to your dataset is correct. If you could share your config, we could help

Thanks, i found a broken image in  my datasets

**Comment by samet-akcay** [comment]
Let us know if you are able to train the model. If yes, we could close the issue.

**Comment by EudicL** [comment]
> 

yes
