### ISSUE TITLE
Getting the segmentation results during testing

### ISSUE THREAD

**Issue by FaDavid98** [openvinotoolkit/anomalib#400]
I saw that during training the model finds the best threhold, and shows the segmentation results for the testing images. I am wondering, how could I get those segemntation results in the testing phase. 
I mean i want to run the inference.py file and get those segmentation result for the used image.
Thanks for your answer.

**Comment by nguyenanhtuan1008** [comment]
@FaDavid98 Do you get the solution?

**Comment by samet-akcay** [comment]
Hi @FaDavid98, what sort of result woulld you like to get? A mask, polygons? Any other format?

**Comment by samet-akcay** [comment]
Duplicate of #294. Let's continue our discussion there.
