### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key log_images_to full_key: logging.log_images_to

### ISSUE THREAD

**Issue by billyc97** [openvinotoolkit/anomalib#402]
The bug "omegaconf.errors.ConfigAttributeError: Missing key log_images_to full_key: logging.log_images_to" appears when I run the train.py file, also encountered this issue when I run the Colab Notebook that was provided in the Getting Started section. All the files are freshly downloaded without being modified.

Exact procedures to reach here:
1.  setup Anaconda environment on Windows 10 
2.  pip install anomalib
3.  pip install -r requirements\base.txt
4.  pip install -r requirements\dev.txt
5. python tools\train.py --config C:\Users\Billy\Downloads\anomalib-development\anomalib\models\padim\config.yaml
   (running python tools\train.py yields the same result)

(For the Google Colab example, I just follow the steps in the notebook exactly, but the same error appeared.)

Error Code:

(anomalib) C:\Users\Billy\Downloads\anomalib-development>python tools\train.py --config C:\Users\Billy\Downloads\anomalib-development\anomalib\models\padim\config.yaml
2022-07-05 09:22:19,934 - pytorch_lightning.utilities.seed - INFO - Global seed set to 42
C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (AdaptiveThreshold). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_no_full_state`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.

  warnings.warn(*args, **kwargs)
C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (AnomalyScoreDistribution). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_no_full_state`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.

  warnings.warn(*args, **kwargs)
C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (MinMax). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_no_full_state`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.

  warnings.warn(*args, **kwargs)
2022-07-05 09:22:20,941 - anomalib.models.padim.lightning_model - INFO - Initializing Padim Lightning model.
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\Billy/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|█████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:04<00:00, 11.0MB/s]
Traceback (most recent call last):
  File "tools\train.py", line 82, in <module>
    train()
  File "tools\train.py", line 67, in train
    callbacks = get_callbacks(config)
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\anomalib\utils\callbacks\__init__.py", line 112, in get_callbacks
    if not config.logging.log_images_to == []:
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\dictconfig.py", line 357, in __getattr__
    self._format_and_raise(
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\dictconfig.py", line 353, in __getattr__
    return self._get_impl(
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\dictconfig.py", line 444, in _get_impl
    node = self._get_child(
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "C:\Users\Billy\anaconda3\envs\anomalib\lib\site-packages\omegaconf\dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key log_images_to
    full_key: logging.log_images_to
    object_type=dict

![image](https://user-images.githubusercontent.com/46989687/177234010-b0db4818-f757-413f-96e1-a9e256139345.png)

Hardware and Software Configuration:
- OS: Windows 10
- NVIDIA Driver Version [516.59]
- CUDA Version [11.2]
- CUDNN Version [8.1]

**Comment by samet-akcay** [comment]
Hi @billyc97, this is a known issue for the pypi version.  To avoid it you could temporarily use the local installation instead.

```bash
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
```

We'll fix the PyPI version today so you could try `pip install anomalib` later

**Comment by ashwinvaidya17** [comment]
@billyc97 can you try installing the latest anomalib `pip install anomalib==0.3.3`?

**Comment by billyc97** [comment]
@ashwinvaidya17 It seems that this issue is resolved, thanks!

**Comment by samet-akcay** [comment]
@billyc97, great! I'm closing the issue then
