### ISSUE TITLE
Make config loading more flexible

### ISSUE THREAD

**Issue by Lucas-Steinmann** [openvinotoolkit/anomalib#412]
**Is your feature request related to a problem? Please describe.**
My problem is, that I want to allow the user, to load the config, but overwrite some values via command line arguments.
This is currently not possible, without copying some larger chunks of code from [get_configurable_parameters](https://github.com/openvinotoolkit/anomalib/blob/e8af956c85eb3e26dcc45bcb6e5cee27d0f55809/anomalib/config/config.py#L116]).
The issue lies in the fact, that this function loads the config from a file and immediately infers some new values.
 But when the user wants to overwrite some values, which are used for inference (e.g. `project.path`), he can only do so afterwards, which may lead to some inconsistencies.

Other deep learning libraries have similar functionality, e.g. [mmdetection](https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/tools/train.py#L73) by specifying `--cfg-options`.

**Describe the solution you'd like**
I would suggest splitting the function into two functions, since it actually does two jobs (loading and augmenting).
This makes it a lot more flexible. For use cases where it is not necessary to modify the config, a wrapper function could be written, which calls both parts in sequence.

**Describe alternatives you've considered**
Load the config, update the values, save them to a temporary file and give that path to the function above.

**Additional context**
Here is how I currently fixed in my local repo:

```python3
def get_configurable_parameters(
    model_name: Optional[str] = None,
    config_path: Optional[Union[Path, str]] = None,
    config_filename: Optional[str] = "config",
    config_file_extension: Optional[str] = "yaml",
) -> Union[DictConfig, ListConfig]:
    """Get configurable parameters.

    Args:
        model_name: Optional[str]:  (Default value = None)
        config_path: Optional[Union[Path, str]]:  (Default value = None)
        config_filename: Optional[str]:  (Default value = "config")
        config_file_extension: Optional[str]:  (Default value = "yaml")

    Returns:
        Union[DictConfig, ListConfig]: Configurable parameters in DictConfig object.
    """
    if model_name is None and config_path is None:
        raise ValueError(
            "Both model_name and model config path cannot be None! "
            "Please provide a model name or path to a config file!"
        )

    if config_path is None:
        config_path = Path(f"anomalib/models/{model_name}/{config_filename}.{config_file_extension}")

    config = OmegaConf.load(config_path)
    return config


def update_config(
        config: Union[DictConfig, ListConfig],
        weight_file: Optional[str] = None,
):
    """Set some default parameters and infer others in the config.

    Args:
        config: Union[DictConfig, ListConfig]: The base config, which should be modified
        weight_file: Path to the weight file

    Returns:
        Union[DictConfig, ListConfig]: Configurable parameters in DictConfig object.
    """
    # Dataset Configs
    if "format" not in config.dataset.keys():
        config.dataset.format = "mvtec"

    config = update_input_size_config(config)

    # Project Configs
    project_path = Path(config.project.path) / config.model.name / config.dataset.name
    if config.dataset.format.lower() in ("btech", "mvtec"):
        project_path = project_path / config.dataset.category

    (project_path / "weights").mkdir(parents=True, exist_ok=True)
    (project_path / "images").mkdir(parents=True, exist_ok=True)
    config.project.path = str(project_path)
    # loggers should write to results/model/dataset/category/ folder
    config.trainer.default_root_dir = str(project_path)

    if weight_file:
        config.model.weight_file = weight_file

    config = update_nncf_config(config)

    # thresholding
    if "metrics" in config.keys():
        if "pixel_default" not in config.metrics.threshold.keys():
            config.metrics.threshold.pixel_default = config.metrics.threshold.image_default

    return config
```

If desired, I can create a pull request.

**Comment by samet-akcay** [comment]
@Lucas-Steinmann, to address this, we have recently introduced a new [CLI](https://github.com/openvinotoolkit/anomalib#%EF%B8%8F-anomalib--v040-beta---subject-to-change). It's currently in beta, and unfortunately not yet documented. It's based on [Pytorch Lightning CLI.](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html), so referring to its documentation could be a good start.

We'll be improving its documentation to show its capabilities.

**Comment by Lucas-Steinmann** [comment]
Oh cool, I'll keep an eye on this. Thank you!

**Comment by samet-akcay** [comment]
As I mentioned, it's still in beta, which would be error-prone, but we want to make it more stable by v.0.4.0 so it would be the default CLI approach.
