### ISSUE TITLE
Unable to convert PADIM to ONNX graph

### ISSUE THREAD

**Issue by pyhow** [openvinotoolkit/anomalib#413]
Good day,

I faced some issues when trying to convert PADIM weights to ONNX format which works well for GANomaly and stfpm models.
Attached is the error displayed:
![padim_onnx](https://user-images.githubusercontent.com/91107801/177913437-cedc87fc-b98b-4305-bf4c-3aa7cdcb81d5.png)

**Hardware and Software Configuration**
- OS: Ubuntu 20.04
- OpenVINO installed in Anaconda

Please let me know what I shall modify so that I could fix the error.
Thanks!

**Comment by samet-akcay** [comment]
Hi @pyhow, can you check your torchvision version? We noticed this issue couple of days ago when we used the most recent torchvision version. Now we have the following in the [base](https://github.com/openvinotoolkit/anomalib/blob/development/requirements/base.txt#L9-L11) requirements?

```
torchmetrics>=0.9.0,<=0.9.1
torchvision>=0.9.1,<=0.12.0
torchtext>=0.9.1,<=0.12.0
```
Can you double check this and let us know?

**Comment by pyhow** [comment]
Hi @samet-akcay, 

Changing the versions have solved my problem.
Thanks for your help!
