### ISSUE TITLE
Add plots and additional metrics

### ISSUE THREAD

**Issue by ORippler** [openvinotoolkit/anomalib#420]
**Is your feature request related to a problem? Please describe.**
Imo, it would be nice to have:

* Pixel-wise AUPR + PRO until 30% FPR as metrics
* Plots with baselines where applicable for all metrics (ROC-Curve, PR-Curve, PRO-Curve)

**Describe the solution you'd like**
  1. Add/implement appropriate torchmetric classes, and add them to the `AnomlibMetricCollection`
  2. Add callbacks which access the underlying scores for metric calculation (i.e. tuple of tpr/fpr for auroc) and which subsequently use the scores to generate and save the plots.
      * Alternatively, one could think of expanding/inheriting the `VisualizerCallback`

Thoughts?

**Comment by ashwinvaidya17** [comment]
@ORippler I think segregating `ImageVisualizerCallback` and `MetricVisualizerCallback` might be a cleaner approach. Let me know what are your thoughts on that.

Also, just to break down your issue here is a list to capture it. Feel free to suggest any modifications.

- [ ] Add AUPR metrics
- [ ] Add PRO metrics
- [ ] Add visualizer for plotting the underlying scores in each metrics

**Comment by ORippler** [comment]
> @ORippler I think segregating `ImageVisualizerCallback` and `MetricVisualizerCallback` might be a cleaner approach. Let me know what are your thoughts on that.
> 
> Also, just to break down your issue here is a list to capture it. Feel free to suggest any modifications.
> 
>     * [ ]  Add AUPR metrics
> 
>     * [ ]  Add PRO metrics
> 
>     * [ ]  Add visualizer for plotting the underlying scores in each metrics

Sure we can split up the Callbacks, but then I suggest inheriting from a `VisualizerCallbackBase`.

**Comment by samet-akcay** [comment]
> Sure we can split up the Callbacks, but then I suggest inheriting from a VisualizerCallbackBase

Sure, this separation should cause minimal duplication.
