### ISSUE TITLE
STFPM loss

### ISSUE THREAD

**Issue by AlessandroPolidori** [openvinotoolkit/anomalib#421]
https://github.com/openvinotoolkit/anomalib/blob/64296d21d027fce3e002c1cee0452ff66c5ad71c/anomalib/models/stfpm/lightning_model.py#L75

Hi, i'm not grasping what is this **loss_val**. It seems to me that it's always zero. Could you please explain what is its purpose?

**Comment by samet-akcay** [comment]
I'll fix it then close it
