### ISSUE TITLE
Why there are two configs parameters?

### ISSUE THREAD

**Issue by alevangel** [openvinotoolkit/anomalib#433]
**Describe the bug**
I see that for each model there are 2 yaml files. One located in `./configs/model/<file.yaml>`, and the other in `./anomalib/models/<model>/<file.yaml>`

**To Reproduce**
The first config file if used generates some errors of missing keys
`!python train.py --model reverse_distillation --config configs/model/reverse_distillation.yaml`

```  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key dataset
    full_key: dataset
    object_type=dict
```

I'm referring to the develop branch, up to date.

**Comment by samet-akcay** [comment]
@alevangel, the ones in `./configs` are for the new CLI, which is in beta at the moment. This is stated at the top of each new config files. For example for reverse distillation;
https://github.com/openvinotoolkit/anomalib/blob/development/configs/model/reverse_distillation.yaml#L3

**Comment by samet-akcay** [comment]
if you want to use the new config to use reverse distillation you need to run 

`anomalib fit --config ./config/model/reverse_distillation.yaml`

**Comment by alevangel** [comment]
@samet-akcay I see. Thank you for the comment!
