### ISSUE TITLE
Error for multiple gpu training

### ISSUE THREAD

**Issue by udasinnayan** [openvinotoolkit/anomalib#436]
In the config file trainer part, if I set `auto_select_gpus: true` and `devices: 2`, I got an error like
`AttributeError: Can't pickle local object 'FeatureExtractor.get_features.<locals>.hook'`, it comes from this line `trainer.fit(model=model, datamodule=datamodule)` in `anomalib/tools/train.py` script but for single GPU it works without an error. Any comments about this error / is it possible to use multiple GPUs for training and testing?

**Comment by ashwinvaidya17** [comment]
Hi @udasinnayan that's a known issue. This might probably be solved when me move towards torchfx but the only option is to use single GPU for now.

**Comment by samet-akcay** [comment]
@ashwinvaidya17, I'm wondering if this is the case even when we use `timm`'s feature extractor
