### ISSUE TITLE
Improve Codacy Results.

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#438]
Codacy shows number of issues. Address the following items to improve the codacy results.

- [ ] Configure pylint for codacy.
- [ ] Configure pydocstyle for codacy.
- [ ] Add markdownlint to the repo (pre-commit)
- [ ] Add shellcheck to the repo (pre-commit)

**Comment by djdameln** [comment]
@samet-akcay this has been implemented right? Can we close this issue?
