### ISSUE TITLE
Calculate detection AUROC from anomaly map

### ISSUE THREAD

**Issue by Howeng98** [openvinotoolkit/anomalib#445]
Great contribution to the community, appreciate that !!

Is it possible to get the detection performance from the anomaly map (segmentation)? I mean like the way that get the top k highest anomaly score in the anomaly map and calculate the mean of them as the threshold for decide as anomaly or not.

Is there any misunderstanding or something that I miss about this kind of way to calculate detection performance instead of calculate with label (1,0) ?

Because I observe that most of the flow-based model (e.g. FastFlow, CSFlow, CFlow-AD) have a better performance in segmentation than the detection.
Is it because it's flow-based (generative-based) model so it have a better behavior in pixel level?

Do you use any way to calculate segmentation performance? (is the anomalib/utils/metrics/adaptive_threshold.py decide the threshold of the anomaly map?)

----------------------------

Besides that, do you have any more reference about the addtional dataset (small dataset) for us to evaluate the model performance? (for example, the color hazelnut dataset you had used as an example for demo how to train model with customize dataset tutorial)

Thanks!

**Comment by samet-akcay** [comment]
> Is it possible to get the detection performance from the anomaly map (segmentation)? I mean like the way that get the top k highest anomaly score in the anomaly map and calculate the mean of them as the threshold for decide as anomaly or not.
>
> Is there any misunderstanding or something that I miss about this kind of way to calculate detection performance instead of calculate with label (1,0) ?

@Howeng98, the way performance is evaluated varies based on each algorithm. For example, here is how the performance of [PatchCore](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/patchcore/anomaly_map.py#L50-L62) is computed. If the model doesn't have a specific method to compute the anomaly score, [AnomalyModule](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/components/base/anomaly_module.py#L155-L158) automatically computes the performance. The performance of the flow-based algos are, for example, computed based on this. This could potentially be tuned to improve the detection performance. 

> Is it because it's flow-based (generative-based) model so it have a better behavior in pixel level?

The penultimate layer of each model outputs values in a different range, which could impact the computation. 

---

> Do you use any way to calculate segmentation performance? (is the anomalib/utils/metrics/adaptive_threshold.py decide the threshold of the anomaly map?)

At the end of a validation step in  [AnomalyModule](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/components/base/anomaly_module.py#L120-L121), [adaptive threshold](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/utils/metrics/adaptive_threshold.py) is computed for image and pixel level. Based on this threshold value, metrics are computed.
