### ISSUE TITLE
PatchCore  inference

### ISSUE THREAD

**Issue by Vvdinosaur** [openvinotoolkit/anomalib#448]
when inference, patchcore model need "memory_bank" to compute distance ,which is used in models/patchcore/torch_model.py, line 158:
distances = torch.cdist(embedding, self.memory_bank, p=2.0)
I think I should save it when train,and use it when inference...but how i save it and how to use it?

**Comment by wskdhr** [comment]
Hi!,I just got the same issue,
could you please share how you solved this?

**Comment by samet-akcay** [comment]
Hi, `memory_bank` is part of the `TorchModel` [here](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/patchcore/torch_model.py#L56).

When the model weights are loaded, the memory bank is loaded as well.
