### ISSUE TITLE
inference speed

### ISSUE THREAD

**Issue by ke-dev** [openvinotoolkit/anomalib#459]
**Describe the solution you'd like**
  - A clear and concise description of what you want to happen.
HI, developers, when I want to use lightgning_inference to test the inference speed of a single image, I find that it takes a lot of time, is it because of the dataloaders? How should I improve the inference speed, can you give me some advice?
**Additional context**
  - Add any other context or screenshots about the feature request here.
The code I use to test the speed is
    ``` python
    start = time.time()
    trainer.predict(model=model, dataloaders=[dataloader])
    print(time.time() - start)

**Comment by samet-akcay** [comment]
@ke-dev we have just merged [`TorchInferencer`](https://github.com/openvinotoolkit/anomalib/blob/development/tools/inference/torch_inference.py) back, which performs pure torch inference. You could perhaps check it out?

**Comment by ke-dev** [comment]
> @ke-dev we have just merged [`TorchInferencer`](https://github.com/openvinotoolkit/anomalib/blob/development/tools/inference/torch_inference.py) back, which performs pure torch inference. You could perhaps check it out?

Thank you so much, this is very helpful to me.
