### ISSUE TITLE
Error for image_size

### ISSUE THREAD

**Issue by J-byte-cloud** [openvinotoolkit/anomalib#461]
**Describe the bug**
- When I set image_size to 39 in yaml files, ganomaly、fastflow、draem、dfm、cflow, these algorithms will get errors and can't run.

**To Reproduce**
1. Set image_size to 39 in dataset of yaml file.
2. Run code 
3. See error

**Hardware and Software Configuration**
- OS: Win 10

**Additional context**
- It's worth mentioning that these  errors of algorithms are different. Is this a bug? Is there any way to set image_size as 39?
- this is my yaml setting:
dataset:
  name: mvtec#options: [mvtec, btech, folder]
  format: folder
  path: xxx
  abnormal_dir: xxx
  normal_test_dir:  xxx
  task: classification
  mask: null
  extensions: null
  split_ratio: null #0.2
  image_size: 39
  train_batch_size: 8
  test_batch_size: 32
  num_workers: 0
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

**Comment by samet-akcay** [comment]
@J-byte-cloud, did you solve this issue?

**Comment by samet-akcay** [comment]
Ganomaly expects an input size that is a power of 2. You could therefore use 32x32 or 64x64 images.

DFM, Fastflow, Cflow models use a CNN backbone such as ResNet, which are trained using image sizes of 224 or 256. I'm not sure if a size of 39 would be handled properly by the backbones. Padding could potentially address, but I feel like there would be some issues that silently fail.

**Comment by J-byte-cloud** [comment]
Thanks,I'll try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/anomalib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月11日(星期四) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/anomalib] Error for image_size (Issue #461)





 
Ganomaly expects an input size that is a power of 2. You could therefore use 32x32 or 64x64 images.
 
DFM, Fastflow, Cflow models use a CNN backbone such as ResNet, which are trained using image sizes of 224 or 256. I'm not sure if a size of 39 would be handled properly by the backbones. Padding could potentially address, but I feel like there would be some issues that silently fail.
