### ISSUE TITLE
train.py got error on metrics AUROC.

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/anomalib#463]
When I run train.py on custom metrics
python tools/train.py --config .../config.yaml
I got the error.
```
Exception has occurred: ValueError
No samples to concatenate
  File "F:\abc\anomalib\utils\metrics\auroc.py", line 50, in _compute
    fpr, tpr, _thresholds = super().compute()
  File "F:\abc\anomalib\utils\metrics\auroc.py", line 59, in generate_figure
    fpr, tpr = self._compute()
  File "F:\abc\anomalib\utils\callbacks\visualizer\visualizer_metric.py", line 53, in on_test_end
    fig, log_name = metric.generate_figure()
  File "F:\abc\tools\train.py", line 65, in train
    trainer.test(model=model, datamodule=datamodule)
  File "F:\abc\tools\train.py", line 69, in <module>
    train()
```
How to fix it?

**Comment by ORippler** [comment]
> No samples to concatenate

Did you assign `pixel` metrics in your `config.yml` without providing segmentation masks for your custom problem?

**Comment by nguyenanhtuan1008** [comment]
Ah, so I need to provide segmentation masks for it. Thank you for your answer!
Anyway, what is the rule for segmentation masks directory will be?

**Comment by ORippler** [comment]
You can just disable the metric/remove it from your config if you don't have segmentation masks.

Regarding the required config keys for datasets, refer the [readme](https://github.com/openvinotoolkit/anomalib#custom-dataset)

**Comment by nguyenanhtuan1008** [comment]
OK. I understood. Thank you!
