### ISSUE TITLE
How to run openvino inferencer?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/anomalib#485]
I set the config file to:
```
optimization:
  openvino:
    apply: true
```
and then I got the .json and .onnx model file.
After that, I install the package for openvino by following requirements/openvino.txt file. but when I run the openvino_inference.py I got the error:

```
Exception has occurred: ImportError
DLL load failed while importing ie_api: The specified module could not be found.
  File "F:\anomaly\anomalib\deploy\inferencers\openvino_inferencer.py", line 31, in <module>
    from openvino.inference_engine import (  # type: ignore  # pylint: disable=no-name-in-module
  File "F:\anomaly\anomalib\deploy\inferencers\__init__.py", line 18, in <module>
    from .openvino_inferencer import OpenVINOInferencer
```
How to fix this issue?

**Comment by ashwinvaidya17** [comment]
@nguyenanhtuan1008 What is your python version?

**Comment by nguyenanhtuan1008** [comment]
> @nguyenanhtuan1008 What is your python version?

@ashwinvaidya17 My python version is 3.8.13.

**Comment by ashwinvaidya17** [comment]
I am not able to reproduce the issue on my end. There might be an issue with the path/virtual environment. Can you check if `ie_api.so` exists in your python environment at this location `<install-path>/lib/python3.8/site-packages/openvino/inference_engine`?

**Comment by nguyenanhtuan1008** [comment]
> I am not able to reproduce the issue on my end. There might be an issue with the path/virtual environment. Can you check if `ie_api.so` exists in your python environment at this location `<install-path>/lib/python3.8/site-packages/openvino/inference_engine`?

I'm using anaconda, and I just checked out that there is no ie_api.so in my env path. I see only ie_api.pyd is there.

**Comment by ashwinvaidya17** [comment]
@nguyenanhtuan1008 If reinstalling `openvino` from pypi does not work then I would suggest that you download the runtime from this link https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html

**Comment by nguyenanhtuan1008** [comment]
I back to python 3.7, installed all independency packages along with openvino, and it's working. I think need to update the new list package for installing openvino.
Thank you so much for your support. @ashwinvaidya17
