### ISSUE TITLE
Can the produced model.onnx use in the c++ inference?

### ISSUE THREAD

**Issue by DeepSpace98** [openvinotoolkit/anomalib#486]
Great works.Now I want to let the Patchcore's onnx model use in the C++  inference, but I find it is diffcult, can you teach me how to begin it?

**Comment by ashwinvaidya17** [comment]
@DeepSpace98 Thanks for your interest but C++ inference is outside the purview of this repository. You can try looking into onnx documentation or you can try adapting `openvino_inference.py` for C++ by using OpenVINO's C++ API. These docs might help https://docs.openvino.ai/latest/openvino_inference_engine_samples_hello_classification_README.html
