### ISSUE TITLE
In the classification task, the predicted results of pixel segmentation are expected to give

### ISSUE THREAD

**Issue by code10086web** [openvinotoolkit/anomalib#489]
It is hoped that in the classification task, the prediction of pixel segmentation can be given when tested. What should I do?

**Comment by samet-akcay** [comment]
@code10086web, can you elaborate a bit please?

**Comment by code10086web** [comment]
> 

For example， In a custom dataset, Since there is no pixel-level labelling, I set the task option to classification task instead of segmentation task. so during the inference phase, I can only get the result of whether the image is anomalous or not, and cannot know the result of where the anomalous area is roughly. But the predicted results of pixel-level are not given.

**Comment by code10086web** [comment]
Could you give me some tips? Thank you very much.

**Comment by dominikgraf** [comment]
@code10086web You need to give a mask for the ground truth as far as I know. You could augment your dataset and create your own anomalous images and save a mask for the augmented area. I hope this is what you meant.

**Comment by code10086web** [comment]
Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samet ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 晚上10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openvinotoolkit/anomalib] In the classification task, the predicted results of pixel segmentation are expected to give (Issue #489)





 
@code10086web, here is the link how the visualization images are generated. When there is no masks, anomalib treats it as a classification task, and only generates the predicted labels. You could potentially add
 visualization.add_image(image_result.heat_map, "Predicted Heat Map")  
to here in L125.

**Comment by samet-akcay** [comment]
Closing this issue, thinking it's resolved now. Feel free to re-open if there are further issues.
