### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by zuowanggithub** [openvinotoolkit/anomalib#505]
How do you convert the algorithm to onnx for model deployment?(eg. Padim)

**Comment by ashishbdatta** [comment]
Since applying the OpenVINO optimization will generate an `.onnx` file you could this to your config:

```yaml
optimization:
  openvino:
    apply: true
```

The `ONNX` file should be saved near your model weights folder. 

I am creating a #509 PR to make this export more generic. You could also pull from top of `main` branch once it is merged.

**Comment by zuowanggithub** [comment]
> Since applying the OpenVINO optimization will generate an `.onnx` file you could add this to your config:
> 
> ```yaml
> optimization:
>   openvino:
>     apply: true
> ```
> 
> The `ONNX` file should be saved near your model weights folder.
> 
> I am creating a #509 PR to make this export more generic. You could also pull from top of `main` branch once it is merged.
