### ISSUE TITLE
How to get label and score without the image for classification task?

### ISSUE THREAD

**Issue by pierrebedu** [openvinotoolkit/anomalib#507]
Hi,

Thanks for that great lib !
The models work fine on my own dataset but i'm struggling to analyse the results.

I only can get the results (anomalous or normal) written on an image located in the "output repo".
This is not what i need.

 I would like a csv (or file of some sort) with the names of the images and the results ( that's useful for inference on a big batch)

Maybe there is a config option that i am missing. (tutorial notebooks are quite limited on this aspect and i don t understand the contributors documentation )

Thanks !

**Comment by dominikgraf** [comment]
You could write a custom script to only get the prediction score and prediction label for a dataset and an existing model.
Take a look at `anomalib/tools/inference/torch_inference.py` for the basic structure and `anomlib/deploy/inferencers/base_inferencer.py > Inferencer > predict` which returns:

```python
return ImageResult(
            image=image_arr,
            pred_score=output["pred_score"],
            pred_label=output["pred_label"],
            anomaly_map=output["anomaly_map"],
            pred_mask=output["pred_mask"],
        )
```

You could then do something like this:
```python
from anomalib.deploy import TorchInferencer

def get_args():
    ...

if __name__ == '__main__':
    args = get_args()
    inferencer = TorchInferencer(config=args.config, model_source=args.weights)

    for image in args.batch:
        predictions = inferencer.predict(image=image)
        pred_score = predictions.pred_score
        pred_label = predictions.pred_label
        # ...
        # save to csv

```
Hope that helps.

**Comment by pierrebedu** [comment]
thanks for your answer ! ;)

I am trying to use the pytorch lightning inferencer (in my understanding, the torch inferencer is no longer supported) so i had a hard time implementing that.

I succeed in adding a "save to csv" script in the post_processingvisualizer.py

Thanks again

**Comment by samet-akcay** [comment]
Thanks @dominikgraf for your answer.

@pierrebedu, `torch_inferencer.py` is still supported.

I'm closing this issue, assuming that the issue has been resolved. Feel free to re-open if you still encounter issues.
