### ISSUE TITLE
patchcore subsample_embedding is very slow

### ISSUE THREAD

**Issue by Vvdinosaur** [openvinotoolkit/anomalib#533]
Hi,
I have 2000+ images( img_size = 360x640) to train, it is very slow at subsample_embedding stage.
is there any method to accelerate this ?

**Comment by samet-akcay** [comment]
@Vvdinosaur, until we optimize the code, you could perhaps reduce the number of layers you are extracting. For example, you could only extract the features from 'layer3'. You could potentially play with `coreset_sampling_ratio` and `num_neighbors` parameters to improve the computation as well.
