### ISSUE TITLE
ONNX inference and TENSORRT optimisation

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#600]
I would like to run Padim AD on a jetson nano on a live feed. When i use torch_inference, it works but its too slow (4s per image for prediction). 
After analysis, i saw that the GPU was not being used at all. 
To give enough initialization time, I even ran the script for 20 times. (it reduced the inference time from 25 sec to 4 sec). 
I would like to know how to perform fast inference on jetson nano using the scripts provided or do I need to do something else to activate the GPU?

**Comment by ashwinvaidya17** [comment]
@shrinand1996 Thanks for reporting this bug. The quickest workaround your can use for now is to move the model to GPU after this line https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/deploy/inferencers/torch_inferencer.py#L86 and move the image to gpu before passing it to the model https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/deploy/inferencers/torch_inferencer.py#L119

**Comment by shrinand1996** [comment]
@ashwinvaidya17 how to do that?

**Comment by ashwinvaidya17** [comment]
@shrinand1996 can you try this

```python
def load_model(self, path: Union[str, Path]) -> AnomalyModule:
        """Load the PyTorch model.
        Args:
            path (Union[str, Path]): Path to model ckpt file.
        Returns:
            (AnomalyModule): PyTorch Lightning model.
        """
        model = get_model(self.config)
        model.load_state_dict(torch.load(path)["state_dict"])
        model.eval()

        return model.to("cuda")

def forward(self, image: Tensor) -> Tensor:
        """Forward-Pass input tensor to the model.
        Args:
            image (Tensor): Input tensor.
        Returns:
            Tensor: Output predictions.
        """
        return self.model(image.to("cuda")
```

**Comment by samet-akcay** [comment]
@ashwinvaidya17, maybe we could consider adding `device` to `TorchInferencer`?

**Comment by shrinand1996** [comment]
Thank you for your reply.
I tried this and it run without errors. But, the inference became much slower. If i didnt specify cuda, it was around 3 sec per image. But with cuda, it is taking a whooping 130s. 
What could be causing this?

**Comment by shrinand1996** [comment]
Pytorch Version: 1.12.0a0+git67ece03
OS: Ubuntu 20.04
Hardware: Jetson Nano
CUDA version: 10.2.300
cuDNN: 8.2.1.32

Code:
import warnings
import skimage
from argparse import ArgumentParser, Namespace
from pathlib import Path
 
from anomalib.data.utils import (
   generate_output_image_filename,
   get_image_filenames,
   read_image,
)
from anomalib.deploy import TorchInferencer
from anomalib.post_processing import Visualizer
import time
config_path= "custom/config.yaml"
weights='custom/model.ckpt'
save_path='test_results'
inferencer = TorchInferencer(config=config_path, model_source=weights)
visualizer = Visualizer(mode="simple", task="segmentation")


filenames = get_image_filenames(path="custom/images")
for filename in filenames:
       image = read_image(filename)
       start=time.time()
       predictions = inferencer.predict(image=image)
       end= time.time()
       output = visualizer.visualize_image(predictions)
       print(end-start)
       if save_path:
           file_path = generate_output_image_filename(input_path=filename, output_path=save_path)
           visualizer.save(file_path=file_path, image=output)

I did not use the PR. I made the changes that you suggested on the previous comments.

**Comment by ashwinvaidya17** [comment]
@shrinand1996 What's your image dimensions?

**Comment by shrinand1996** [comment]
I just uploaded the config file as well. The image size is 512

**Comment by shrinand1996** [comment]
Hello, this works on colab but i dont see a major difference in cpu vs gpu computing. Since Padim by nature is big,i guess jetson nano gpu will not be sufficient for it. 
But why is padim so slow? Even on a good gpu, 2 fps is quite low.

Which anomaly detection model is best for real time detection? (>25 fps)?

**Comment by dominikgraf** [comment]
@shrinand1996 FastFlow with ResNet18 backbone is at 30.8 FPS according to their paper. But it is slow as well with the anomalib implementation somehow. I tested it on a 2070 super and a 3060. I try to use it for real time anomaly detection too.

**Comment by SimonB97** [comment]
@shrinand1996 
hi, i'm trying to do the same, predict on a jetson nano. 

would you mind telling me how you even got cuda to work with anomalib on the jetson? it would be very helpful if you could tell me which python version, pytorch/pytorch-lightning+gpu wheel/version, linux and anomalib version you used!

Thank you in advance!
