### ISSUE TITLE
ERROR: No matching distribution found for torchmetrics<=0.9.3,>=0.9.1

### ISSUE THREAD

**Issue by gloomyfish1998** [openvinotoolkit/anomalib#606]
**Hardware and Software Configuration**

- OS: [Windows 10 64bit]
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.0]
- CUDNN Version [e.g. v8.x]
- TensorRT8.4.x
- Pytorch1.7 +cu110
- OpenVINO Version [Optional e.g. v2022.1]
- Python3.6.5

**Additional context**
D:\python\anomalib-0.3.6>pip install -e .
Obtaining file:///D:/python/anomalib-0.3.6
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement torchmetrics<=0.9.3,>=0.9.1 (from anomalib) (from versions: 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0rc0, 0.6.0rc1, 0.6.0, 0.6.1, 0.6.2, 0.7.0rc0, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc0, 0.8.0, 0.8.1, 0.8.2)
ERROR: No matching distribution found for torchmetrics<=0.9.3,>=0.9.1

================================================================
i got no matching installation package issue when i try to run the library install script , any workaround/? or not support window os at all , please advice for me!!!!
thanks in advance~~~~

**Comment by ashwinvaidya17** [comment]
@gloomyfish1998 can you upgrade your python version to 3.7? `torchmetrics` 0.9.1 and above require `python>=3.7`. You can have a look here https://pypi.org/project/torchmetrics/0.9.1/

**Comment by ashwinvaidya17** [comment]
I am closing this issue as the minimum python version for Anomalib is 3.7
