### ISSUE TITLE
Inference Too slow

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#608]
I was testing the padim model with custom dataset and the inference seems very slow even on google colab. It takes around .5 sec per image which doesnt add up.
Given since padim is lightweight and using resnet18 only, the inference should be super fast..

**Comment by ashwinvaidya17** [comment]
Are you using the TPU or GPU instance? Here is my colab notebook and you can see that inference is faster on gpu when using the GPU instance. https://colab.research.google.com/drive/143FEAt86yzmVHT-xzP21PW6FslfAElBs?usp=sharing. Also, I am closing this issue as it seems related to https://github.com/openvinotoolkit/anomalib/issues/600. So let's continue our discussion there.
