### ISSUE TITLE
Cflow too slow

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#612]
in the paper, they explain why cflow is faster than other AD methods and is smaller. But, the inference speed is super slow even on a gpu(0.6s per image) and the model size is around 900MB. 

I tried to optimise it for openvino but was unable to do so because of an error:
/usr/local/lib/python3.7/dist-packages/anomalib/models/cflow/torch_model.py:110: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if batch_num < (fiber_batches - 1):
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/content/anomalib/results/cflow/NMF/model.onnx
	- Path for generated IR: 	/content/anomalib/results/cflow/NMF/openvino
	- IR output name: 	model
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/usr/local/lib/python3.7/dist-packages/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Concat): Concat_177>':
Check 'concat_axis < this_input_rank.get_length() && concat_axis >= 0' failed at core/src/op/concat.cpp:63:
While validating node 'v0::Concat Concat_3495 (onnx::Shape_729[0]:i64{3}, Constant_109[0]:i64{}) -> (dynamic...)' with friendly_name 'Concat_3495':
Concatenation axis (0) is out of bounds [0, -1] for argument 1, which has shape {}.

[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/usr/local/lib/python3.7/dist-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/usr/local/lib/python3.7/dist-packages/openvino/tools/mo/main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/usr/local/lib/python3.7/dist-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 147, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: While validating ONNX node '<Node(Concat): Concat_177>':
Check 'concat_axis < this_input_rank.get_length() && concat_axis >= 0' failed at core/src/op/concat.cpp:63:
While validating node 'v0::Concat Concat_3495 (onnx::Shape_729[0]:i64{3}, Constant_109[0]:i64{}) -> (dynamic...)' with friendly_name 'Concat_3495':
Concatenation axis (0) is out of bounds [0, -1] for argument 1, which has shape {}.

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
Traceback (most recent call last):
  File "tools/train.py", line 71, in <module>
    train()
  File "tools/train.py", line 60, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 211, in run
    output = self.on_run_end()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/fit_loop.py", line 322, in on_run_end
    self.trainer._call_callback_hooks("on_train_end")
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/anomalib/utils/callbacks/export.py", line 49, in on_train_end
    export_mode=self.export_mode,
  File "/usr/local/lib/python3.7/dist-packages/anomalib/deploy/optimize.py", line 71, in export_convert
    assert os.system(optimize_command) == 0, "OpenVINO conversion failed"
AssertionError: OpenVINO conversion failed
Epoch 2: 100%|██████████| 2/2 [03:50<00:00, 115.08s/it, image_F1Score=1.000, image_AUROC=1.000]

**Comment by samet-akcay** [comment]
We also notice that Cflow is slow. Our code is based on the official Cflow code base. For model specific questions, I would recommend creating an issue on the original repo.

When I check the FPS using the code snippet provided here: I get the following:
Efficient AD: 223.08 FPS
CFlow: 3.93

These numbers are based on NVIDIA 3090 GPU.

In regards to the openvino conversion issue, I think it has been fixed, so you could convert the torch model to openvino ir format.

I'm closing this issue. Feel free to re-open if you are still having issues. Cheers!
