### ISSUE TITLE
Inference speed is model agnostic

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#613]
All models end up with fps of around 2 on a google colab GPU.
Even if algorithms like cflow, fastflow are lightweight, the fps doesnt seem to get effected by the model type. 

The issue is same with lightning inference or torchinference

**Comment by ashwinvaidya17** [comment]
Closing as this is currently removed from v1.0 and will be introduced with refactor. https://github.com/openvinotoolkit/anomalib/issues/2054
