### ISSUE TITLE
Multi-GPU Code Crash

### ISSUE THREAD

**Issue by raviy0807** [openvinotoolkit/anomalib#618]
**Training pipeline crashed when using 2 gpu V100 GCP machine after 3 epochs without any warning or log**

- My training data consist of 800k image which i try to train Ganomaly and FastFlow. Both of the architecure crashed after 3 epoch on gcp. 

After 3 epoch, i received "killed python 2292"

1. Create docker Image as per the repo
2. Make 800k image dataset
3. Trigger this GCP ML job on V100 2 GPUs 

**Expected behavior**

- I tried changing the batchsize
- Validation percentage
- Pin memory for data loader
- Trainer option to auto scale batch
- Disable validation (didn't work)

**Hardware and Software Configuration**

- OS: [Ubuntu 20, DOCKER]
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.4]
- CUDNN Version [e.g. v11.4.120]
- OpenVINO Version [Optional e.g. v2021.4.2]

**Comment by ashwinvaidya17** [comment]
@raviy0807 it might be related to this https://github.com/openvinotoolkit/anomalib/discussions/641
