### ISSUE TITLE
Patchcore & Fastflow onnx/ov export fails

### ISSUE THREAD

**Issue by pmudgal-Intel** [openvinotoolkit/anomalib#631]
**Describe the bug**
Training patchcore or fastflow model fails if export is configured as "Openvino"
python tools/train.py --config anomalib/models/patchcore/config.yaml
In anomalib/models/patchcore/config.yaml file, change export option as "openvino"

Screenshot is attached showing the error. Seems like model is getting trained, but fails to export as onnx.
torch version - 1.11.0+cu102

**Screenshots**

![image](https://user-images.githubusercontent.com/48809925/195666940-16ea3b76-c0d9-4cae-86a3-5babe4be0eca.png)

**Hardware and Software Configuration**

- OS: [Ubuntu, 20.04]
- NVIDIA Driver Version [470.141.03]
- CUDA Version [e.g. 10.2]
- CUDNN Version [e.g. V10.2.89]
- OpenVINO Version [Optional e.g.v2022.1.0]

**Comment by samet-akcay** [comment]
@ashwinvaidya17, should we consider replacing `cdist` by default?

**Comment by ashwinvaidya17** [comment]
Since this is a recurring question I think it makes sense to replace the function. We can explore the performance difference first.

**Comment by pmudgal-Intel** [comment]
Patchcore works fine with torch 1.12, but fastflow still shows same error during export.

**Comment by samet-akcay** [comment]
With the latest anomalib version, PatchCore and FastFlow models can be converted to ONNX and OpenVINO models. I'm now closing this issue. Thanks!
