### ISSUE TITLE
onnx Infer problem?

### ISSUE THREAD

**Issue by montensorrt** [openvinotoolkit/anomalib#638]
**Is your feature request related to a problem? Please describe.**
when infer the onnx model,don‘t find meta_data.json file?
if i want infer onnx,must be using openvino libs?
maybe provide some scripts for onnx model infer ,such as using **onnxruntime** infer? or other?

**Comment by samet-akcay** [comment]
Hi @montensorrt, PR #636 addresses this issue. We hope to be able to merge it by the end of today. Hope that answers your question.

**Comment by montensorrt** [comment]
it's solved，but have a lit problem,why must to export_mode == "openvino",the meta_data.json file would be created,when I only export_mode == "onnx“，the file wondn't created,maybe ,should adjust the order,
Such as:
    torch.onnx.export(
        model.model,
        torch.zeros((1, 3, height, width)).to(model.device),
        onnx_path,
        opset_version=12,
        input_names=["input"],
        output_names=["output"],
    )

    with open(Path(export_path) / "meta_data.json", "w", encoding="utf-8") as metadata_file:
        meta_data = get_model_metadata(model)
        # Convert metadata from torch
        for key, value in meta_data.items():
            if isinstance(value, Tensor):
                meta_data[key] = value.numpy().tolist()
        json.dump(meta_data, metadata_file, ensure_ascii=False, indent=4)

    if export_mode == "openvino":
