### ISSUE TITLE
[refactor] `enum.Enum` vs. strings and ints

### ISSUE THREAD

**Issue by jpcbertoldo** [openvinotoolkit/anomalib#644]
*I didn't follow the issue templates because this is a refactor, there is no bug or new feature associated.* 

There are many string constants and ints out there, and enums started to be used (for instance in #572).

I think it would be nice to clean up those constants with enums to make the code clearer.

---

Example: the labels normal/anomalous are ints 0/1 respec. 

One will find raw 0/1 in the depths of the code, which is fine when you know what it means, but some authors will define normal/anomalous as 1/0 actually, which creates confusion and you may take a while to realize it.

**Comment by samet-akcay** [comment]
Thanks @jpcbertoldo, good point!

**Comment by WenjingKangIntel** [comment]
anomalib_Team3 working on this
