### ISSUE TITLE
Refactor: Modify all callbacks to return `AnomalyModule` instead of `pl_module`

### ISSUE THREAD

**Issue by ashwinvaidya17** [openvinotoolkit/anomalib#65]
Ensure that all callbacks return `AnomalyModule` instead of `pl_module`. Otherwise we have to use `cast` statements. Eg-
`compress.py` uses `pl_module = cast(AnomalyModule, pl_module)` to placate mypy. This should be changed to ensure that we always pass `AnomalyModule`.

**Comment by samet-akcay** [comment]
I think this issue could be more generic to address all the callbacks, which should `AnomalyModule` instead of `pl_module`
