### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by ANTZ314** [openvinotoolkit/anomalib#656]
**ImportError**

- Running the Colab workbook: Following step by step,
- After successful compilation of the default (PaDiM) model is trained, 
- I'm getting the following error on both "tools/inference/lightning_inference.py" inferencers:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Predicting DataLoader 0: 100% 1/1 [00:00<00:00,  3.23it/s]
```

**To Reproduce**

Follow the Google Colab steps provided, inference throws an error?

<a href="https://colab.research.google.com/drive/1K4a4z2iZGBNhWdmt9Aqdld7kTAxBfAmi?usp=sharing" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> by [@bth5](https://github.com/bth5)

**Expected behavior**

- Successful inference & anomaly detection

**Hardware and Software Configuration**

- Standard Google Colab + GPU

**Comment by ANTZ314** [comment]
**NOTE**
I've noticed that although command [1] throws an error, it still produces the heatmapped anomaly image in the results direcotory, whereas command [2] does not produce any results. The only difference is the argumnet "--visualization_mode full".

**Command [1]**
```
!python tools/inference/lightning_inference.py \
    --config anomalib/models/padim/config.yaml \
    --weights results/padim/mvtec/bottle/weights/model.ckpt \
    --input datasets/MVTec/bottle/test/broken_large/013.png \
    --output test_result
```

**Command [2]**
```
!python tools/inference/lightning_inference.py \
    --config anomalib/models/padim/config.yaml \
    --weights results/padim/mvtec/bottle/weights/model.ckpt \
    --input datasets/MVTec/bottle/test/good/012.png \
    --output test_result \
    --visualization_mode full
```

**Comment by ashwinvaidya17** [comment]
Sorry, I missed this. This might be a similar to this issue https://github.com/openvinotoolkit/anomalib/issues/749. I am closing this. Free free to re-open in case that solution does not work for you.
