### ISSUE TITLE
Datamodules Refactor

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#681]
Changes to be made to the datamodules [feature branch](https://github.com/openvinotoolkit/anomalib/tree/feature/datamodules) before merging into main.

- [x] Create and implement new design for modules in `anomalib/data`.
- [x] https://github.com/openvinotoolkit/anomalib/issues/646
- [x] Add synthetic validation set functionality.
- [x] Remove `PreProcessor` class and use raw transforms instead.
- [x] https://github.com/openvinotoolkit/anomalib/issues/680
- [x] Use enum for task type
- [x] https://github.com/openvinotoolkit/anomalib/pull/732
- [x] Allow custom val/test split ratio (see https://github.com/openvinotoolkit/anomalib/issues/731)

**Comment by jpcbertoldo** [comment]
https://github.com/openvinotoolkit/anomalib/pull/634 one more down here, no?

**Comment by djdameln** [comment]
Yep, getting there. We're working on the last item, but we might decide to address it in a separate PR to main to speed up merging the feature branch.
