### ISSUE TITLE
I only have normal pictures  Diagram without defects

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#686]
I only have normal pictures

Diagram without defects

What should the configuration file do

```
  normal_dir: OK # name of the folder containing normal images.
  abnormal_dir: NULL # name of the folder containing abnormal images.
  normal_test_dir: NULL  # name of the folder containing normal test images.
```

Model Type: Classification

What model should I choose

**Comment by innat** [comment]
You may need some bad samples.

**Comment by samet-akcay** [comment]
@monkeycc, it's unfortunately not possible with the current version. We are currently working on it in [this feature branch](https://github.com/openvinotoolkit/anomalib/tree/feature/datamodules). It may not be super stable, but you might want to try it out if you don't want to wait for it to be merged into the main.

There is already an issue for this here #277, so closing this one. Feel free to continue the discussion there.
