### ISSUE TITLE
Add pipeline training and inference Patchcore UI

### ISSUE THREAD

**Issue by vnk8071** [openvinotoolkit/anomalib#721]
I have already build a pipeline for training and inferencing Patchcore model on website. I want to contribute my pipeline for everyone can use it to quickly demo. Where folder can I create pull request in anomalib repo?

My pipeline Github: https://github.com/vnk8071/anomaly-detection-in-industry-manufacturing

With training:
- User can add custom dataset from zip file with MVTec format
- I use default backbone Resnet 18 and Patchcore model (Can be add more backbones and models)
- I created 2 custom datasets for training.

With inference:
- I have already training in MVTec dataset with 3 categories: Hazelnut, Metal Nut and Grid.
- 3 outputs: Anomaly score, target label and show heatmap on UI

I hope my pipeline can contribute to anomalib open-source.

**Comment by vnk8071** [comment]
@ashwinvaidya17 I would like to be assigned and can see my repo.

**Comment by ashwinvaidya17** [comment]
@vnk8071 That's a great pipeline you have build using anomalib! It is nice that you support training as well. One comment is that using only patchcore is a bit limiting. You can have a look at this script https://github.com/openvinotoolkit/anomalib/blob/main/tools/inference/gradio_inference.py. Maybe you can extend your `app.py` to something similar here so that you can support more models. You can then create a PR to replace the `gradio_inference.py`. It might need some refactor but we can discuss that in the PR comments.

**Comment by vnk8071** [comment]
Thank you for the reply. I will refactor the code with more backbones and models like https://github.com/openvinotoolkit/anomalib/blob/main/tools/inference/gradio_inference.py and maybe create folder name example in tools. Because I use Flask API and the app.py link with each part together and really hard to break them. How you feel with my idea? @ashwinvaidya17

**Comment by ashwinvaidya17** [comment]
Not sure if I understand what you mean. What does app.py link with?

**Comment by vnk8071** [comment]
My app.py link with database when user training (weight of model ) and output of inference. And with Flask, it links with templates and static folder and structure of code when I break down them from one file.

**Comment by ashwinvaidya17** [comment]
Ah in that case we can always have a folder named `gradio_inference` with the relevant files and a README to get started.

**Comment by vnk8071** [comment]
Oki I will refactor code follow structure of gradio_inference.py and create PR for discuss details.  Thank you for your time answer @ashwinvaidya17
