### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by seanko29** [openvinotoolkit/anomalib#730]
**Describe the bug**

Hello. First of all, thank you for the awesome library. 
I am having RuntimeError: Tensors must be CUDA and dense when I use multiple-gpu on DDP.
I change gpu settings in the trainer in config.yaml as stated below.
I am also trying to train the models on custom dataset. I guess this is not the problem that causes runtime error on cuda (not sure...).

I am trying to run on 4 titan RTXs 

Thank you in advanced!

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

- A clear and concise description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/72428646/203646711-3ca5adca-c0c0-4282-b1ee-ae9e9f026325.png)

- If applicable, add screenshots to help explain your problem.

**Hardware and Software Configuration**

- OS: [Ubuntu, OD] Ubuntu
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.4] CUDA 10.2
- CUDNN Version [e.g. v11.4.120]
- OpenVINO Version [Optional e.g. v2021.4.2]

**Additional context**

- Add any other context about the problem here.

dataset:
  name: cect
  format: folder
  path: /home/data/anolib_cect
  normal_dir: normal # name of the folder containing normal images.
  abnormal_dir: abnormal # name of the folder containing abnormal images.
  normal_test_dir: test # name of the folder containing normal test images.
  task: classification # classification or segmentation
  mask: null #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.

**Comment by seanko29** [comment]
> To use multiple GPUs you have to remove all the `cpu()` calls in `AnomalyModule` (anomalib/models/components/base/anomaly_module.py). Note: this will also lead to higher gpu usage as all the metrics will remain on the gpu. Also, in case of padim you have to remove the `cpu` call from line 82 of the `lightning_module.py`. `self.embeddings.append(embedding.cpu())` to `self.embeddings.append(embedding)`

Thank you for the answer @ashwinvaidya17 !! 
Just a follow up question: Aside from padim, do i have to remove stuffs in the lightningmodule for other models as well? (I guess I have to find those stuffs manually?)

Thank you again :)

**Comment by ashwinvaidya17** [comment]
@seanko29 sorry for the late reply. 
1. Yes the `train.py` creates and trains the lightning module. You can have a look at the `devices` flag under the `trainer` section in `config.yaml`. It is set to 1 by default. If you want to train it on multiple GPUs you can increase this number to match the number of GPUs on your system. Since `devices` is set to 1, changing `CUDA_VISIBLE_DEVICES` will not have any effect. I would suggest you stick to only using this flag from the config.
2. I haven't experimented with all the models so some may require removing some operations that move the tensor to CPU.

**Comment by jyothish-automi** [comment]
> To use multiple GPUs you have to remove all the `cpu()` calls in `AnomalyModule` (anomalib/models/components/base/anomaly_module.py). Note: this will also lead to higher gpu usage as all the metrics will remain on the gpu. Also, in case of padim you have to remove the `cpu` call from line 82 of the `lightning_module.py`. `self.embeddings.append(embedding.cpu())` to `self.embeddings.append(embedding)`

@ashwinvaidya17 , does the following parameter in the yaml config file(under trainer) help without modifying anything in the code?
move_metrics_to_cpu: false
