### ISSUE TITLE
Changing ratio for create_validation_set

### ISSUE THREAD

**Issue by seanko29** [openvinotoolkit/anomalib#731]
**Describe the bug**

Good evening. I have a small newbie question when using the library. 
Whenever we use custom dataset (or simply mvtec), 
`create_validation_set
`
is set True which the test set is divided into 50/50 for validation and test set respectively. Is there any way to change this ratio?
For example, if I have 1,000 test images, I want to use 300 for validation and 700 for test images. 

Also, if I reduce the split ratio of 0.2 to lets say 0.05 (5%) , will this small percetange work as well for splitting normal set for test set? 

Thank you in advanced.

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

- A clear and concise description of what you expected to happen.

**Screenshots**

![image](https://user-images.githubusercontent.com/72428646/203780709-1bad10e6-2320-4beb-b83a-d94a7b1954f9.png)

**Hardware and Software Configuration**

- OS: [Ubuntu, OD] Ubuntu
- NVIDIA Driver Version [470.57.02]
- CUDA Version [e.g. 11.4] 10.2
- CUDNN Version [e.g. v11.4.120]
- OpenVINO Version [Optional e.g. v2021.4.2]

**Additional context**

- Add any other context about the problem here.

**Comment by djdameln** [comment]
Currently, it is not possible to change the val/test split ratio from the default value of 0.5. However, we are currently working on a major [refactor of the datamodules](https://github.com/openvinotoolkit/anomalib/issues/681), so we could consider adding a configurable parameter for your use case. We will investigate the possibility and post any updates here.

**Comment by seanko29** [comment]
> Currently, it is not possible to change the val/test split ratio from the default value of 0.5. However, we are currently working on a major [refactor of the datamodules](https://github.com/openvinotoolkit/anomalib/issues/681), so we could consider adding a configurable parameter for your use case. We will investigate the possibility and post any updates here.

Thank you for your effort :) !

**Comment by seanko29** [comment]
> Currently, it is not possible to change the val/test split ratio from the default value of 0.5. However, we are currently working on a major [refactor of the datamodules](https://github.com/openvinotoolkit/anomalib/issues/681), so we could consider adding a configurable parameter for your use case. We will investigate the possibility and post any updates here.

Thank you for your effort 👍

**Comment by djdameln** [comment]
Merged to feature branch in https://github.com/openvinotoolkit/anomalib/pull/760
