### ISSUE TITLE
[Bug]: torchmetrics.functional.auc deprecated

### ISSUE THREAD

**Issue by Anurag-Shah** [openvinotoolkit/anomalib#750]
### Describe the bug

Needs to be replaced with torchmetrics.utilities.compute.auc

Affects following files:

- anomalib/utils/metrics/aupr.py
- anomalib/utils/metrics/aupro.py
- anomalib/utils/metrics/auroc.py

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

Just try to run any dataset on a fresh install (in a fresh conda environment).

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

There should not be a runtime error when importing the auc function

### Screenshots

N/A

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpcbertoldo** [comment]
@ashwinvaidya17 

How much effort would it be?
Just wondering.

Another suggestion: as this will be corrected, maybe could we rename the classes in 

```
anomalib/utils/metrics/aupr.py
anomalib/utils/metrics/auroc.py
```

To something that does not shadow torchmetrics? 
It's a bit confusing to have `AUROC(ROC)` while you find exactly the same thing in tochmetrics -- maybe `AnomalibAUROC`?

**Comment by Anurag-Shah** [comment]
I made these edits myself when running the github locally. It's just changing the name of the import, from 
"from torchmetrics.functional import auc"
to
"from torchmetrics.utilities.compute import auc"

Not really any work at all. 

But yes, as mentioned, the version change also breaks the CLI and I didn't try to fix that. I used the tools/train.py and didn't need to make any other edits to get it to work besides this. Didn't think about downgrading my torchmetrics version lol

**Comment by ashwinvaidya17** [comment]
@jpcbertoldo like @Anurag-Shah mentioned just changing the import does not work. There are a few more places where we have to make changes. I haven't investigated it thoroughly but for now we have fixed the torchmetrics version to 0.10.3 in this PR https://github.com/openvinotoolkit/anomalib/pull/754.
Renaming the classes is a good idea. We will discuss it when we upgrade the torchmetrics version.

**Comment by jpcbertoldo** [comment]
> ... the version change also breaks the CLI and I didn't try to fix that.

I was referring to this in the "how much effort".

> I haven't investigated it thoroughly ...

Ok, :+1: !

> Renaming the classes is a good idea. We will discuss it when we upgrade the torchmetrics version.

Yes, please :pray: ! : )

**Comment by ashwinvaidya17** [comment]
Closing as this will be addressed by https://github.com/openvinotoolkit/anomalib/pull/1879
