### ISSUE TITLE
Training with Custom Data segmentation

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#772]
`https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html`

This tutorial is a single classification tutorial
Not segmentation tutorial

Hazelnut_toy:
```

  ├── NG
      ├── colour
      │  ├── 00.jpg
      │  ├── 01.jpg
      ├── crack
      │  ├── 00.jpg
      │  ├── 01.jpg

├── good
│  ├── 00.jpg
│  ├── 01.jpg


└── mask
      ├── colour
      │  ├── 00.jpg
      │  ├── 01.jpg
      ├── crack
      │  ├── 00.jpg
      │  ├── 01.jpg

```

```

# Replace the dataset configs with the following.
dataset:
name: hazelnut
format: folder
path: ./datasets/Hazelnut_toy
normal_dir: good # name of the folder containing normal images.
abnormal_dir: NG# name of the folder containing abnormal images.
mask: mask         #mask
normal_test_dir: null # optional
task: segmentation # classification or segmentation
```

My error
I don't know what the problem is
Didn't understand the tutorial

**Comment by djdameln** [comment]
If you want to train with the segmentation task type, you will have to provide pixel-level annotations for your anomalous images (the `mask` parameter should point to the file system location where the annotations are stored). These annotations are used for evaluation, and to compute the optimal value of the anomaly score threshold. If you don't have pixel-level annotations available for your anomalous data, you can set the task type to classification during training, and then change it to segmentation before running [inference](https://openvinotoolkit.github.io/anomalib/tutorials/inference.html#pytorch-lightning-inference).

**Comment by djdameln** [comment]
Ah, I understand your problem now. In this case you will have to test your model on each of the anomalous categories separately. The `abnormal_dir` and `mask` keywords both expect a single folder of image data. So nested structures are not allowed. In your case, you could first evaluate on the `colour` category, using the following config:

```
  normal_dir: good
  abnormal_dir: colour
  mask: mask/colour
```

Then, you could evaluate on the `crack` category using the following config:

```
  normal_dir: good
  abnormal_dir: crack
  mask: mask/crack
```

Alternatively, you could merge the images from the two anomalous categories together in a single folder. Just make sure that you change the file names from one of the categories to prevent duplicates, and make sure the files in your mask folder follow the same naming convention.

We are currently working on a major re-design of the data modules, and we will look into the possibility of making the Folder dataset a bit better suited to read anomalous images from multiple sources.

**Comment by djdameln** [comment]
A fix has been provided in https://github.com/openvinotoolkit/anomalib/pull/784. It's now on a feature branch, but it will be merged to the main branch soon and it will be included in the next release. Closing this issue for now.
