### ISSUE TITLE
Custom Data segmentation  Easier conversion mask ?

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#785]
Custom Data segmentation  Easier conversion mask ?

The labelme conversion script does not know how to convert to the required mask format

```
img = Image.open("*.PNG")
image_L = img_as_ubyte(img)
mask_dst = np.uint8(image_L) * 255
out_mask = Image.fromarray(mask_dst)
out_mask.save(*.jpg)
```

Whether my conversion script conforms to the mask?

**Comment by djdameln** [comment]
Hi, could you provide us with some details about your problem, and how it's related to Anomalib? We don't recognize the code snippet in your question as our code.

**Comment by monkeycc** [comment]
labelme
```
1.jpg
1.json
2.jpg
2.json
```

How to convert mask

```
| mask
| -- 1.jpg
| --2.jpg
```

**Comment by djdameln** [comment]
We really can't answer your question if you don't provide some more background information about your problem.

Please list clearly what you are trying to achieve, and which steps you already tried. If you are using any external tools, please provide a link to the (documentation of the) tool so that we are aware of the context.

You could have a look at the following page which gives some pointers on how to ask good questions: https://stackoverflow.com/help/how-to-ask.

**Comment by monkeycc** [comment]
Sorry English is not good
I'll rearrange the process
I'm a novice

Step 1
Labelme
```
| -- 1.jpg
| -- 1.json
| -- 2.jpg
| -- 2.json
```

Demand mask
How to convert mask
`https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html`
`task: segmentation`

Step 2
Pseudo color map     Convert Monochrome
`labelme\examples\instance_segmentation\data_dataset_voc\SegmentationClassPNG`
![2011_000003](https://user-images.githubusercontent.com/6490927/209038350-a9f27ee8-2e69-4da6-9658-d7af16ac76a2.png)
```
img = Image.open("*.PNG")
image_L = img_as_ubyte(img)
mask_dst = np.uint8(image_L) * 255
out_mask = Image.fromarray(mask_dst)
out_mask.save(*.jpg)
```
![2011_000003](https://user-images.githubusercontent.com/6490927/209038539-2e69c1c3-9a9f-47a8-b39a-1c5d6e835802.jpg)

I'm sorry I didn't find the tutorial
can only do this

**Comment by djdameln** [comment]
If I understand your question correctly, you are trying to run Anomalib with ground truth masks generated using an external tool. From the examples images you posted, I believe you are using this tool to create the masks: https://github.com/wkentaro/labelme.

The masks used by Anomalib are expected to be binary images with ones for anomalous pixels, and zeros for non-anomalous pixels. The example image you provided (the last one) should work fine. Just make sure that the images in the masks folder have the same file names as the corresponding images in the anomalous folder. So, for example:

```
dataset
├── anomalous
│  ├── 00.jpg
│  ├── 01.jpg
│  ...
├── masks
│  ├── 00.jpg
│  ├── 01.jpg
│  ...
└── good
│  ...
...
```

You could then use the following configuration for the `dataset` section of your `config.yaml` to train a model and evaluate using the provided mask files.

```
dataset:
  name: name-of-your-dataset
  format: folder
  path: <path-to-your-dataset>
  normal_dir: good
  abnormal_dir: anomalous
  task: segmentation
  mask: masks
  normal_test_dir: null
  ...
```

**Comment by monkeycc** [comment]
Thank you for your answer
The data set can be trained normally
