### ISSUE TITLE
[Task]: I CAN'T USE GPU

### ISSUE THREAD

**Issue by chelsea456** [openvinotoolkit/anomalib#792]
### What is the motivation for this task?

When i install lib anomalib, pytorch install pytorch cpu

### Describe the solution you'd like

When i install lib anomalib, pytorch install pytorch cpu

**Comment by nixczhou** [comment]
you install cpu pytorch, thats why you can't use gpu

**Comment by chelsea456** [comment]
> you install cpu pytorch, thats why you can't use gpu

no, i installed pytorch gpu, but when i run pip install anomalib, it uninstall my pytorch gpu and after install pytorch cpu. I don't kinow what happend

**Comment by nixczhou** [comment]
hi i think you can try to local install. Don't know about your environment you are using. But these command let you setup from clean conda env. 

```
yes | conda create -n anomalib_env python=3.8
conda activate anomalib_env
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .
```

**Comment by nixczhou** [comment]
and make sure you have gpu driver installed too in your computer

**Comment by chelsea456** [comment]
I use cuda 11.6, card gtx 3060 12gb

Vào Th 5, 15 thg 12, 2022 lúc 21:48 Nico Zhou ***@***.***> đã
viết:

**Comment by thanh-repo** [comment]
Run this code to remove torch and update torchgpu.
```
pip uninstall -y torch torchvision torchtext
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by chelsea456** [comment]
Tks bạn nha

Vào Th 3, 20 thg 12, 2022 lúc 08:27 Nguyen Thanh Dat <
***@***.***> đã viết:

**Comment by ashwinvaidya17** [comment]
We cannot automatically install the right torch + cuda version from `setup.py`. As @thanh-repo mentioned, the best approach is to uninstall torch and reinstall the version you require.
