### ISSUE TITLE
Resize bug in inference

### ISSUE THREAD

**Issue by QQR1** [openvinotoolkit/anomalib#83]
- When input the width and height of the image are not equal, sizes of input arguments that do not match will occur

Line 152 in  ./anomalib/deploy/inferencers/torch.py should be `anomaly_map = cv2.resize(anomaly_map, (meta_data["image_shape"][1], meta_data["image_shape"][0]))`

meta_data["image_shape"] is (image_width, image_height)  
-# cv2.resize(img, (image_height，image_width ),interpolation=cv2.INTER_CUBIC)

**Comment by samet-akcay** [comment]
Thanks @QQR1! Good catch!

**Comment by raviv** [comment]
@QQR1  Did you manage to train when width and height of the image are not equal?
I'm getting an error in `anomaly_module.validation_epoch_end()`

**Comment by raviv** [comment]
@samet-akcay No, I'm getting an error while training, not inference.
You can easily reproduce by setting image size in config.yaml to something like below and trying to train

  image_size:
    - 512
    - 256

**Comment by samet-akcay** [comment]
which algorithm is this? Patchcore?

**Comment by raviv** [comment]
@samet-akcay PADIM

**Comment by samet-akcay** [comment]
Thanks, we'll reproduce the issue, and give you an update here.

**Comment by djdameln** [comment]
@raviv https://github.com/openvinotoolkit/anomalib/pull/135 should solve the `image_size` problems for both training and inference for most models. Patchcore and GANomaly still do not allow changing the image size, but this will be addressed separately, see https://github.com/openvinotoolkit/anomalib/issues/136 and https://github.com/openvinotoolkit/anomalib/issues/40.

**Comment by raviv** [comment]
@djdameln got latest dev branch and the fix @QQR1 suggested is not there.
Training works but inference fails on the original bug in this thread (resizing anonmaly map)

**Comment by djdameln** [comment]
@raviv Sorry, I misinterpreted the original post and thought the problem was for non-square `image_size` parameter in the `config.yaml`. I implemented the fix suggested by @QQR1 in a new PR https://github.com/openvinotoolkit/anomalib/pull/140.

**Comment by samet-akcay** [comment]
@raviv PR #140 has now been merged, and the issue should be fixed. Feel free to re-open it if you think there is still an issue
