### ISSUE TITLE
[Bug]: FileNotFoundError in notebook

### ISSUE THREAD

**Issue by amrzv** [openvinotoolkit/anomalib#833]
### Describe the bug

Hi.
A `FileNotFoundError` raises when running `001_getting_started.ipynb` notebook in colab:
![image](https://user-images.githubusercontent.com/36787333/211607578-905e8d49-bd77-4bbf-8b9d-8dcfaa040f41.png)

Probably there should be
`git clone https://github.com/openvinotoolkit/anomalib.git`
at the very beginning of notebook.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

"Run all cells" in colab notebook
https://colab.research.google.com/github/openvinotoolkit/anomalib/blob/main/notebooks/000_getting_started/001_getting_started.ipynb#scrollTo=tqeuctWkwHgR

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Config file exists.
In colab possible solution is to edit this cell:
`CONFIG_PATH = f"/usr/local/lib/python3.8/dist-packages/anomalib/models/{MODEL}/config.yaml"`

### Pip/GitHub

pip

### Configuration YAML

```yaml
-
```

### Logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@amrzv, thanks for spotting this! You are right! Since the installation is done via pip, config files cannot be found in the specified directory. Installing the library from source would be a better choice in this case. 

We'll fix this asap!

**Comment by samet-akcay** [comment]
Alternatively, you could also create a PR if you want to become a contributor

**Comment by amrzv** [comment]
Looks like you got over it quickly on your own.
