### ISSUE TITLE
[Bug]: Crop in SSPCAB implementation

### ISSUE THREAD

**Issue by YRChen1998** [openvinotoolkit/anomalib#839]
### Describe the bug

The crop of SSPCAB in Anomalib is 2 * (kernel_size + dilation)，but the official implementation's crop is kernel_size + 2*dilation + 1
[https://github.com/ristea/sspcab/blob/main/sspcab_torch.py](url)

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

--

### OS information

--

### Expected behavior

--

### Pip/GitHub

pip

### Configuration YAML

```yaml
--
```

### Logs

```shell
--
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@YRChen1998, thanks for reporting this issue. @djdameln, is this intentional? If not, @YRChen1998 would you like to create a PR to contribute to the repo?

**Comment by isaacncz** [comment]
hi @djdameln @YRChen1998 , if there's no one creating the PR, anomalib_Team4 would like to work on this.
