### ISSUE TITLE
Patchcore export onnx fails (maybe)

### ISSUE THREAD

**Issue by hsysfan** [openvinotoolkit/anomalib#841]
![image](https://user-images.githubusercontent.com/13518370/212621385-feb03676-dbf4-4e74-905e-e2cdfe7f8dba.png)

Hello, i am researcher about computer vision.

I wanna use patchcore with onnxruntime in c# program.

I have something problem in using .onnx model file

The uploaded image is my exported onnx model. but i think it is not completed exporting to onnx.

So, i cant understand output structure, 529 in outputs.

Could you explain about Reshapeoutput_dim_0 ~ 3 and Name 529 ?

I already saw the issue ([https://github.com/openvinotoolkit/anomalib/issues/653](https://github.com/openvinotoolkit/anomalib/issues/653)).

Thank you.

**Comment by samet-akcay** [comment]
Closing this as #1267 addressed the issue.
