### ISSUE TITLE
Anomalib Colab Test.ipynb error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#850]
When I ran Anomalib Colab Test.ipynb on Google Colab, the following error occurred.

```
!python tools/train.py --config anomalib/models/padim/config.yaml

Traceback (most recent call last):
  File "tools/train.py", line 19, in <module>
    from anomalib.data.utils import TestSplitMode
ImportError: cannot import name 'TestSplitMode' from 'anomalib.data.utils' (/usr/local/lib/python3.8/dist-packages/anomalib/data/utils/__init__.py)
```

**Comment by samet-akcay** [comment]
If you install the latest anomalib on your colab, you should not see this error. To install the latest anomalib, you could run the following:
```bash
!git clone https://github.com/openvinotoolkit/anomalib.git
%cd anomalib
%pip install -e .
```

**Comment by Ishihara-Masabumi** [comment]
This notebook is from your current https://github.com/openvinotoolkit/anomalib.

**Comment by Ishihara-Masabumi** [comment]
At the beggining, I ran the following command as you instructed.

```
!git clone https://github.com/openvinotoolkit/anomalib.git
%cd anomalib
%pip install -e .
```

Then I tried to run the train.py, another error has occurred.

```
!python tools/train.py --config anomalib/models/padim/config.yaml

Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from anomalib.config import get_configurable_parameters
ModuleNotFoundError: No module named 'anomalib'
```

**Comment by samet-akcay** [comment]
Please check if you have properly create your [virtual environments](https://github.com/openvinotoolkit/anomalib#local-install) and install anomalib based on the instructions in the readme file.

**Comment by Ishihara-Masabumi** [comment]
I'd like to make sure that I passed the following commands.

```
!pip install anomalib
!pip install -r openvino.txt
```

Is this right?

**Comment by samet-akcay** [comment]
This issue has been resolved with the new release. You could either install anomalib via `pip install anomalib==0.4.0rc1`, or install from source to get the latest changes.

I'm closing this issue. Feel free to re-open if you still have this issue.

**Comment by Ishihara-Masabumi** [comment]
Thanks. It's OK.
