### ISSUE TITLE
[Bug]: BTech PyTorch Lightning DataModule Catch 22 - not automatically downloading / preparing dataset

### ISSUE THREAD

**Issue by stillgreyfox** [openvinotoolkit/anomalib#873]
### Describe the bug

Working with `anomalib/notebooks/100_datamodules/101_btech.ipynb`

Can't get it to create a datamodule if the dataset isn't already installed.

It chokes when instantiating a `BTech(AnomalibDataModule)` while in the superclass constructor, it tries to create a BTechDataset, which raises a RuntimeException when it doesn't find files.

This presents a catch-22 problem, because the auto-download `prepare_data(self)` function is an instance method of the BTech class, but with no instance, no calling :(

### Dataset

BTec

### Model

N/A

### Steps to reproduce the behavior

See above

### OS information

OS information:
- OS: Ubuntu 20.04
- Python version: 3.8
- Anomalib version: 0.3.7 git
- PyTorch version: 1.12.0
- CUDA/cuDNN version: 11.6
- GPU models and configuration: GeForce RTX 3070ti
- Any other relevant information: N/A

### Expected behavior

It should download the dataset and prepare it as described in the function BTech.prepare_data(self)

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 11
      1 btech_datamodule = BTech(
      2     root="../../datasets/BTech",
      3     category="01",
   (...)
      9     normalization=InputNormalizationMethod.NONE,
     10 )
---> 11 btech_datamodule.setup()

File /notebooks/gh/anomalib/anomalib/data/base/datamodule.py:102, in AnomalibDataModule.setup(self, stage)
     96 """Setup train, validation and test data.
     97 
     98 Args:
     99   stage: str | None:  Train/Val/Test stages. (Default value = None)
    100 """
    101 if not self.is_setup:
--> 102     self._setup(stage)
    103 assert self.is_setup

File /notebooks/gh/anomalib/anomalib/data/base/datamodule.py:118, in AnomalibDataModule._setup(self, _stage)
    115 assert self.train_data is not None
    116 assert self.test_data is not None
--> 118 self.train_data.setup()
    119 self.test_data.setup()
    121 self._create_test_split()

File /notebooks/gh/anomalib/anomalib/data/base/dataset.py:161, in AnomalibDataset.setup(self)
    159 """Load data/metadata into memory."""
    160 if not self.is_setup:
--> 161     self._setup()
    162 assert self.is_setup, "setup() should set self._samples"

File /notebooks/gh/anomalib/anomalib/data/btech.py:186, in BTechDataset._setup(self)
    185 def _setup(self) -> None:
--> 186     self.samples = make_btech_dataset(path=self.root_category, split=self.split)

File /notebooks/gh/anomalib/anomalib/data/btech.py:85, in make_btech_dataset(path, split)
     81 samples_list = [
     82     (str(path),) + filename.parts[-3:] for filename in path.glob("**/*") if filename.suffix in (".bmp", ".png")
     83 ]
     84 if not samples_list:
---> 85     raise RuntimeError(f"Found 0 images in {path}")
     87 samples = pd.DataFrame(samples_list, columns=["path", "split", "label", "image_path"])
     88 samples = samples[samples.split != "ground_truth"]

RuntimeError: Found 0 images in ../../datasets/BTech/01
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stillgreyfox** [comment]
Want to make the prepare_data() function not need an instance, it currently uses it's instance-ness to get the root location and the category to check if files are there.

Any suggesstions for properly generalizing?

Also, when I have the dataset manually installed, it doesn't call prepare_data(), which would be nice, because it compresses all the .bmp's into .png.

I'm still new to (Pytorch) Lightning, so would it get called somehow later, besides at the creation of the BTech DataModule? Think it should be called regardless? at least the auto-convert / compress part would be nice to do if it isn't detected as having been done.

**Comment by djdameln** [comment]
Hi, thanks for reporting. The signature of the `prepare_data` method is defined by the `LightningDataModule` base class, and it is called by the PyTorch Lightning Trainer to ensure the dataset is properly installed before creating the dataloaders, so we don't want to make this method static and change its signature.

You are correct in observing that the notebook fails when the dataset has not been previously installed, but I believe the solution is much simpler. We can just add the call to `prepare_data` before calling `setup`, and this should ensure that the dataset is installed properly before we create the samples dataframe and apply the subset splitting. I will push a fix for this.

> Also, when I have the dataset manually installed, it doesn't call prepare_data(), which would be nice, because it compresses all the .bmp's into .png.

This is a good point, we could separate the download and compression functionality within the `prepare_data` method to accommodate cases where the dataset was previously installed manually.

**Comment by stillgreyfox** [comment]
Thanks for the quick fix! Tested and it's good!

One typo was in the MVTec notebook, copy paste monster left "BeanTech" instead of MVTec, can make a PR if you want, or let you handle.

**Comment by samet-akcay** [comment]
Thanks @stillgreyfox, I'm closing this issue now.
