### ISSUE TITLE
Switch to hard permutation.

### ISSUE THREAD

**Issue by danielsoy** [openvinotoolkit/anomalib#89]
Hey There!

Who can help me to modify : all_in_one_block.py script
to avoid this warning, to happen:

C:\Users\libro\AppData\Local\Programs\Python\Python38\lib\site-packages\FrEIA\modules\all_in_one_block.py:123: UserWarning: Soft permutation will take a very long time to initialize with 2048 feature channels. Consider using hard permutation instead.
  warnings.warn(("Soft permutation will take a very long time to initialize "

I would like to switch to hard permutation mode, but i dont know how to do it.

Thank you so much.

**Comment by alexriedel1** [comment]
It's defined in the CFlow Backbone https://github.com/openvinotoolkit/anomalib/blob/f1c8a6b553b82a8974ccc9fd27aa5f9b939d5917/anomalib/models/cflow/backbone.py#L98

**Comment by samet-akcay** [comment]
We could maybe set this as a configurable parameter [here](https://github.com/openvinotoolkit/anomalib/blob/f1c8a6b553b82a8974ccc9fd27aa5f9b939d5917/anomalib/models/cflow/model.py#L143). @blakshma can you comment on this?

**Comment by danielsoy** [comment]
It worked! Thanks again.
