### ISSUE TITLE
load image folder

### ISSUE THREAD

**Issue by laborer123** [openvinotoolkit/anomalib#890]
https://github.com/openvinotoolkit/anomalib/blob/d963e01fe6730ee63229d5759b90f59b219d4445/anomalib/data/utils/image.py#L40
Maybe this needs to be changed to the previous one  “len(image_filenames) == 0”

**Comment by samet-akcay** [comment]
@laborer123,  thanks. This has been fixed with the new release. Please update your branch. 
https://github.com/openvinotoolkit/anomalib/blob/2ae212358aed6e4e9f7dd200db9886d8730ebce7/anomalib/data/utils/image.py#L40-L41
