### ISSUE TITLE
Always reorder auc inputs after upgrading to pytorch 1.9.x

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#92]
In the [AUROC](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/core/metrics/auroc.py) metric computation, we should ideally always reorder the inputs. Currently the [lack of support](https://github.com/pytorch/pytorch/issues/28871) for [stable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability) sorting in pytorch 1.8.1 prevents us from doing so (more detailed explanation [here](https://github.com/openvinotoolkit/anomalib/pull/90#issuecomment-1024299093)). Stable sorting was added in pytorch 1.9.0, so once we upgrade our requirements to that version, we should be able to always reorder the inputs using the `stable=True` option of `torch.sort()`.

**Comment by ashwinvaidya17** [comment]
Closing as the current workaround works and this change is blocked by the downstream tasks.
