### ISSUE TITLE
[Task]: Add CIFAR-10 dataset

### ISSUE THREAD

**Issue by ashwinvaidya17** [openvinotoolkit/anomalib#963]
### What is the motivation for this task?

Add CIFAR-10 dataset to allow fast prototyping.

### Describe the solution you'd like

Implement a dataloader for CIFAR 10.

**Comment by sahilpmehra** [comment]
Hi @ashwinvaidya17 I want to work on one of the anomalib related project ideas for GSoC'23 and would like to work on this task to familiarize myself. Could you assign this task to me?

**Comment by samet-akcay** [comment]
Thanks for your interest @sahilpmehra!
