### ISSUE TITLE
[Task]: Implement Kolektor dataset

### ISSUE THREAD

**Issue by ashwinvaidya17** [openvinotoolkit/anomalib#964]
### What is the motivation for this task?

Add Kolektor dataset: https://www.vicos.si/resources/kolektorsdd/

### Describe the solution you'd like

Implement dataloader to support Kolektor dataset.

**Comment by Ravindu987** [comment]
Hi

I'm interested in contributing to Anomalib through GSoC. I've completed the prerequisite task on openvino notebooks and did the [PR](https://github.com/openvinotoolkit/openvino_notebooks/pull/931) .

I've been going through Anomalib and I'd like to do this task to get a deeper understanding.

**Comment by samet-akcay** [comment]
Hi @Ravindu987, thanks for your interest. Yeah, if you confirm, I could assign this task to you. 
Basically the implementer needs to implement a `make_kolektor_dataset` function that creates a `pd.DataFrame` containing all of the necessary data information such as `image_path`, `label`, `mask_path` etc. The next step is to implement `KolektorDataset` and finally `Kolektor` lightning datamodule. For more examples, you could have a look at [MVTecAD](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/mvtec.py), [BTech](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/btech.py) and [Folder](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/folder.py) datasets, which are based on ImageData

**Comment by Ravindu987** [comment]
> Hi @Ravindu987, thanks for your interest. Yeah, if you confirm, I could assign this task to you. Basically the implementer needs to implement a `make_kolektor_dataset` function that creates a `pd.DataFrame` containing all of the necessary data information such as `image_path`, `label`, `mask_path` etc. The next step is to implement `KolektorDataset` and finally `Kolektor` lightning datamodule. For more examples, you could have a look at [MVTecAD](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/mvtec.py), [BTech](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/btech.py) and [Folder](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/folder.py) datasets, which are based on ImageData

Thank you for the info . Please assign this to me. I'll work on it in the next couple of days.

**Comment by Ravindu987** [comment]
Hi @samet-akcay 
I've been following up on this and went through the examples. There's a thing I want to clarify.
`Kolektor` dataset doesn't provide labels such as good/bad. It provides images with their respective masks. There are 52 images with defects but they aren't specified and have to be manually found. In this case is it ok to omit `label` from Dataframe. The alternative is to run a script with hardcoded image names to label them but it doesn't seem a good practice.

**Comment by Ravindu987** [comment]
@samet-akcay 
I developed a workaround for the above issue. Implemented a function to analyze masks and label images 'Good'/'Bad' on the runtime. Please inform me whether this follows your guidelines.
With that I completed the `make_kolektor_dataset` function along with `KolektorDataset` and `Kolektor` module.

I made the PR #983 under the WIP tag. If you give the green light on the above scenario, I'll complete the other formalities such as docstrings.

You can reach me at ravindu.19@cse.mrt.ac.lk . If you want we can take a quick meet to discuss this.

**Comment by samet-akcay** [comment]
Hi @Ravindu987, Thanks for creating a PR for this! I'll have a look at the PR and let you know.

**Comment by Ravindu987** [comment]
Thanks @samet-akcay . In the meantime I have a small question regarding GSoC. I had my eyes on project number 8 in the project list. I'm very much interested in this and studied and completed my prerequisite task and made the [PR](https://github.com/openvinotoolkit/openvino_notebooks/pull/908) 2 weeks ago. Since then I studied `Anomalib` and made this PR as well.
I saw that another applicant is applying for project number 8. Though I'm more than prepared to learn and complete the task to my best, he has more experience since I'm still doing my bachelor's degree.
In this context I'm thinking of applying to another project because I want to be realistic and apply to a project that I have a better shot at. 
Can you please offer me some insight on this whether to apply for another project in OpenVino or continue with project 8.

Also I have the proposal prepared. Shall I send it to you for a review.

**Comment by samet-akcay** [comment]
Hi @Ravindu987,

While we can't guarantee acceptance into any particular project, it's always a good idea to explore other projects that might be a good fit for your skills and interests. If you're concerned that your experience might not be enough to secure the position, it might be worth considering other projects that you might be well-suited for.

I recommend checking out Project 6 or 7 on the project list as possible alternatives. If you're interested in these projects, you can certainly send over your proposal for review. If you want to have a look at other non-anomalib OpenVINO projects, you could contact those mentors.

Best of luck with your GSoC application! Let me know if you have any other questions or concerns

**Comment by Ravindu987** [comment]
> Hi @Ravindu987,
> 
> While we can't guarantee acceptance into any particular project, it's always a good idea to explore other projects that might be a good fit for your skills and interests. If you're concerned that your experience might not be enough to secure the position, it might be worth considering other projects that you might be well-suited for.
> 
> I recommend checking out Project 6 or 7 on the project list as possible alternatives. If you're interested in these projects, you can certainly send over your proposal for review. If you want to have a look at other non-anomalib OpenVINO projects, you could contact those mentors.
> 
> Best of luck with your GSoC application! Let me know if you have any other questions or concerns

Thank you for your input Samet. I'll surely look into those projects as well. After thinking about this I thought of applying to project 8 and another project if I find one suitable.

Please let me know how to send the proposal. If I need to email please send me your address.

Also don't hesitate to contact me regarding issues of the PR. After you review and we finalize the implemented logic, I'll finish the code formatting and self-checks.

**Comment by Ravindu987** [comment]
Hi @samet-akcay Please let me know how to submit the proposal.
