### ISSUE TITLE
[Task]: how to export patchcore ckpt model to onnx type

### ISSUE THREAD

**Issue by ccsself** [openvinotoolkit/anomalib#968]
### What is the motivation for this task?

how to export patchcore ckpt model to onnx type

**Comment by blaz-r** [comment]
Hello,
you should add 
```yaml
optimization:
  export_mode: onnx
```
To config.yaml

**Comment by ccsself** [comment]
OK  Many Thanks  It works   , by the way , the onnx  model  can't work it  at  NX platform ？

**Comment by blaz-r** [comment]
Good to hear that it works :). I don't understand your question though, but according to the issue I linked, onnx model might not work, but you can try and report back if it does work for you.

**Comment by ccsself** [comment]
i
