### ISSUE TITLE
[Bug]: Cannot export fastflow model to ONNX

### ISSUE THREAD

**Issue by xiaoyunwei** [openvinotoolkit/anomalib#982]
### Describe the bug

When exporting a FastFlow model, the following error occurs.

![image](https://user-images.githubusercontent.com/20653516/227787869-6fce11c0-ff90-4bd2-84de-776975a01eb5.png)

torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_convolution_mode' to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

### Dataset

MVTec

### Model

FastFlow

### Steps to reproduce the behavior

1. set: config.optimization.export_mode = "onnx"
2. In the end of training, exporting to onnx will cause the error above

### OS information

OS information:
- OS: Windows 11
- Python version: 3.9.13
- Anomalib version: 0.4
- PyTorch version: 2.0
- CUDA/cuDNN version: 11.7
- GPU models and configuration: GeForce RTX 3070

### Expected behavior

ONNX model exported

### Pip/GitHub

pip

### Configuration YAML

```yaml
The default one with the fastflow
```

### Logs

```shell
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexriedel1** [comment]
The convolution mode parameter isn't supported in ONNX: https://pytorch.org/docs/stable/onnx_supported_aten_ops.html

It is used for the padding mode "same" in the fastflow model:
https://github.com/openvinotoolkit/anomalib/blob/7bc2330e29d295aaa7aa68bdd20b4711f9f701ec/src/anomalib/models/fastflow/torch_model.py#L42-L48

You can implement the "same padding" convolution like this as a workaround: https://discuss.pytorch.org/t/pth-to-onnx-convolution-mode-error/146817/5

**Comment by xiaoyunwei** [comment]
> The convolution mode parameter isn't supported in ONNX: https://pytorch.org/docs/stable/onnx_supported_aten_ops.html
> 
> It is used for the padding mode "same" in the fastflow model:
> 
> https://github.com/openvinotoolkit/anomalib/blob/7bc2330e29d295aaa7aa68bdd20b4711f9f701ec/src/anomalib/models/fastflow/torch_model.py#L42-L48
> 
> You can implement the "same padding" convolution like this as a workaround: https://discuss.pytorch.org/t/pth-to-onnx-convolution-mode-error/146817/5

Thanks for the workaround.
