### ISSUE TITLE
[Task]: Drift between code and quick-start-toturial

### ISSUE THREAD

**Issue by TorAP** [openvinotoolkit/anomalib#984]
### What is the motivation for this task?

When I follow this Training with Custom Data -guide: https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html I cannot run the training: python tools/train.py --config custom_padim.yaml. Where the config is as in the tutorial. I get the this error: AttributeError: 'NoneType' object has no attribute 'keys'. When I guess is most likely becuase there is no data, but the I checked the paths and the dataset hazelnut_toy. 

### Describe the solution you'd like

Updated guide..

**Comment by Ravindu987** [comment]
Hi 
I also encountered the same error and resolved it this way.

First make sure all configs under `dataset` is indented. If you copy and paste from the [guide](https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html) they might not be indented.

Then I had to add these configs as I got `Missing key` errors for these
`normalization: imagenet`
`test_split_mode: from_dir`
`val_split_ratio: 0.5`

Also if you downloaded the dataset from the provided link, the extracted folder is named `hazelnut_toy` and in the given config it is named `Hazelnut_toy`. Change one of them to match.

Let me know if it works after making these changes.

**Comment by Ravindu987** [comment]
@samet-akcay  shall I make these changes and do a PR or is someone already on it

**Comment by samet-akcay** [comment]
@Ravindu987, if you could make the changes, that'd be great. Currently there is no one working on it

**Comment by Ravindu987** [comment]
Will do the necessary.
